#import "_pseudocode.typ": *

#chapter([The Flat Baseline], label: <chap:methodology>)

#section([The Anatomy of the Proof], label: <sec:proof-anatomy>)

Recall the statement we are after, first mentioned at the end of @sec:motivation and formally defined in @sec:prob-formulation: given a complete weighted graph on $N$ nodes, the prover knows a Hamiltonian cycle whose total cost does not exceed a public threshold $T$. We want the verifier to come away convinced this is the case without learning anything else---not the cycle, not its exact cost. Our task is to turn that one sentence into a zero-knowledge proof. More precisely, we go from the statement to a set of arithmetic constraints that together form a circuit, through a process called arithmetization. That circuit is what lets us build a zk-SNARK, which in turn lets us prove knowledge of a witness satisfying the circuit without revealing it.

#subsection([Defining the Witness], label: <sub:witness-def>)

The private witness is the cycle itself. Its exact cost is private too, but it can be derived directly from the cycle through the cost matrix, so it is never an explicit input the prover supplies. We represent the cycle as an array of node indices, where the $i$-th entry names the $i$-th node visited. The closing edge we leave implicit: once all $N$ nodes have been visited, the tour returns to where it began, but that final step back to the start is not written down. So an array of $N$ entries stands for $N$ directed edges, of which $N-1$ are given explicitly by consecutive entries and the last---the return to the start---is read off by convention rather than stored. Treating closure as a convention we read into the array, rather than a fact recorded in it, costs us no generality and buys two small conveniences: it keeps the encoding lean, and it means that proving a statement about an open path instead of a closed cycle---one that need not return to its first node---is a change of a single line in the implementation.

Now that we know what the witness looks like, the natural question arises: what must be true of that array for it to encode a valid, cheap-enough tour---that is, a valid witness?

#subsection([Defining the Constraints], label: <sub:constraints-def>)

We closed the last section with a reasonable question, and we are now ready to answer it. For the array to carry a valid witness, exactly three things must hold, and we encode each as its own block of constraints, which we call a _constraint group_. Together the three groups certify that the array describes a valid, sub-threshold tour. The numbering is not mere bookkeeping: these three groups are the skeleton every circuit in this thesis shares, and reading it once here buys the reader all the constructions to come. The hierarchical approaches will bend the groups only slightly, adapting them to hold for local segment proofs as well as for the single global proof of the flat approach.


- Group 1: _Permutation_
  #block(
    stroke: (left: 1.5pt + colors.primary),
    inset: (left: 10pt),
    height: 35pt,
    above: 1em,
    align(horizon)[
      The cycle visits every node exactly once: its entries are a permutation of the set ${0, dots, N-1}$.
    ]
  )
#v(5pt)
- Group 2: _Edge Cost_
  #block(
    stroke: (left: 1.5pt + colors.primary),
    inset: (left: 10pt),
    height: 55pt,
    above: 1em,
    align(horizon)[
      The cost charged for each edge is that edge's true cost under the (committed) cost matrix, and not some convenient number the prover invented.
    ]
  )
#v(5pt)
- Group 3: _Threshold_
  #block(
    stroke: (left: 1.5pt + colors.primary),
    inset: (left: 10pt),
    height: 15pt,
    above: 1em,
    align(horizon)[
      The $N$ edge costs sum to at most the public threshold $T$.
    ]
  )

It is worth pausing on what each group is there to stop, because every one of them closes a door a dishonest prover would otherwise walk through. Group 1 is what forces the route to be a genuine tour rather than a convenient walk: by demanding that the cycle be a permutation of the nodes, it prevents a dishonest prover from revisiting a cheap node and quietly skipping an expensive one, to avoid paying its cost, while still presenting what looks like a sequence of $N$ steps. Group 2 ties the proof to reality: edge costs are not numbers the prover hands over but values fixed in advance by the (committed) cost matrix, so this group is what stops the prover from charging a lower price than the graph actually demands. Group 3, finally, is the claim itself---that the tour comes in under budget---and is the one assertion the entire proof exists to make. The first two groups, in a sense, are there only so that the third means what we want it to mean.

The division is exhaustive: a witness that satisfies all three is a valid sub-threshold tour, and every valid sub-threshold tour satisfies all three. Its real value, though, is that the three groups are _orthogonal_: changing one leaves the others untouched. Group 3, the threshold, is settled once and never touched again; Group 1, the permutation mechanism, and Group 2, the way edge costs are bound, are the two knobs the rest of the thesis turns---and every variant we build turns exactly one. That is what later lets us read a change in cost as the work of a single group rather than an unattributable mix.

#subsection([Assembling the Circuit], label: <sub:assembling>)

We began with a single sentence defining our claim and broke it into three constraints stated in plain words. But we are yet to have something a prover can run. The next thing to do is to express the same three groups in program form: not the real code yet, that will come at the right time later on, but a pseudocode close enough to it that the shape of the circuit, and its costs, start to show through.

Two choices have to be made before we can write anything down, and for both, the first instinct is the starting point. The first choice is about how to retrieve edge costs. Indeed, the circuit must somehow get at the edge costs, and the simplest way imaginable is to hand it the whole cost matrix as a public input: the prover and verifier already agree on the graph, so we give the circuit all $N^2$ entries and let it look up whatever it needs. We start there because it asks for no machinery and it simply works. It is worth flagging already that handing over the entire matrix is not the only way to give the circuit access to it: one could instead commit to the matrix and feed in only a short fingerprint, proving each looked-up cost against it. We will not need that yet, so we set it aside---but we mark the spot, because those $N^2$ public inputs will come back to bite us, and dealing with them is a crucial point in the sections to come.

One implementation detail deserves a word, since the listing that follows quietly leans on it. The cost matrix is by nature an $N times N$ table, but we do not store it as one: we flatten it row by row into a single one-dimensional array of $N^2$ entries, putting the cost of the directed edge from node $i$ to node $j$ at index $i dot N + j$. The reason is simple---a flat array is the shape the tooling handles most readily, from Noir's `Prover.toml` down to the Python script that formats the inputs---but it is worth clarifying, because it is exactly the arithmetic Group 2's lookup performs, and the same address $i dot N + j$ will reappear in @sec:representation when we commit to the matrix instead of publishing it.

The second choice is how to enforce Group 1---that the cycle is a permutation of the nodes---and here too the natural move is the direct one. If you wanted to convince yourself, in any ordinary program, that a list of $N$ numbers had no repeats, you would compare every entry against every other and make sure no two coincide. That pairwise distinctness check is the first thing we write. On its own, though, it is not enough: it guarantees that no node is visited twice, but not that every node is visited exactly once, because it does not check that the entries are real nodes---a prover could hand over $N$ distinct numbers that overshoot the graph entirely. To close this gap we add a _range check_, forcing every entry to be a valid node index. The two together do amount to a permutation of the nodes: $N$ entries, all distinct and all in range, must by the pigeonhole principle be exactly the nodes, each visited once. It is a correct check, but---as the gate count will shortly remind us---a quadratic one; cheaper mechanisms exist, and a stronger one will later enforce the permutation directly, with no separate range check. For now, the brute-force version is the honest starting point.

One convention before the listing that shows the pseudocode for our circuit. We write #inline[require] $P$ for a constraint: a relation the witness is obliged to satisfy for the proof to go through. The word is deliberate. In the real Noir source code this same line is written with an #inline[assert], but that name is a little misleading---it is not the runtime check of an ordinary program, which tests that a condition holds and halts when it does not. A circuit cannot test anything at run time; Noir translates the instruction into constraints behind the scenes. We write #inline[require] $P$ to record exactly that: we are adding $P$ to the system of equations the proof must satisfy, and a witness that violates it is not a witness in the first place. The signature, likewise, names the public and private inputs explicitly, since that split is the privacy surface that we analyze throughout this work.

With all of this in mind, we are now ready for our circuit pseudocode specification, presented in @fig:flat-pairwise that follows.

#[
  #set text(font: "Libertinus Sans")
  #figure(
    kind: "listing",
    supplement: "Listing",
    caption: [The flat baseline in its simplest form: the public-matrix representation of @sec:representation with the pairwise permutation check of @sec:permcheck.],
    pseudocode-list(hooks: 0.5em, booktabs: true, booktabs-stroke: 1pt)[
      + *circuit* #fn[flat-full-pairwise]$(N)$ #h(1fr)
        + *public* $matrix[rng(0, N^2-1)], med T$
        + *private* $cycle[rng(0, N-1)]$
        - #hide("")
        - #lc[Group 1: _permutation, by range + pairwise distinctness_]
        + *for* $i$ *in* #fn[range]$(0, N)$:
          + *require* $cycle[i] < N$
        + *for* $i < j$ *in* #fn[range]$(0, N)$:
          + *require* $cycle[i] != cycle[j]$
        - #hide("")
        - #lc[Group 2: _edge cost, by direct lookup into the public matrix_]
        + $total arrow.l 0$
        + *for* $i$ *in* #fn[range]$(0, N)$:
          + $total arrow.l total + matrix[cycle[i] dot N + cycle[(i+1) pmod N]]$
        - #hide("")
        - #lc[Group 3: _threshold_]
        + *require* $total <= T$
    ]
  ) <fig:flat-pairwise>
]

Two details in this small circuit deserve a closer look, because each is a lesson in what "writing a sentence as constraints" really costs.

The first hides in plain sight. The line #inline[require] $cycle[i] != cycle[j]$ looks exactly like a not-equal test one would write in any language, and that resemblance is precisely the trap: a circuit has no such test. It can assert that two polynomials are equal; it cannot directly assert that two values differ. So where does the $!=$ go? It is shorthand for a small trick. A field element $d$ is nonzero exactly when it has a multiplicative inverse, so in order to prove that $d = a - b$ is nonzero it is enough to exhibit one. The prover, while generating the witness---off to the side, in ordinary arithmetic that costs the circuit nothing---computes $w = d^(-1)$ and supplies it as an extra private input. The circuit then enforces the single equality $d dot w = 1$. If $a$ and $b$ differ, the honest prover's $w$ satisfies it; if $a = b$, then $d = 0$, no inverse exists, and no value of $w$ can make $d dot w = 1$---the constraint is simply unsatisfiable, and no proof can be formed. So the $!=$ in the listing quietly conceals two things the figure does not show: an extra witness value, the inverse, and one multiplication constraint. This is the SNARK style in miniature, a pattern we will meet again and again---let the prover compute freely and out of sight, and have the circuit check only a cheap relation on the result. The cost here is one inverse and one constraint per pair of positions, hence $N(N - 1) \/ 2$ of them, beside which the $N$ range checks barely register: this is exactly the quadratic the next section sets out to escape.

The second detail is a subtlety in Group 2 that we will meet again in @sec:witness-inversion and that is easy to walk past and important to get right: an array lookup that looks free can be one of the most expensive things a circuit does. To understand this, look closely at the cost lookup presented in the listing, $matrix[cycle[i] dot N + cycle[(i+1) pmod N]]$: it actually tangles together two kinds of array access, and telling them apart is the whole point. The inner reads $cycle[i]$ and $cycle[(i+1) pmod N]$ fetch cycle entries at positions that are plain constants---the loop is unrolled at compile time (see @sec:snarks), so $i$ runs through $0, 1, dots, N-1$, and $(i+1) pmod N$ is just as fixed at each step. This means that even if the values sitting at those positions are secret---they are part of the prover's witness---the positions themselves are settled before any secret is chosen. The outer read into $matrix$ is the opposite case: its index is built out of those secret values, so the position it points to is not known until proving time. Surprisingly, the obvious difference between the two reads---that the cycle's values are secret and the matrix's public---is not the one the circuit cares about: secrecy decides who learns what, but it does nothing to the cost of a read. Then what is the true difference? The position---which slot of the array a read draws from. For the cycle that slot is fixed when the circuit is compiled; for the matrix it takes shape only at proving time. So what divides a cheap read from a costly one is not whether the value is public or private, but whether its position is known in advance: a value whose position is fixed ahead of time is almost free to read, while one whose position is determined by the witness---that is, only at proving time---is costly.

Why should a secret position cost so much more than a secret value? Because a circuit is a fixed wiring diagram, soldered once, before any witness exists. Something like "Read position $3$ of the cycle" is a wire you can attach in advance: you need not know what value will flow along it, only which terminal to reach for. By contrast, "Read position $k$ of the matrix"---where $k$ surfaces only at proving time---cannot be wired in advance at all: with the diagram already fixed, the circuit has no way to know which of the $N^2$ terminals it should connect, and so cannot reach a value whose position is decided only once the witness exists. The way around it is, once again, the pattern we met with the $!=$ check: have the prover compute, out of sight, what the circuit cannot, and let the circuit check only that the result is consistent.

This check is a general construction---_offline memory checking_, or a _read-only-memory (ROM) lookup_ in the circuit's own terms---used widely enough to be worth understanding in its own right, and explained in @sec:snarks. However, the thing that matters here is its price. A read at a fixed position is cheap and consists of a single wire; a read at a witness-chosen position is expensive, because it drags in that whole check---paid once for every such access, and assembled by the prover's witness solver before proving can even begin.

With the baseline circuit in hand, the next step is optimization. Two questions arise immediately. The first stems from the quadratic permutation check: is there a more efficient way to prove that the cycle is a permutation of the nodes? The second concerns the public inputs: only $N$ edge costs are used, but the full cost matrix of $N^2$ entries is always supplied, making the number of public inputs quadratic in $N$. Is there a way to reduce this public input surface? We address these two questions next.

#section([Five Ways to Check a Permutation], label: <sec:permcheck>)

The first of those two questions is the subject of this section, and it has more than one answer---five, of which the pairwise check of @sec:proof-anatomy is the first and the worst. That check is correct but quadratic: it compares every position against every other, $N(N-1) \/ 2$ comparisons in all. What we want is a check that scales linearly with $N$, and the four candidates ahead all get there---by different routes, and, as we will see, paying in different coins. The section does three things, in that order. It first introduces each mechanism in turn: the idea, what the prover supplies, what the circuit checks, and an itemized account of what that costs. It then puts all of them on the bench and measures them on identical instances (@sub:mech-measured). And it finally chooses the two mechanisms the rest of the thesis carries (@sub:choosing). One warning is owed up front, because it changes how the cost analyses should be read: the choice will not be made by the costs. The accounts cannot settle it---their items, we will see, carry very different gate prices---and the measurements, when they arrive, end in a near-tie. What settles it is a criterion that appears on no account at all: what each mechanism turns into when, in the chapters after this one, the single global proof is cut into pieces. The cost analysis is not wasted work for that. Working through it is how the mechanisms' anatomy is understood---how operations a programmer takes for granted, an array write, a lookup, a comparison, a hash, are actually realized inside a circuit, and at what price---and that understanding is precisely what the final argument runs on.

There is a natural order in which to take the four, and it is set not by cleverness but by _memory_. A circuit's cheapest reads are those whose position is fixed before any witness exists; dearer are the reads whose position the prover chooses (@sec:proof-anatomy); dearer still are the cells the circuit must also _write_. So we begin with the most human check of all---the one a person keeps on a clipboard---and find that it asks for the heaviest memory the tooling offers. That cost is our cue to get cleverer: the next two mechanisms step down from read--write memory to read-only, and the last gives up prover-chosen memory altogether. Three of the four---presence, sort, and inverse-permutation---are _exact_: when they pass, the cycle simply _is_ a permutation, with the certainty of an algebraic identity. The fourth, the grand product, is different in kind, trading that certainty for a probabilistic argument, and the trade is deliberate; we build toward it last. Throughout, the only thing changing is Group 1; Groups 2 and 3 stay fixed, so any cost difference between two of these circuits is the price of the permutation mechanism and nothing else---the discipline that organizes the whole thesis.

Since every mechanism is about to be given a price, a word on how prices will be stated, because it is easy to do badly. The temptation is to count _constrained operations_ and compare totals. The trouble is that the operations are not alike: a range check, a memory access, and---further down the section---a hash invocation compile to very different numbers of gates, and a total that adds them pretends otherwise. So we allow ourselves two kinds of statement and no third. We _itemize_: each mechanism's bill is a list of items with multiplicities, read straight off its listing. (Equality checks at fixed positions compile to wiring and stay off the bills; a read that must match an expected value is one item, a read.) And we _count to classify_: a tally settles whether a mechanism is linear or quadratic, because no price tag changes an exponent---but it is never allowed to rank two linear mechanisms. That question belongs to measurement, and @sub:mech-measured answers it. One further distinction the accounts must respect, since two of the mechanisms ahead lean on the pattern of @sec:proof-anatomy and hand work to the prover: each mechanism keeps _two ledgers_. The in-circuit ledger lists the constrained operations---these become gates, and the verifier's guarantee rests on them and on nothing else. The off-circuit ledger lists the work the prover performs while building the witness---computing hints, sorting, scanning---which lays down no gates and attests nothing, but takes real time at every single proof. We will find the second ledger to be anything but a footnote.

#subsection([Marking as We Go], label: <sub:presence>)

Ask a person to check that a list of $N$ names holds each guest exactly once, and they will neither sort it nor invert it: they will run a finger down the list and tick each name against a sheet, watching for one already ticked. It is the most direct check imaginable, and it ports into a circuit almost verbatim. The circuit keeps a boolean array $seen$ of length $N$, every entry false to start and built into the circuit's own structure rather than handed in by the prover---so that a cheat cannot quietly pre-tick it. Then it scans the cycle once: at position $i$ it reads $seen[cycle[i]]$, asserts the entry is still false (this node has not been visited before), and sets it to true. Should two positions name the same node, the second visit finds the mark already set and the assertion fires. One guard is needed, since $cycle[i]$ is used as an index into $seen$: an explicit range check $cycle[i] < N$ must ride along, for an out-of-range index would be meaningless. With it in place, $N$ values that are distinct and in range are exactly ${0, dots, N-1}$, each once.

Before pricing it, one feature of this check deserves to be named---plainly, and without judgment yet---because it is the structural fact the whole mechanism stands on: the tick sheet is _addressed by node value_. The expression $seen[cycle[i]]$ uses a witness value as a physical position in an array, and that is possible only because the set being checked against is ${0, dots, N-1}$---a contiguous range, fixed when the circuit is compiled, so that a dense array with exactly one cell per node exists to be addressed. The check, in other words, never compares the cycle against a target it was handed; it compares it against a target _baked into its own geometry_. Nothing is wrong with that here. We record the fact and move on; it will carry weight in @sub:choosing.

What this check makes plain---and what earns it the opening slot---is the distinction every later cost turns on: the kind of _memory_ a circuit uses. The $seen$ array is not read-only. The circuit writes to it as it scans, and a read at step $j$ must reflect a write made at an earlier step $i < j$. That is a read--_write_ memory, a RAM, and the tooling backs it with the heaviest construction in this section: a table in which every access is logged and a consistency argument---a sorted permutation of the access trace, policed by its own timestamps---proves that each read returns the value most recently written to that cell. The in-circuit ledger is accordingly the longest we will write: $N$ initializing writes, $N$ reads, $N$ marking writes, and $N$ range checks guarding the indices, with all the memory traffic on the dearest memory the tooling offers. The off-circuit ledger, by contrast, is empty: the prover supplies the cycle and nothing else---there is no hint to compute. And what the long bill buys back is auditability: no library call, no supplied map to distrust, just a sequential scan whose soundness fits in a sentence---worth something in a proof whose whole purpose is to be believed. But the bill also tells us what to attack. If the costly thing is read--write memory, the natural question is whether the same guarantee can be had with memory the circuit only ever _reads_. It can; the next two mechanisms show how.

#subsection([Sorting the Cycle], label: <sub:sort>)

The tick-sheet's expense was the writing. Forbid the circuit to write, then, and let it only read---and, in the move we have leaned on twice already, let the prover do the real work outside the circuit altogether. The most familiar such check is to _sort_: a list is a permutation of ${0, dots, N-1}$ exactly when, sorted, it reads $0, 1, 2, dots, N-1$. Sorting is ruinous inside a circuit but free outside it, so the prover sorts the cycle while preparing the witness and hands the result in as a private _hint_, the array $sorted$. The circuit never sorts; its entire job is to decide what that handed-in array is worth.

It is worth naming the split this leans on, because it is the engine of every mechanism that hands work to the prover. The tooling gives us two kinds of code. _Unconstrained_ code runs while the witness is being built: it computes values but lays down no constraints, adds no gates, and the verifier never sees it---the prover may sort, search, or invert, however convenient, for free. _Constrained_ code is the circuit proper: each line becomes gates and is part of what the proof attests. In the implementation the two meet in a single standard-library call, #inline[sort_via], which runs an ordinary quicksort in unconstrained code and then lays down constraints about its output. A free quicksort sounds too good, and the catch sits exactly where it sounds like there should be one: nothing about the quicksort is attested. It leaves no trace in the constraint system, so the proof cannot tell whether it ran, ran correctly, or was replaced wholesale by something else. From the circuit's point of view, $sorted$ is not "the output of a sort"; it is one more private input, chosen by a prover we must assume dishonest, and every property we intend to rely on must be re-established, in gates, as if the array had arrived from an adversary---because it may have. @fig:flat-sort shows the resulting Group 1: the sort itself (a) is unconstrained and free, and three constrained checks (b)--(d) decide what the hint is worth.

#[
  #set text(font: "Libertinus Sans")
  #figure(
    kind: "listing",
    supplement: "Listing",
    caption: [The _sort_-based permutation check, replacing Group 1 of @fig:flat-pairwise. The prover supplies the sorted cycle as a hint; the circuit checks it is sorted, is a rearrangement of the cycle, and equals $0, dots, N-1$. Groups 2--3 are unchanged.],
    pseudocode-list(hooks: 0.5em, booktabs: true, booktabs-stroke: 1pt)[
      + *circuit* #fn[flat-full-sort]$(N)$ #h(1fr)
        + *public* $matrix[rng(0, N^2-1)], med T$
        + *private* $cycle[rng(0, N-1)], med sorted[rng(0, N-1)]$ #h(1fr) #lc[(a) hint $= "sort"(cycle)$]
        - #hide("")
        - #lc[Group 1: _permutation, by an off-circuit sort_]
        + *for* $i$ *in* #fn[range]$(0, N-1)$: #h(1fr) #lc[(b) is sorted]
          + *require* $sorted[i] <= sorted[i+1]$
        + *require* #fn[check_shuffle]$(cycle, sorted)$ #h(1fr) #lc[(c) same multiset, $approx 2N$ reads]
        + *for* $i$ *in* #fn[range]$(0, N)$: #h(1fr) #lc[(d) is the identity]
          + *require* $sorted[i] = i$
        - #hide("")
        - #lc[Group 2 (edge cost) and Group 3 (threshold) exactly as in @fig:flat-pairwise]
    ]
  ) <fig:flat-sort>
]

Let us establish the checks one at a time, by asking what a cheating prover could do with each of them absent. The end state we want is the identity: the cycle's values, in some order, are $0, 1, dots, N-1$. The most direct constraint toward it is check (d), entry-by-entry equality $sorted[i] = i$. Suppose it were the only one. Then $sorted$ is pinned completely---and tied to nothing: a cheat submits the identity array as its "sorted" hint and any cycle whatsoever beside it, and the circuit, having never compared the two, accepts. The hint satisfies every constraint while certifying nothing; Group 1 has quietly evaporated. What is missing is the link: a proof that $sorted$ and $cycle$ hold _the same multiset of values_, each a rearrangement of the other. That is check (c), the standard-library routine #inline[check_shuffle], and with (c) and (d) together the argument closes: the cycle's values, rearranged, are exactly $0$ through $N-1$, each once---the cycle is a permutation of the nodes. Two constrained checks, and the guarantee is complete. The reader counting along will notice the listing contains a third. Check (b) asserts that $sorted$ is, in fact, sorted---one comparison $sorted[i] <= sorted[i+1]$ per adjacent pair, $N-1$ in all---and given (d) it is logically redundant: an array forced entry-by-entry to equal $0, dots, N-1$ is in order by inspection. It is on the bill because it arrives bundled with the library call. The contract of #inline[sort_via] is "a sorted rearrangement of the input"---sortedness (b) plus multiset equality (c)---since the library cannot know that this particular caller's next move is to pin the array to the identity; for a general caller, sortedness _is_ the deliverable. We could write a bespoke Group 1 that drops (b); we keep the library routine, and the bill records what is paid, not what logic strictly requires.

Check (c) hides the cost, and it repays opening up, both because it dominates the bill and because its shape will explain the next mechanism. #inline[check_shuffle] is the pattern in miniature (@fig:check-shuffle). First, unconstrained: the prover finds the map carrying one array onto the other---a list $idx$ of positions with $cycle[i] = sorted[idx[i]]$---by whatever means, for free. Then, constrained, it verifies that hint in _two_ passes. The first proves $idx$ is a genuine permutation of the positions $0, dots, N-1$, that no slot is reused; without it a prover could aim several cycle entries at one sorted entry and smuggle in a duplicate. The second proves the map actually carries the cycle across, $sorted[idx[i]] = cycle[i]$. Each pass reads an array at a position the prover chose---$idx$ in the first, $sorted$ in the second---so the routine spends about $2N$ of those dynamic, prover-chosen lookups. There is a small irony in pass 1 worth savoring: to prove that the cycle is a permutation, the library proves that a _map_ is a permutation---our original statement, one level removed, only now over the positions $0, dots, N-1$ rather than the nodes. The problem has not been solved so much as relocated to a place where it is cheaper to check.

#[
  #set text(font: "Libertinus Sans")
  #figure(
    kind: "listing",
    supplement: "Listing",
    caption: [Inside #inline[check_shuffle]: an unconstrained hint, then two constrained passes costing $approx 2N$ prover-chosen reads. Pass 1 is itself an inverse-permutation check applied to the shuffle map---a fact @sub:invperm will cash in.],
    pseudocode-list(hooks: 0.5em, booktabs: true, booktabs-stroke: 1pt)[
      + *procedure* #fn[check_shuffle]$(cycle, sorted)$ #h(1fr)
        - #lc[unconstrained: find $idx$ with $cycle[i] = sorted[idx[i]]$]
        + $idx[rng(0, N-1)] arrow.l$ #fn[find_shuffle]$(cycle, sorted)$
        - #hide("")
        - #lc[pass 1 --- $idx$ is a permutation of $rng(0, N-1)$ (no slot reused)]
        + *for* $v$ *in* #fn[range]$(0, N)$:
          + $p arrow.l$ #fn[index_of]$(v, idx)$ #h(1fr) #lc[unconstrained]
          + *require* $idx[p] = v$
        - #hide("")
        - #lc[pass 2 --- the map carries $cycle$ onto $sorted$]
        + *for* $i$ *in* #fn[range]$(0, N)$:
          + *require* $sorted[idx[i]] = cycle[i]$
    ]
  ) <fig:check-shuffle>
]

Now the two ledgers, kept apart as the section's convention demands. Off-circuit, the prover pays twice: once for the quicksort itself, and once for discovering the shuffle map---as the listing writes it, a scan per value, real work performed at every proof with not a line of it constrained. In-circuit, the bill reads: $N-1$ ordering comparisons (check (b), paid for the reason just given), about $2N$ prover-chosen reads (check (c)), and the $N$ identity equalities of check (d), which sit at fixed positions and by the convention of this section stay off the bill. On memory, the whole check is already lighter than the tick-sheet: it only ever _reads_ its arrays, never writes them, so it lives in read-only memory (ROM) rather than read--write RAM---and read-only memory carries no write-consistency argument, which was the dearest part of the RAM construction. A bonus falls out, too: $sorted = 0, dots, N-1$ together with $sorted$ a rearrangement of $cycle$ already forces every cycle entry into range, so the separate range check that the pairwise and presence circuits needed is here subsumed, free. What neither ledger can show, and what @sub:mech-measured will put a number to, is how the two interact: those $approx 2N$ prover-chosen reads, and the off-circuit work behind them, will turn out to cost far more to _solve_ than to count.

#subsection([Supplying the Inverse], label: <sub:invperm>)

Look again at what the sort spent its money on. The first pass of #inline[check_shuffle] did nothing but prove that a supplied map was a permutation of $0, dots, N-1$---which is _the very thing we set out to prove_, only about the shuffle map rather than the cycle. The sort, that is, routes the cycle to the identity through a go-between, the sorted array, and pays to validate both legs of the trip: cycle-to-sorted, then sorted-to-identity. If the prover could point us straight from the cycle to the identity, the go-between would vanish, and one of the two legs with it.

That is the inverse-permutation check. The prover supplies a private array $invperm$ where $invperm[v]$ claims the position in the cycle at which node $v$ sits---the inverse of the map the cycle defines. The circuit walks $v$ from $0$ to $N-1$ and checks two things at each step: that $invperm[v]$ is in range, and that the cycle really carries $v$ there, $cycle[invperm[v]] = v$. That is the whole of it (@fig:flat-invperm). Two distinct nodes cannot claim the same position---one cell cannot hold both---so the positions are forced distinct, and $N$ distinct in-range positions matched to the $N$ values $0, dots, N-1$ make the cycle a permutation. Range is subsumed once more, and the off-circuit ledger is the shortest a hint can have: one linear scatter, $invperm[cycle[i]] = i$---no sorting, no searching---against the sort's quicksort and per-value scans.

#[
  #set text(font: "Libertinus Sans")
  #figure(
    kind: "listing",
    supplement: "Listing",
    caption: [The inverse-permutation check: one pass, $N$ prover-chosen reads---the sort with the go-between removed. The value $v$ serves at once as the array index and the expected value, the economy the implicit identity target allows. Groups 2--3 unchanged.],
    pseudocode-list(hooks: 0.5em, booktabs: true, booktabs-stroke: 1pt)[
      + *circuit* #fn[flat-full-invperm]$(N)$ #h(1fr)
        + *public* $matrix[rng(0, N^2-1)], med T$
        + *private* $cycle[rng(0, N-1)], med invperm[rng(0, N-1)]$ #h(1fr) #lc[hint: $invperm[cycle[i]] = i$, an $O(N)$ scatter]
        - #hide("")
        - #lc[Group 1: _permutation, by a supplied inverse map_]
        + *for* $v$ *in* #fn[range]$(0, N)$:
          + *require* $invperm[v] < N$ #h(1fr) #lc[position in range]
          + *require* $cycle[invperm[v]] = v$ #h(1fr) #lc[read $cycle$ at a chosen position]
        - #hide("")
        - #lc[Group 2 (edge cost) and Group 3 (threshold) exactly as in @fig:flat-pairwise]
    ]
  ) <fig:flat-invperm>
]

The ledgers, side by side with the sort's. In-circuit: $N$ range checks and $N$ reads, against $N-1$ orderings and $approx 2N$ reads. The per-entry guards pair off, range checks against orderings, leaving as the whole of the saving the leg we removed: where the sort proved a map a permutation (pass one) _and_ that it carried the cycle across (pass two), the inverse check does the first job directly against the cycle and needs no second---one pass, $N$ prover-chosen reads in place of $approx 2N$. Off-circuit: one scan, against a sort and a search. Inverse-permutation is the sort with the hop taken out; its memory is the same read-only ROM, and only the counts differ---on both ledgers at once.

One more feature must be named before the price can be understood, because the lightness of this check is not all honest economy. Every permutation check compares the cycle against a _target_ set, and this one's target is _implicit_. Watch the value $v$ in $cycle[invperm[v]] = v$: the same $v$ is at once the _index_ into $invperm$ and the _value_ we expect to find. The two roles fuse into one number only because the target is the contiguous range $0, dots, N-1$, so that a node value can serve directly as an array position; nothing need be supplied or stored to name the target, because the loop counter spins it out for free. We have seen this device before. It is the tick-sheet's addressing trick from @sub:presence#[]---there a value addressed a mark cell, here it addresses a slot of the inverse map---and the sort, for the record, touches the same free target in its check (d) but uses it only as _data_, comparison values on the right-hand side, never as an address. Two of our three linear exact mechanisms, then, are built on the same quiet assumption: that the set being checked against is ${0, dots, N-1}$ itself, contiguous and known when the circuit is compiled. What becomes of them when that assumption fails is the hinge of @sub:choosing; we mark the spot. For the flat proof the assumption holds, the economy is real, and of the exact mechanisms inverse-permutation is the leanest on both ledgers.

#subsection([From Sets to Polynomials], label: <sub:grand-product>)

The three mechanisms so far are variations on one theme: each proves, _exactly_ and with certainty, that the cycle's multiset of values is ${0, dots, N-1}$. The fourth abandons certainty for something subtler and, as we will see across the rest of this thesis, far more useful. It is worth saying at the outset that at this point in the story---a single, flat proof---the grand product is not the rational choice. It is more elaborate than the sort, and it trades away a guarantee for a gamble, in exchange for a benefit that, here, is exactly zero. We introduce it anyway, and now, because it is the next mechanism in the permutation family and because the benefit it cannot collect at the flat level is precisely the one that decomposition will later make decisive. The reader is asked to file it away; the first installment of that argument comes due in @sub:choosing, and the chapters beyond collect it in full.

The idea begins with a reformulation. To say that the multiset ${cycle[0], dots, cycle[N-1]}$ equals the multiset ${0, dots, N-1}$ is to say that the two collections agree, with multiplicity, as _sets of numbers_---order forgotten. There is a classical way to test multiset equality with a single number. Form, from each side, the polynomial that collects one linear factor per element, and compare the two polynomials:
$
P(Y) = product_(i=0)^(N-1) (Y + cycle[i]), quad Q(Y) = product_(j=0)^(N-1) (Y + j).
$
Distinct values yield distinct factors, and a product of linear factors determines them uniquely, so $P$ and $Q$ are equal _as polynomials_ if and only if the two multisets coincide---each shared value contributes the identical factor, and any discrepancy leaves a factor unmatched. So the permutation question becomes a question about whether two polynomials are the same.

Checking that two polynomials are identical sounds harder than what we started with, not easier; the saving comes from not checking it everywhere, only at one point. Evaluate both products at a single field value $X$ and compare the two numbers $P(X)$ and $Q(X)$. If the multisets are equal the polynomials are identical and the two numbers agree at every $X$. If the multisets differ, the difference $D = P - Q$ is a nonzero polynomial of degree at most $N-1$, and such a polynomial has at most $N-1$ roots in the field; so the two numbers agree only if $X$ happens to be one of those at most $N-1$ unlucky points, out of a field of size on the order of $2^254$. This is the Schwartz--Zippel principle: a nonzero low-degree polynomial is almost nowhere zero, so an identity that holds at a random point almost certainly holds everywhere.

Everything now turns on that word _random_. If the prover could see $X$ before committing to the cycle, a cheater could fix a bogus cycle and then search for one of the $N-1$ roots of its own difference polynomial, and the check would be worthless. The challenge $X$ must therefore be unpredictable to the prover and yet reproducible by the verifier, with no interaction between them. The standard device for this is the Fiat--Shamir transform, which we treat properly in @sec:fiat-shamir: in place of a challenge drawn by a live verifier, one _derives_ the challenge by hashing the data the prover has already committed to. Here the circuit computes $X$ by hashing the entire cycle with the Poseidon2 hash---chaining $h_(j+1) = H([h_j, cycle[j]])$ across all $N$ entries and folding the result once more into $X$---so that $X$ depends on every node the prover chose. Modeled as a random oracle, the hash returns a value the prover cannot anticipate and cannot steer, fixed once the cycle is fixed. The same $cycle$ array feeds both the hash chain and the products, which is what stops a prover from deriving $X$ from one cycle and running the product over another. With $X$ pinned this way, a wrong multiset survives with probability at most $(N-1) \/ |FF|$---below $2^(-240)$ at every instance size we run, negligible by any standard.

The pseudocode is short, and the shape of the cost is visible in it.

#[
  #set text(font: "Libertinus Sans")
  #figure(
    kind: "listing",
    supplement: "Listing",
    caption: [The grand-product permutation check. The challenge $X$ is hashed from the cycle in-circuit (Fiat--Shamir), then the two multiset polynomials are compared at that single point. Groups 2--3 unchanged.],
    pseudocode-list(hooks: 0.5em, booktabs: true, booktabs-stroke: 1pt)[
      + *circuit* #fn[flat-full-product]$(N)$ #h(1fr)
        + *public* $matrix[rng(0, N^2-1)], med T$
        + *private* $cycle[rng(0, N-1)]$
        - #hide("")
        - #lc[Group 1a: _derive the Fiat--Shamir challenge from the whole cycle_]
        + $h arrow.l 0$
        + *for* $j$ *in* #fn[range]$(0, N)$:
          + $h arrow.l$ #fn[H]$(h, cycle[j])$
        + $X arrow.l$ #fn[H]$(h)$
        - #hide("")
        - #lc[Group 1b: _compare the two products at_ $X$]
        + $lhs arrow.l 1, quad rhs arrow.l 1$
        + *for* $i$ *in* #fn[range]$(0, N)$:
          + $lhs arrow.l lhs dot (X + cycle[i])$
          + $rhs arrow.l rhs dot (X + i)$
        + *require* $lhs = rhs$
        - #hide("")
        - #lc[Group 2 (edge cost) and Group 3 (threshold) exactly as in @fig:flat-pairwise]
    ]
  ) <fig:flat-grandproduct>
]

Both ledgers are short, and one of them is empty. Off-circuit there is nothing at all: no hint, no extra witness---like the presence check, the prover supplies the cycle and not a value more. In-circuit, the constrained work is linear: $N$ hash invocations for the challenge chain and $2N$ field multiplications for the two products, with no library shuffle and---crucially---no dynamic memory at all. This is the foot of the ladder the section has been descending: the presence check needed read--write RAM, the sort and inverse checks dropped to read-only ROM, and the grand product asks for no prover-chosen memory whatever. Every array index in @fig:flat-grandproduct is a compile-time constant, so the whole check is straight-line, statically-indexed arithmetic---which, we will find in @sec:witness-inversion, is the property that makes it cheap to _run_ even where it is not cheap to count. As with the exact mechanisms, the range check comes for free: a multiset equal to ${0, dots, N-1}$ has all its entries in range by definition.

What sets this mechanism apart is not its gate count, which is comparable to the others, but what it does to the proof's soundness. The first three mechanisms are _exact_: when they pass, the cycle _is_ a permutation, full stop, with the certainty of an algebraic identity. The grand product is _probabilistic_: when it passes, the cycle is a permutation _unless_ the prover was astronomically lucky with the challenge, and the guarantee rests on modeling the hash as a random oracle. We have traded a structural certainty for a computational one. At the flat level this is a pure loss---we pay in soundness flavor and receive nothing, since the public surface is already as small as it can be. The reason to make the trade lies further on, when the cycle is cut into segments and each segment must publish a fingerprint of its share of the partition: there, the grand product's single field element will collapse a per-segment surface that the sort would leave linear, and the trade turns favorable. That argument opens at @sub:choosing and becomes the spine of @chap:hierarchical; @sec:representation takes the first step in the same war on the public surface, committing the matrix down to a single root. For now we have only loaded the gun.

#subsection([The Mechanisms, Measured], label: <sub:mech-measured>)

@fig:perm-mechanisms gathers the five mechanisms in the order we met them, one row apiece, both ledgers spelled out, together with the two structural columns the section has been quietly filling in. Read down the memory column and the story so far is there: the quadratic pairwise check; the presence check on read--write RAM; the sort and inverse refinements stepping down to read-only ROM; the grand product asking for no prover-chosen memory at all and standing apart in the soundness column too, where exact certainty gives way to a probabilistic argument. The target column records the quieter observation, twice marked and not yet used: two of the mechanisms address arrays by node value and so carry their target baked into their own geometry, while the sort takes its target as plain comparison data and the grand product compresses any multiset into a single field element. That column does no work in this subsection; it is the hinge of the next one.

#figure(
table(
  columns: 6,
  align: (left, left, left, left, left, left),
  table.header([*mechanism*], [*in-circuit ledger*], [*off-circuit ledger*], [*memory*], [*target*], [*soundness*]),
  [pairwise], [$N$ range checks, $N(N-1) \/ 2$ pairs], [inverse per pair], [---], [implicit (range check)], [exact],
  [presence], [$N$ range checks, $approx 3N$ RAM ops], [none], [RAM (dynamic)], [implicit (value as address)], [exact],
  [sort], [$N$ comparisons, $approx 2N$ reads], [sort + shuffle map], [ROM (dynamic)], [as data (any array)], [exact],
  [inverse-perm.], [$N$ range checks, $N$ reads], [inverse map (one scan)], [ROM (dynamic)], [implicit (value as address)], [exact],
  [grand product], [$N$ hashes, $2N$ multiplications], [none], [none (static)], [any (one field element)], [probabilistic],
),
caption: [The five permutation mechanisms for Group 1, in order of presentation. The first four are exact; the grand product trades exactness for a probabilistic argument (Schwartz--Zippel over a Fiat--Shamir challenge), and uniquely uses no dynamic memory. Per the convention of this section, the ledger columns are lists, not sums: their items carry different gate prices---a hash invocation weighs far more than a read or a comparison---so bills of different lengths do not rank the mechanisms; @fig:mech-measured does. Read down the memory column for the story of the section; read down the target column for the hinge of @sub:choosing.],
) <fig:perm-mechanisms>

The bills cannot rank the four linear mechanisms; the bench can. The protocol is this section's discipline made physical: four circuits---pairwise, presence, sort, inverse-permutation---identical in Groups 2 and 3 and in every input, differing only in Group 1, compiled and proven over the full-matrix representation at sizes up to $N = 500$ (the pairwise--sort pair, on to $N = 1000$), five runs per point. (The grand product sits this round out deliberately: its measured comparison is staged in @sec:witness-inversion, against the sort, in the committed-matrix representation of @sec:representation#[]---one controlled experiment at a time. Nothing below would change with it present; its distinction, as we said, was never its cost.) The metrics are the set we use throughout the thesis: gate count, witness-generation time, proving time, proof size, peak prover memory.

One implementation note is needed before the numbers can be read fairly, because gate counts are sensitive to it: types. Node indices and positions are unsigned 32-bit integers (#inline[u32]): they range over $0, dots, N-1$, comfortably within $32$ bits for every instance we consider, and keeping them narrow keeps the range checks cheap. Edge costs are #inline[u64]: wide enough that a sum of $N$ edge costs cannot overflow even at our largest $N$. The presence array is #inline[bool], the natural type for a tick sheet and the one that compiles to the lightest RAM cells. The grand product, by contrast, works in the native field type (#inline[Field]): its challenge is a hash output and its products are field elements, quantities that live in $FF$ and have no business being range-constrained to $32$ or $64$ bits. The rule throughout is to use the narrowest type that holds the value, because every surplus bit is a constraint the prover pays for---and to step up to #inline[Field] exactly when the arithmetic is genuinely field arithmetic, as the hash chain and the products are.

@fig:mech-measured holds the headline numbers at $N = 500$; @fig:mech-witness-plot traces the trends across the sweep. Three readings, in order of how much they surprise.

#figure(
table(
  columns: 6,
  align: (left, right, right, right, right, right),
  table.header([*mechanism*], [*gates*], [*vs. sort*], [*witness (s)*], [*vs. sort*], [*prove (s)*]),
  [pairwise], [2 072 578], [+13.3%], [2.76], [+66%], [23.9],
  [presence], [1 827 838], [−0.04%], [1.23], [−26%], [20.9],
  [sort], [1 828 579], [---], [1.67], [---], [21.4],
  [inverse-perm.], [1 825 580], [−0.16%], [1.21], [−27%], [20.9],
),
caption: [The four exact mechanisms head to head at $N = 500$, full-matrix representation, means over five runs. Proof size is $14 656$ bytes for all four; peak prover memory ranges $2.5$--$2.9$ GB. Gate counts are deterministic; times carry run-to-run noise of a few percent.],
) <fig:mech-measured>

The first reading is the one the tallies already promised: the exponent decides, and pairwise retires. Against the sort it starts ahead---at $N = 8$ the sort circuit is marginally _larger_ ($3505$ against $3472$ gates), the linear machinery's fixed overhead not yet repaid by so short a list---but by $N = 104$ it trails by some ten thousand gates and at $N = 1000$ by nearly a million, a gap that grows like $N^2$ because it _is_ the quadratic: the $N(N-1) \/ 2$ pair gadgets, at about two gates apiece, that the linear mechanisms took off the bill. Its witness is worse still, two-thirds slower than the sort's at $N = 500$ and widening, dragged down by the quadratic load of unconstrained inversions on its off-circuit ledger. The lesson is the expected one stated precisely---the asymptotically better mechanism wins, but only once $N$ is large enough to pay off its constant overhead---plus one that is easy to miss: the most instructive number in pairwise's row is how _small_ its penalty looks. Thirteen percent, for a quadratic mechanism, because the representation it sits in is itself quadratic---the $N^2$-entry cost matrix dominates every row of this table, and mechanism differences ride on top as perturbations. The table is quietly answering a question we have not asked yet: of the two questions that closed @sec:proof-anatomy, the second is worth more than the first.

The second reading is the near-tie, and it is the billing convention of this section vindicated. The three linear mechanisms land within $0.16$ percent of one another on gates---a spread of six gates per node between the leanest and the heaviest---though their bills read $approx 2N$, $approx 3N$, and $approx 4N$ items. Had item counts decided, presence would have placed last; measured, its $4N$ operations ride on featherweight boolean cells and land it second, a few hundred gates _under_ the sort, whose reads and comparisons cost more apiece. The items are simply not priced alike, and in this representation all of them together are a thin slice of a circuit the shared cost-matrix machinery dominates. Proving time, proof size, and peak memory follow the gates, as they must: the trio proves within three percent of one another, produces byte-identical proofs, and peaks within five percent on memory. By every meter the verifier or the proving system sees, the three exact mechanisms are interchangeable.

The third reading is the one that breaks the tie, and it is the first appearance of a finding this thesis will keep returning to. Witness-generation time separates the trio cleanly: from $N = 100$ up, inverse-permutation solves twenty-two to thirty-one percent faster than the sort, and presence, after a slower start, converges to the same advantage as $N$ grows---at gate counts that differ by a rounding error. The ranking does not follow the gates; it follows the _other_ numbers on the accounts: the count of prover-chosen reads the witness solver must resolve and the off-circuit work behind the hints. The sort pays $approx 2N$ dynamic reads where the inverse check pays $N$, and pays a quicksort and a search for its hint where the inverse check pays one scan; presence pays no hint at all, and its RAM traffic, for all the gravity of the consistency argument in gates, proves cheap to _solve_. Even the retired pairwise check obeys the rule in its broader form, its witness the slowest of all under a quadratic load of unconstrained inversions that no gate records: _witness time tracks the work the circuit does not see._ Gate count and witness-solving cost, we conclude for the first time and not the last, are different currencies. The finding gets a section of its own (@sec:witness-inversion), where the clean two-point experiment---sort against grand product, everything else fixed---gives it its sharpest form; what the four-way comparison adds is that the effect is _graded_, visible already inside the exact family, scaling with exactly the quantities the gate meter ignores.

So the bench returns a verdict, and it is worth stating honestly before overriding it: if cost decided, we would carry inverse-permutation---fewest gates by a nose, fastest witness, both ledgers the shortest---with presence a whisker behind and the sort third of three. We are about to carry the sort and the grand product. The case is the business of the next subsection, and not a single row of this table is what makes it.

#subsection([Choosing for the Road Ahead], label: <sub:choosing>)

Why not simply take the bench's word? For two reasons, one small and one structural. The small one: a verdict by a nose among near-ties is barely a verdict---the trio's gate spread is a rounding error, and the witness advantage, real as it is, separates mechanisms that agree on everything else. The structural one is the reason this subsection exists: cost was never the right criterion, because this circuit is not the product. It is the _baseline_ of a comparison. The program of this thesis, set out in @sec:research-questions, is to cut this proof into $K$ independent segment proofs and study what the cutting buys and costs; the flat circuit's job, from @chap:hierarchical onward, is to be the control everything is measured against. A mechanism should therefore be chosen the way one packs for a journey: not by weight, but by whether it survives the road.

Start with what cost savings can and cannot buy, because the scalability question makes the point bluntly. Every number in @fig:mech-measured is a constant factor on a circuit that grows with $N$---quadratically in this representation, and still without bound after @sec:representation commits the matrix away. The prover's memory grows with the circuit: at $N = 500$, proving any of the four already peaks between two and a half and three gigabytes. Somewhere up the axis, every flat circuit meets the same wall---an instance too large for one prover to hold---and a permutation mechanism cannot move that wall by more than its share of the circuit, a share we have just measured in fractions of a percent. Choosing the cheapest mechanism is choosing to hit the wall a rounding error later. The only lever that moves the wall itself is to make each _proof_ smaller: cut the cycle into $K$ segments, prove each on its own, and reassemble the guarantee---the program of @chap:hierarchical. The criterion this hands us is not _which mechanism is cheapest here_ but: _which mechanisms survive the cut?_ A second, quieter constraint points the same way: whichever mechanism the decomposed constructions carry, the flat baseline must carry the same one, or every later flat-versus-decomposed comparison would change two variables at once---the same one-variable discipline this section has been practicing, applied to the chapters ahead.

What does the cut change, exactly, for a permutation check? One thing, and we have been marking it for three subsections: the _target_. Every mechanism in this section proves that an array of values matches a target multiset, and at the flat level that target is the friendliest one imaginable---the contiguous range ${0, dots, N-1}$, known when the circuit is compiled, conjured entry by entry from a loop counter, free to name and, for two of our mechanisms, free to use as an address. A segment of a decomposed proof enjoys none of that. It holds an $M$-node leg of the cycle, and the set it must check against is _its own share of the nodes_: an arbitrary $M$-element subset of ${0, dots, N-1}$, different for every instance, known only to the prover. And it must moreover _publish_ a fingerprint of that share, because the layer that reassembles the $K$ segment proofs has to verify that the shares are disjoint and exhaust the nodes---why publication is forced, and what it costs in privacy, is the business of @chap:hierarchical; here we need only the fact. The target, in short, stops being implicit and becomes explicit data. Under that one change, the mechanisms of this section meet three different fates.

The presence check does not survive it. Its tick sheet is addressed by node value over the target's domain---the fact we recorded in @sub:presence#[]---and an arbitrary subset offers no domain to address. Concretely, a segment has two options, both ruinous. It can keep a sheet over the full global domain, one cell per node in ${0, dots, N-1}$: but then every segment pays for an $N$-cell RAM---the initialization alone is $N$ writes---and its cost ceases to shrink with $M$, which forfeits the very thing decomposition is for; $K$ provers each doing work proportional to $N$ is the flat proof multiplied, not divided. Or it can try a dense $M$-cell sheet over its own subset: but addressing that sheet means mapping each node value to its slot in an arbitrary set, the map must come from the prover as a hint, and verifying a supplied position map is precisely the shuffle machinery of @sub:sort#[]---the tick sheet has collapsed into the sort with extra steps. The clipboard check exists only while values can serve as addresses; explicit targets revoke the privilege.

Inverse-permutation survives---but not as itself. Nothing stops a segment from supplying an inverse map against its published share: the share arrives as a sorted array (strictly increasing, which buys its distinctness for $M-1$ comparisons), and the map claims each published value's position in the segment's leg. But look at what happened to the ledger. The value-as-address fusion is dead---the published array, not the loop counter, now names the targets---and that published artifact is the _sorted node set_: the very object the sort-based segment publishes, the same size, the same disclosure, the same read-only memory underneath. The check arrives at the segment level as the sort's _twin_, distinguishable only by its halved count of dynamic reads. That residue is real---the law of @sec:witness-inversion does not stop holding, and nothing about the constructions ahead removes the reads---but it is a constant-factor edge on a mechanism otherwise identical to one we already hold: a midpoint on a line whose endpoints, the sort's $approx 2N$ reads and the grand product's none, we are about to carry anyway. A midpoint settles no question the endpoints leave open.

The sort survives unchanged, and that is its entire case. "Organize and inspect" never asked who the target was: check (d) compares the organized array against a list of expected values, and whether that list is spun from a loop counter or read from a published input changes the comparison's right-hand side and nothing else. One mechanism, one form, any target. The uniformity pays a second time at the recombining layer: the statement to check there is that $K$ published shares, each already sorted, together tile ${0, dots, N-1}$---and that statement _is_ a sort, of the concatenated shares against the identity. The mechanism reproduces itself one level up; the global check is the local check at scale.

And the grand product is what the cut was waiting for. Its fingerprint of a multiset is a single field element whatever the multiset---and, decisively, multiset union becomes _multiplication_ of fingerprints. Let each segment publish the product taken over its own share, $P_i$, the product of $(X + v)$ over its nodes $v$; the recombining layer then checks $P_1 dot P_2 dot dots.c dot P_K = product_(v=0)^(N-1) (X + v)$---$K$ field multiplications against the one target that is free at every level, the global identity. No segment ever writes down its share; no layer ever re-organizes $N$ values; the local work _aggregates_ instead of being redone, because products of products are products---whereas sorted lists do not concatenate into sorted lists, and the sort's recombiner must take up all $N$ values again, serially. The per-segment public surface falls from the sort's (and the twin's) $M$-element array to one element. Two honesty notes, both with bills attached elsewhere: making $K$ segments agree soundly on the single challenge $X$ is a genuine construction, built in @chap:hierarchical, not a free generalization of @fig:flat-grandproduct; and a published $P_i$, small as it is, is not thereby _private_---what it leaks, and what it costs to close the leak, are questions for the same chapter. We are choosing a mechanism here, not yet certifying its privacy. At the flat level, we said, the grand product's benefit is exactly zero; this is the benefit, named at last, and the soundness flavor of @sub:grand-product remains its standing price.

So the choice writes itself, and for the first time in the section it is not close. We carry the _sort_: the canonical exact mechanism, standard-library-backed, the one member of its family whose form is indifferent to its target and therefore identical at every level we will build. And we carry the _grand product_: the sole probabilistic mechanism, no extra witness, no dynamic memory, and the only fingerprint that stays a single field element as the construction grows. For the record, because honesty about near-misses is cheap: inverse-permutation could follow the road as the sort's twin, and carrying it instead would change no claim ahead---a somewhat faster witness on the same surface, the same soundness, the same side of every divide this thesis draws; what it would not do is stake out any position the sort and the grand product do not already hold between them. As for the bills and the bench that occupied most of this section: they did not make the choice, and that was the point of making them. They are what lets us _read_ everything that follows. We now know what a RAM cell, a prover-chosen read, a hash invocation actually cost---in gates and in solving time, on which ledger---so when a later chapter changes one variable and the meters move, we will know which item did it. The costs were the anatomy lesson; the road ahead made the choice.

The two survivors are worth holding side by side as the section closes, because the contrast between them is the sharpest the thesis can draw and it recurs at every turn. They sit on opposite sides of nearly every axis: the sort is exact, the grand product probabilistic; the sort leans on dynamic, prover-chosen reads, the grand product is pure straight-line arithmetic; the sort's published artifact, when publishing begins, will be a node set, the grand product's a single field element. And---the twist the measurements have already hinted at---the one that looks cheaper on paper will turn out not to be the one that is cheaper to run. That inversion is a result in its own right, and we give it its own treatment, with the controlled experiment it deserves, in @sec:witness-inversion. First, though, we turn to the second of the two questions left open at the end of @sec:proof-anatomy: the cost matrix, all $N^2$ entries of it, still sitting in the public inputs.
