#import "/theme/headings.typ": *

#chapter([Related Work], label: <chap:related-work>)

The previous chapter assembled the tools this thesis builds on: zero-knowledge proofs and the three properties they must have, the SNARK that makes a proof short and non-interactive, the hash and commitment primitives the circuits call on, and the Travelling Salesman Problem itself. Those are foundations, settled and shared. This chapter turns from foundations to current research. Its task is to place the constructions of the coming chapters on the map of what others have built, and to say plainly what is new.

We first fix the lens through which everything else is read: what this thesis is, what it is not, and the one gap it fills. We then survey the research it touches, grouped by the question each line of work answers. The first group splits a proof across machines, for speed or for memory; the second puts the pieces back together, through recursion, folding, aggregation, or commitment; the third does both at once, in the production zero-knowledge virtual machines that already ship. A fourth group is the application itself: zero-knowledge over graphs, and private routing. We close by drawing the gap as a table and naming the column that is empty everywhere but here.

#section([The Comparison Lens], label: <sec:lens>)

Before comparing, we have to say what kind of object this thesis is, because that decides what counts as a fair comparison. It is not a record-setting prover. We do not compete on raw proving throughput, and against the systems below we would lose. What this thesis offers is a _structural_ account of one move---decomposing a single hard proof into pieces and binding them back together---instantiated on a concrete NP statement where the decomposition is a graph partition that carries its own privacy meaning.

That account rests on three named findings, each developed in full later and previewed here only enough to position the work. The first is _the dualism_: decomposing a zero-knowledge proof buys no algorithmic speedup in the proving itself, only parallelism and lower memory per machine (@sec:dualism). The second is _the stitching tax_: recombining independently produced sub-proofs into one sound, private statement is a single cost felt along three angles at once: what the seam leaks, what the verifier must check, and the bookkeeping carried outside the proofs (@sec:stitching-tax). The third is _the frontier_: at a fixed level of privacy, the architectures form a pick-two triangle, where parallelism, a constant-cost verifier, and low prover overhead cannot all be had together (@sec:frontier). On top of these sits the dimension that organizes this whole chapter: the privacy of the partition, treated as a first-class axis and measured, not assumed.

The substrate is a tool, not a comparison point. The constructions are written in Noir, compiled to an arithmetic circuit, and proved with Barretenberg's UltraHonk backend. That backend supplies succinctness, the zero-knowledge property, and knowledge soundness uniformly, on its own assumptions, identically for every variant we build; it is therefore never what distinguishes one of our constructions from another (@sec:two-layers). What distinguishes them is the circuit and the split between public and private inputs. The systems surveyed below use different backends and chase different goals, and we engage them at the level of architecture and privacy, never as a throughput contest.

This fixes the lens, and with it the chapter's claim in one sentence. Across the state of the art, decomposition is treated as a performance technique and recombination as engineering. No line of work isolates recombination as a structural cost with a privacy face, and none makes the privacy of the partition a measured dimension on a concrete combinatorial statement. That is the gap this thesis fills.

#section([Decomposing the Proof: Distributed and Collaborative Proving], label: <sec:distributed>)

The most direct neighbors are the systems that split a proof across many machines. They share our starting move---one large proof becomes several smaller ones---and they motivate it exactly as we do in @sec:dualism: a single prover is bound by the memory of a single machine, and splitting the work relieves that bound. Two different things can be split, though, and they must be kept apart, because only one of them is what we do.

#subsection([Splitting the Circuit Across Workers], label: <sub:split-circuit>)

The first line splits the computation itself. DIZK was the first to do it, partitioning proof generation across a compute cluster to reach statements about a hundred times larger than a single machine could handle @wu2018dizk. Its cost is communication between workers that grows with the problem, an artifact of the interleaved polynomial arithmetic, and much of the later work targets exactly that cost. deVirgo, the distributed prover inside the zkBridge cross-chain system, data-parallelizes a different proof system but still routes work through a primary node and still pays linear inter-worker communication @xie2022zkbridge. Pianist removes that communication bottleneck by encoding the witness as a bivariate polynomial, so each worker runs its arithmetic on local data alone @liu2024pianist. Hekaton decomposes an arbitrary computation, proves the chunks in parallel, and aggregates the chunk proofs into one, with communication that stays constant in the size of the computation @rosenberg2024hekaton. Soloist pushes the efficiency further, reporting constant proof size with sharply lower communication than its predecessors @li2025soloist, and Cirrus adds _accountability_, the ability to single out a worker that cheated, in the same distributed setting @wang2024cirrus.

These systems are the engineered, performance-tuned form of decompose-and-recombine. Their aggregation step is the counterpart of the recombiner this thesis studies, and their constant-communication results are precisely the optimizations we do not pursue: our recombiner is deliberately simple, because the object of study is its _structural_ cost and its privacy, not its throughput. One result among them speaks straight to our memory dimension from the other direction. Rather than spread a large proof across machines, recent work proves long executions in small space on a single machine, streaming the computation to keep the memory footprint low @nair2025smallspace. That is the same goal our per-machine memory reduction reaches---low memory per prover---arrived at by a different route, and a clean point of contrast for @chap:results.

#subsection([Splitting the Witness Across Provers], label: <sub:split-witness>)

The second line splits the _witness_, not the circuit, and this is the distinction that must not be blurred. In collaborative proving, several mutually distrustful parties each hold a share of the secret and together produce one proof, with no party learning the others' shares. The original construction lifts a conventional SNARK into a secure computation among the provers and reports runtime close to a single prover when most parties are honest @ozdemir2022collaborative; later work distributes the proving fully and adds security against malicious parties @liu2024scalablecozk.

The privacy here is real, but it points the other way. Collaborative proving hides each prover's share _from the other provers_. This thesis hides the structure of the partition _from the verifier_. The two are orthogonal, and we name the difference now so that "collaborative" is not mistaken for the segment decomposition of @chap:hierarchical: there, one prover holds the whole route and chooses how to cut it, and the question is what that cut reveals to whoever checks the proof.

#section([Putting the Pieces Back Together], label: <sec:recombination>)

Decomposition raises a question the moment it is made: how do you bind independent pieces into one statement that is still sound, and ideally still private? That question is the stitching tax, and the literature answers it in several ways. We sort the answers by _where_ the binding is enforced: inside a circuit, outside the proofs, or in a commitment, with one abstract framework standing over all three. The same sorting orders the constructions of this thesis, which bind outside the proofs, in a commitment, and inside a circuit by turns; the cheaper in-circuit route, folding, is the one we leave for future work.

#subsection([The Binding Formalism], label: <sub:pcd>)

The abstract object behind all of this is _proof-carrying data_, introduced by Chiesa and Tromer: a way to compose proofs across a distributed computation so that each node's proof attests to the entire history that produced it @chiesa2010pcd. Later work showed that proof-carrying data can be built from primitives weaker than full succinct arguments @bunz2021pcd. Proof-carrying data is binding done in-circuit, in its most general form. It gives the precise vocabulary for the stitching tax: our recursion variant (@sec:recursion) is a concrete, single-statement instance of it, and our external cross-checks are the cheaper, leakier approximation that recursion replaces. The stitching tax, in these terms, is the cost of approximating proof-carrying data from outside.

#subsection([Recursion and Folding], label: <sub:folding>)

The practical question is how cheap the in-circuit binding can be made. Halo opened this line by deferring the most expensive part of each verification into an accumulator carried along a recursion chain, achieving recursion without a trusted setup and without a full verification at every step @bowe2019halo. Folding schemes took the idea further. Instead of verifying each step's proof inside the next circuit, they _fold_ two instances into one and check a single instance at the end, so the per-step overhead becomes small. This is the modern route to _incrementally verifiable computation_ (IVC), where a long chain of steps is proved with per-step work that does not grow with the chain. Nova set the template @kothapalli2022nova, and a family followed it: non-uniform steps @kothapalli2022supernova, more general constraint systems @kothapalli2023hypernova, accumulation for any special-sound protocol @bunz2023protostar, folding several instances at once @eagen2023protogalaxy, and handling the curve cycle that recursion needs @kothapalli2023cyclefold.

This family marks the one corner of our frontier that none of the architectures built here reaches (@sec:frontier). The recursion variant of this thesis pays a full in-circuit verification for every segment it binds, which is the dominant cost of that construction (@sec:recursion); folding is the principled way to avoid paying it. That makes our recursion cost a _characterized price_ rather than a dead end, and it makes folding the natural future direction (@sec:future-work). The work that comes closest to ours is Mangrove, a folding framework with a uniformizing compiler, a low-memory parallel prover, and a commit-and-fold step @nguyen2024mangrove. Its commit-and-fold echoes our committed constructions, and its low-memory folding is the performance realization of the corner we leave open. We engage it directly and concede the overlap: Mangrove is the performance embodiment of folding, while this thesis contributes the structural map, the privacy ladder, and the application to a concrete NP statement, not a competing folding scheme.

#subsection([External Aggregation], label: <sub:aggregation>)

A different answer binds the pieces without putting them in a circuit at all. SnarkPack aggregates many independent proofs into one with logarithmic verifier cost, reusing existing public parameters @gailly2022snarkpack; related schemes aggregate proofs of a particular system @ambrona2022aplonk or fold them with the techniques of the previous subsection @liu2023snarkfold. Aggregation is worth a careful word, because the stitching-tax framing yields a sharp observation about it. Aggregation attacks exactly _one_ of the three angles of the tax: it reduces the verifier's burden, taking the cost of checking $K$ pieces down toward the cost of checking one. It does nothing about the other two. The partition is still disclosed, and the bookkeeping outside the proofs remains. Aggregation is therefore not a full cure for the stitching tax, only relief on one face of it, whereas recursion and folding dissolve all three angles together. This is the lens earning its keep: a construction that looks like a competitor turns out to address a strict sub-part of the problem, and the framing is what makes that visible. Our own recursion variant takes the same verifier-cost angle to zero, by moving the $K$ checks inside one circuit so the verifier sees a single proof; the price it pays for that is weighed in @sub:aggregation-tax.

#subsection([Commit-and-Prove], label: <sub:cp-snark>)

The last place to put the binding is in a commitment. Commit-and-prove SNARKs commit to data once and then compose separate proofs that operate on the committed values, linked through the commitment rather than re-proving the data each time. LegoSNARK gives the general framework and a toolbox for this style @campanelli2019legosnark. Our committed constructions (@sec:committed) are a concrete commit-and-prove design: each segment exposes one blinded commitment, and the recombiner proves a relation over the openings. We cite LegoSNARK as the general pattern, and note what is specific to us: the commitment is not a convenience for modularity but the mechanism that closes the partition leak, which is why it sits on the privacy ladder of @sub:privacy-ladder.

#section([The Same Spectrum in Production: zkVM Continuations], label: <sec:zkvm>)

The most direct operational analog of this thesis is not a paper but a product category. Zero-knowledge virtual machines prove that a program ran correctly, and to handle long executions they split the execution trace into segments, prove each segment, and then bind the segment proofs back together. That is the flat-to-segment-to-recombine spectrum this thesis maps, running in deployed systems on generic computation.

The split between two of these systems mirrors our own central comparison. RISC Zero proves each segment and then _recursively aggregates_ the segment proofs into one constant-size proof @risczero_continuations; this is our recursion variant, the same architecture applied to virtual-machine execution rather than to a combinatorial statement. Other systems run the continuation but stop short of the recursive step, emitting one proof per segment for an external verifier to check @sp1. That is our hierarchical variant: external binding, $K$ independent proofs, and a verifier cost that grows with $K$. The pair of systems, with and without the recursive step, is our hierarchical-versus-recursion comparison made concrete in production. A third system states the underlying tension in plain words: more segments give a faster prover through parallelism but a larger proof until the recursive step folds them back @jolt. That sentence is our pick-two triangle, observed independently and from the outside.

What none of these systems do is treat the segmentation as carrying information. They cut a generic trace by time, and the cut means nothing in particular. This thesis cuts a _graph_, where the partition is a meaningful object---which nodes share a segment---and where revealing it can leak the very structure the proof is meant to hide. That is why the privacy of the partition is a real axis here and a non-question there.

#section([Zero-Knowledge for Graphs and Private Routing], label: <sec:zk-graphs>)

The application sits at the meeting of two older lines: zero-knowledge for graph problems, and privacy-preserving routing. The theoretical root is foundational and needs only a sentence. Goldreich, Micali, and Wigderson established that every statement in NP has a zero-knowledge proof, building the result on the NP-complete problem of graph three-coloring @goldreich1991. Blum gave the protocol for the specific statement this thesis instantiates, knowledge of a Hamiltonian cycle in a graph @blum1986. This thesis proves a close relative of it---a Hamiltonian cycle held to a cost bound---but as a single succinct, non-interactive artifact rather than a conversation, and it asks what decomposing that artifact costs.

The closest application sibling is ZKGraph, which compiles graph operations such as neighborhood expansion and shortest-path queries into composable circuits and proves graph queries privately and verifiably @wu2025zkgraph. The shape is familiar---compose circuits over a graph, keep privacy and verifiability---but the statement is different. ZKGraph answers queries; this thesis proves knowledge of a constrained Hamiltonian cycle under a cost bound, and studies the cost of decomposing that proof. The statement itself appears to be open ground: proving a feasible tour under a budget as a succinct zero-knowledge artifact does not, as far as we have found, appear in the literature. The Travelling Salesman Problem shows up in the zero-knowledge world mostly as a textbook example of an NP problem, not as a statement someone sets out to prove succinctly and in private.

A second line keeps the route private but changes the model entirely. Privacy-preserving shortest-path computation hides the query and the map from a server using cryptographic structures @wu2016shortestpath, and privacy-preserving cross-domain routing optimizes policy-compliant paths across administrative domains without revealing each domain's topology, through secure computation @chen2015pycro. Closer to optimization than to lookup, distributed constraint optimization has been combined with cryptography to coordinate logistics, assigning customers to carriers on vehicle-routing benchmarks while each party keeps its own constraints hidden @leaute2011logistics. These protect a route from a service, or between competitors, but they do not produce a single succinct artifact that any verifier can check. Our setting is verifiable _and_ private from the verifier, in one proof. A different trust model reaches a similar end without cryptography: a trusted execution environment runs the computation inside an attested hardware enclave, so the verifier trusts the processor rather than a proof #cite(<schuster2015vc3>)---we take the cryptographic route precisely to keep that hardware out of the trust base. That all of these systems exist is evidence that route privacy is a real and studied need, which motivates the application in @sub:formulation.

One nearby body of work deserves to be set apart, because it shares the words _privacy_ and _graph_ but means something else by them. A long line studies the privacy of _published graph data_: anonymizing a social network so its members cannot be re-identified, and the re-identification attacks that show how leaky such anonymization is @narayanan2009. That work hides who connects to whom in a released dataset. This thesis releases no dataset. The graph is the prover's secret, and the question is what the _decomposition of the proof_ discloses to a verifier who never sees the graph at all. The object of privacy is different---a proof's internal structure rather than a published dataset---and so are the means. We make the point because the contribution of this chapter lives exactly in that difference.

One contrast is with the whole approach rather than a single system. There is an alternative route to zero-knowledge for NP that avoids a universal SNARK: simulate a secure multiparty computation "in the head," or build on related correlations, to get a cheap prover at the price of larger, sometimes interactive proofs @ishai2007 @ames2017ligero. These constructions sidestep the decomposition-and-recombination question entirely, because they are not succinct and not recursively composed. Positioning against them clarifies why this thesis lives in the succinct-SNARK regime in the first place: it is exactly that regime, where a proof is small and composable, that makes the stitching tax arise and worth studying.

#section([The Gap], label: <sec:the-gap>)

The survey can be read down a single column. @tab:related-gap lays the families side by side against the questions this thesis asks of them: what they decompose, how they recombine, and whether the privacy of the partition is analyzed at all.

#figure(
  table(
    columns: (auto, auto, auto, auto),
    align: (left, left, left, left),
    stroke: none,
    table.hline(),
    table.header(
      [*Work / family*], [*Decomposes*], [*Recombination*], [*Privacy of partition*],
    ),
    table.hline(),
    [DIZK, Pianist, Hekaton, Soloist, Cirrus], [circuit across workers], [engineered comm. / aggregation], [not analyzed],
    [Collaborative zk-SNARKs], [witness across provers], [secure computation], [between provers, not verifier],
    [Proof-carrying data], [abstract], [in-circuit (formal)], [not applicable],
    [Nova family, Mangrove], [step / iteration], [folding (in-circuit, cheap)], [not analyzed],
    [SnarkPack, aPlonK, SnarkFold], [---], [external aggregation], [not analyzed],
    [LegoSNARK / CP-SNARKs], [---], [commit-then-link], [commitment hiding],
    [RISC Zero, SP1, Jolt], [execution by time], [recursion or none], [not analyzed],
    [ZKGraph, private routing], [query / graph], [composition / secure comp.], [different model],
    table.hline(),
    [*This thesis*], [*graph partition*], [*flat / external / in-circuit / folding (future)*], [*measured ladder*],
    table.hline(),
  ),
  caption: [Related work along the axes of this thesis. The rightmost column is empty for every line but the last.],
) <tab:related-gap>

The empty column is the contribution. Decomposition is everywhere, for scale, for memory, or for unbounded computation. Recombination is well studied, through folding, aggregation, and proof-carrying data. But no line treats the privacy of the decomposition structure as a first-class, measured dimension on a concrete combinatorial statement. The nearest exception is the commit-and-prove row, where a commitment's hiding does protect the values inside each piece; but that hides the piece's _contents_, not the partition---where the cut was made---and it is offered as a building block, not measured as a privacy axis. The column stays empty in the sense that matters. That, together with the dualism and the stitching-tax framing that organize every row above into one frontier, is what this thesis adds.

A second, smaller difference is in how the comparison is run. General benchmarking efforts for zero-knowledge systems measure libraries, circuits, and whole proving stacks for throughput @ernstberger2024zkbench; the systems above are compared the same way. This thesis measures under a discipline built instead for the question it asks. Comparisons are made only within a fixed privacy level, never across one. Each comparison changes exactly one thing, and the change that would alter two at once is named and forbidden---the forbidden diagonal. And both totals are reported: the total work, which decomposition conserves, and the parallel wall-clock, which is where the win actually appears. That discipline also forces an honest look at the metrics themselves, including one count that tracks the proving cost far less well than it appears to, which we examine in @chap:results.

With the map drawn and the gap named, the rest of the thesis fills it. @chap:methodology builds the monolithic baseline the decomposed constructions answer to. @chap:hierarchical develops the framework---the dualism, the stitching tax, the frontier---and walks down the privacy ladder one construction at a time. @chap:results measures them, and @chap:conclusions returns to the frontier to ask which corner is worth building next.
