#import "/theme/headings.typ": chapter, section, subsection
#import "/theme/colors.typ": colors
#import "/theme/utils.typ": inline, lc, fn, ccal
#import "/thesis/chapters/_pseudocode.typ": *

#chapter([Introduction], label: <chap:introduction>)

This chapter introduces the idea of a zero-knowledge proof: what it is, why it matters, and how it carries us from a puzzle to a real-world problem. We state that problem precisely, explain the origin of this thesis and the research questions it raised, and finally summarize the contributions and outline the remaining chapters.

#section([Motivation], label: <sec:motivation>)

Alice has just solved a very hard Sudoku that Bob gave her. She tells him, but he is skeptical and wants proof. The obvious way to settle this is for Alice to show him the completed grid: Bob can quickly check it and be convinced that Alice is telling the truth. However, this resolves things entirely in Bob's favor. By handing over the completed grid, Alice has given away the solution to the puzzle. It is the only thing that was hard to come by, and Bob has obtained it for free. This leaves us with a natural question: can Alice convince Bob that she knows the solution, without giving it to him?

Phrased that way, the question sounds like a contradiction. A proof is something you show. And at first glance, to prove that you know a secret seems to mean revealing it. A _zero-knowledge proof_ @goldwasser1989 dissolves the contradiction: it lets Alice convince Bob that a statement is true without revealing anything more.

The asymmetry of Sudoku---that a solution is trivial to check but hard to find---makes the puzzle an ideal setting for a zero-knowledge proof. The solution is valuable precisely because it is hard to produce, and being able to prove knowledge of it, without giving it up, is something worth having.

But how could such a proof work? We have established that if Alice reveals the completed grid, she reveals everything. If she does not reveal it, Bob has no reason to trust her. The way out is to turn the proof into a conversation @gradwohl2009. First, Alice locks in her completed grid without showing it. We call this step a _commitment_. After that, Bob chooses a random row, column, or block, and asks her to reveal it to prove it contains each digit exactly once. We call this a _challenge_. An honest Alice can always provide a _response_ that is consistent with her commitment.
A cheating Alice cannot. Because she must commit to the grid before knowing Bob's challenge, she cannot adapt her response after the fact. She can only prepare for some of the challenges, and she is caught if Bob chooses one she did not prepare for.

A single round of this protocol---commitment, challenge, response---still leaves room for a lucky guess. A cheating Alice can escape detection if Bob's challenge happens to be one that she prepared for. To mitigate this, the protocol is repeated, round after round, until the probability of her guessing every challenge correctly is as small as Bob wants. 

This repetition introduces a new problem: if Bob inspects enough pieces of the same completed grid across rounds, he will eventually reconstruct all of it. To prevent this, Alice scrambles the completed grid before each round by relabeling the digits: every 1 might become a 6, every 6 a 9, and so on, consistently across the whole grid, using a mapping only she knows. She then commits to this scrambled grid instead of the original one. A valid Sudoku stays valid under any such relabeling, so Bob's checks still pass. But because the digits he sees at each round are the result of a fresh random relabeling, the pieces he collects never add up to the real solution. 

This scrambling raises one last problem: if Bob only ever sees relabeled rows, columns, and blocks, Alice does not actually need to solve _his_ specific puzzle. She could take _any_ entirely unrelated, pre-solved Sudoku, apply a random mapping for each round, and pass every check, without Bob ever knowing she is cheating. To avoid this, we give Bob one additional choice for his challenge at each round: he can ask Alice to reveal her secret mapping for the round, together with the scrambled values in the cells corresponding to the puzzle's original starting clues. Because the clues of the original puzzle are public knowledge, Bob already knows their true values. He applies her mapping to these known clues, verifies that the resulting values match what Alice revealed, and checks that those same values are also consistent with her commitment. This additional challenge is what ties Alice to a specific puzzle. Because she must commit before she knows the challenge, a cheating Alice is forced to choose in advance: hold a valid solution to the wrong puzzle, and risk the mapping challenge, or hold an invalid solution to the right one, and risk a challenge on one row, column, or block she did not prepare for. Either way, a single wrong guess exposes her. 

Ultimately, after enough successful rounds, Bob is convinced Alice holds a valid solution because the probability of her passing every round by chance is practically zero.

This example showcases the original form of a zero-knowledge proof: an _interactive protocol_ @goldwasser1989 between two parties. Alice played the part of the prover, while Bob that of the verifier. The example also demonstrates the three crucial properties any such proof must have. First, an honest prover always convinces the verifier (_completeness_#h(1pt)). Because Alice knows a valid solution, she can answer any challenge. Second, a cheating prover almost never succeeds (_soundness_#h(1pt)). Because of the repeated rounds, the chances that a cheater slips through every challenge by guessing are extremely low. Finally, the verifier learns nothing beyond the truth of the statement (_zero-knowledge_#h(1pt)). Because of the fresh random relabeling Alice uses before each round, Bob cannot reconstruct the underlying solution. Completeness makes the proof useful, soundness makes it trustworthy, and zero-knowledge makes it private. We formally define these properties in @sec:zk-proofs.

Zero-knowledge proofs are no longer a mathematical curiosity confined to textbooks. They are becoming more and more important across a wide range of applications. Zcash @zerocash, a cryptocurrency launched in 2016, uses them to hide the sender, receiver, and amount of a transaction while allowing the network to verify that no money was fraudulently created. Identity systems apply them to verify attributes like age or citizenship without requiring users to disclose their exact birth date or passport @babel2023. The cryptographic primitives enabling these anonymous credentials were formalized over two decades ago @brands2000, @camenisch2001. These proofs also extend to computation itself. Systems such as RISC Zero @risczero allow a party to prove a program executed correctly without re-running the computation, trusting the entity that ran it, or exposing the underlying private inputs. In each case, the same shift is happening: trust moves away from an institution---a bank, a government office, a server---and onto a mathematical guarantee that anyone can verify.

These applications span domains so diverse that designing a specific protocol for each would be wasteful. We need a _general-purpose_ proof system, one that can be pointed at any statement and treat its specifics as mere input. Generality of this kind is within reach: the commitment-challenge-response pattern of Sudoku can be adapted to many different statements. Generality, then, is not the hard part.

While necessary, generality is not enough. The applications ask for more. The interaction between prover and verifier has a cost. In the Sudoku example, this cost is negligible: asking Bob to sit through as many rounds as it takes is perfectly acceptable. At scale, however, interactivity becomes a severe obstacle. Zcash needs proofs that thousands of anonymous nodes can verify independently; requiring a live exchange with the sender is highly impractical. An identity system needs a proof that can be checked years later by a verifier the prover will never meet; it cannot rely on synchronous communication. Similarly, RISC Zero needs a proof that stays valid long after the computation finishes; it cannot keep the prover on call. Consequently, the proof must be a single object, produced once and verifiable by anyone, at any later time, with no further exchange required. We call such a proof _non-interactive_. And because that one object may be checked by thousands of parties, or vouch for a computation far too large to re-run, it must also be cheap to deal with: small to store and send, and fast to verify, however large the statement behind it. We call such a proof _succinct_.

Proof systems that meet all these demands and that provide zero-knowledge exist. They are called zk-SNARKs @bitansky2012, an acronym for Zero-Knowledge Succinct Non-Interactive ARgument of Knowledge. A zk-SNARK provides all the properties we are looking for, and it is an _argument of knowledge_, meaning that it does not simply prove that a statement is true---it also proves knowledge of some information that makes the statement true. We usually call that information the _witness_.

Generality is the property the acronym leaves out, and the one we already called within reach. That is because it is structural, not a cryptographic guarantee. We saw that the interactive protocol behind Sudoku could be adapted from one statement to another; a zk-SNARK reaches the same generality, but systematically. Instead of re-casting a protocol by hand for each statement, it compiles any program into a single common form: an arithmetic circuit @parno2013pinocchio. Much like an electrical circuit carries current along wires through logic gates, an arithmetic circuit carries numbers along wires through addition and multiplication gates. Each gate acts as a constraint, a rule its input and output numbers must satisfy. The statement fixes the public-input wires. The prover fills in the private-input wires so that every constraint holds, and that private assignment is the witness.

This circuit is where the generality comes from. Any computation ultimately reduces to arithmetic and logic, so any program can be turned into one. The proving machinery then treats the circuit as mere input: it does not care what the circuit computes, only that its constraints hold. The circuit changes from one problem to the next; the machinery around it never does. So any statement a program can check, this one framework can prove.

One word is worth a brief explanation: we said _argument_, not proof~#footnote[While a zk-SNARK is strictly an argument by definition, the difference is purely theoretical. Because all practical implementations of zk-SNARKs provide arguments, the literature often defaults to calling them proofs anyway.]~@brassard1988 . The difference comes down to how much computational power we allow the prover to have, and we formalize the technical details in @sec:snarks. For now, a plain description is enough. We say _proof_ when soundness must hold against any prover, even one with unlimited computational power. We say _argument_ when soundness only needs to hold against a computationally-bounded prover, one restricted to a feasible amount of time and resources and thus the only kind that could actually exist. Against a bounded prover, an argument is sound. Against an unbounded one, it offers no guarantee at all. This relaxation is what makes the whole approach practical: it lets us rely on problems we believe are hard to solve, and build these systems on top of them. By hard, we mean that every known way of solving the problem takes an amount of time that grows so quickly with its size that no realistic amount of computation could finish it. No one has proven these problems are actually hard in this sense, but to this day no bounded prover has ever managed to break one. The soundness of an argument is therefore only as strong as our confidence that the underlying problem really is hard for a computationally-bounded prover.

A specific zk-SNARK is the tool we focus on for the rest of this work. To see it in use, we turn to the Travelling Salesman Problem, a well-known problem in combinatorial optimization @dantzig1954, @applegate2006: given a set of nodes and the cost of moving between each pair, the task is to find the least-cost route that visits every node exactly once and returns to the start.

Our goal is not to find that route, nor to prove that one is optimal. We assume the prover already holds a good route, one whose total cost does not exceed a public threshold. How good the route is depends on how tight that threshold is, but that is not our concern. We assume only that the threshold is tight enough that finding a route under it is not trivial. What we want is to use a zk-SNARK to build a proof that convinces one party that the other holds a valid route under the threshold, without revealing the route or its exact cost. 

This problem shares the same asymmetry that made Sudoku a good fit for zero-knowledge proofs: a solution is easy to check but hard to find. This is what makes a zero-knowledge proof worthwhile here as well. But the true value of such a proof lies in the practical importance of the problem at hand. While Sudoku was simply an example to build intuition, the problem we are considering---proving that a route's cost stays under a threshold, without revealing the route or the exact cost---is relevant across a wide range of real-world settings where compliance conflicts with secrecy.
For example, if a logistics firm bids to deliver perishable goods, it must prove its route stays under a strict spoilage threshold. However, proving this traditionally by revealing the route exposes proprietary optimizations that competitors could easily copy.

#section([Problem Definition], label: <sec:problem-definition>)

The previous section provided two examples showing the practical relevance of the problem at hand, highlighting a conflict between compliance and secrecy. Our work addresses this conflict. But to solve it systematically, we must translate the practical scenarios into a rigorous and general framework. We need to define our problem in mathematical terms, explain the approach we will use to solve it, and identify the computational bottlenecks that establish the need for a scalable architectural solution.

#subsection([Mathematical Formulation], label: <sub:formulation>)

We begin with the setting. Our problem lives on a complete weighted graph. In full generality it is _directed_: between any two distinct nodes run two separate connections, one each way, and each may carry its own cost. We label the nodes by the integers $0$ through $n-1$ and gather them in the set $ccal("V") = {0, dots, n-1}$. The connections we call _arcs_ and gather in the set $ccal("A")$; because the graph is complete, every ordered pair of distinct nodes is an arc, so $ccal("A") = { (i, j) : i, j in ccal("V"), i != j }$. The two together describe an instance as a graph $G = (ccal("V"), ccal("A"))$. The number $n = |ccal("V") #h(1.5pt)|$ is the _size_ of the instance, and it is the quantity nearly every metric in this thesis is measured against.

Each arc carries a cost, and we collect these costs in an $n times n$ _cost matrix_ $C$, whose entry in row $i$ and column $j$ is the cost $c#h(1pt)\(i, j)$ of the arc from node $i$ to node $j$. We take the costs to be nonnegative. In general nothing ties $c#h(1pt)\(i, j)$ to $c#h(1pt)\(j, i)$: the cost out may differ from the cost back. We restrict ourselves to the _symmetric_ case, $c#h(1pt)\(i, j) = c#h(1pt)\(j, i)$ for all $i, j$, because our costs stand for distances, which do not depend on the direction of travel. Under this assumption the two opposite arcs between a pair of nodes carry the same cost and collapse to a single undirected _edge_, and from here on we speak of edges accordingly.

The object the prover holds is a _route_---a Hamiltonian cycle, in graph terms---that visits every node exactly once and returns to where it began. We write it as an ordering of the nodes, $pi = (pi_0, pi_1, dots, pi_(n-1))$, where $pi_k$ is the node visited at step $k$. This sequence has $n$ entries but describes a closed route: after the last node $pi_(n-1)$, the route returns to the first. Rather than writing that return into the sequence, we leave it implicit and recover it through the convention $pi_n = pi_0$. The $n$ entries then already stand for $n$ edges: the consecutive pairs $(pi_k, pi_(k+1))$ for $k = 0, dots, n-1$, the last of them the closing edge from $pi_(n-1)$ back to $pi_0$.

Leaving the return implicit, and keeping the sequence to $n$ entries rather than $n+1$, costs nothing in generality and buys conveniences that @chap:methodology draws on when it fixes the prover's witness. The encoding stays lean. It also stays a _permutation_: with exactly $n$ entries for the $n$ nodes, visiting each one once leaves none repeated and none skipped, so $pi$ is precisely a permutation of $ccal("V")$. Writing the return explicitly would spoil this---the $(n+1)$-entry list would hold $pi_0$ twice, a permutation no longer but a list with a single duplicate, awkward to reason about and to check. This identification of a route with a permutation is more than a notational convenience: it is one of the properties the proof is built to enforce, and we return to it in @chap:methodology. Finally, the convention keeps a neighboring problem within reach: drop $pi_n = pi_0$, and the same description carries over from closed routes to open _paths_, which need not return to where they began.

The route's _cost_ is the sum of the costs of its $n$ edges,
$ "cost"#h(1pt)\(pi) = sum_(k=0)^(n-1) c#h(1pt)\(pi_k, pi_(k+1)) med . $
The problem fixes a public _threshold_ $T$, and we call the route _feasible_ when its cost does not exceed it, $"cost"#h(1pt)\(pi) <= T$. How such routes are found, and how good they can be made, is the subject of @sec:tsp.

We can now state precisely what the prover sets out to prove. The public data is the instance together with the threshold: the cost matrix $C$, which carries the graph and all its edge costs, and the bound $T$. The private data is the route itself, the _witness_ of @sec:motivation: a single permutation $pi$. Gathering the conditions for a valid, under-budget route into a relation,
$ R = { ((C, T), pi) : pi "is a permutation of" ccal("V") "and" "cost"#h(1pt)\(pi) <= T }, $ <eq:relation>
the prover's claim is that it knows a $pi$ for which $((C, T), pi) in R$. A zero-knowledge proof of this claim convinces the verifier that such a route is known while revealing nothing else about it---not the route $pi$, and not its exact cost $"cost"#h(1pt)\(pi)$---only that the prover holds some feasible route.

Two features of this statement shape everything that follows. It asks for _feasibility_, not _optimality_: the prover shows a route under the threshold, never that it is the cheapest one, and the gap between the two is exactly where the optimization story of @sec:tsp enters. And it is a claim of _knowledge_, an argument of knowledge in the sense of @sec:motivation: the verifier comes away convinced not merely that a feasible route exists, but that this prover holds one---the only thing worth proving when finding such a route is itself hard.

#subsection([Computational Bottlenecks], label: <sub:computational-bottleneck>)

A proof system can be measured from two sides. On the verifier's side sit the size of the proof and the time to check it. On the prover's side sits the work of producing the proof in the first place: the time it takes and the memory it consumes. Succinctness, the property that made a zk-SNARK worth choosing back in @sec:motivation, settles the verifier's side outright: the proof stays small and quick to check however large the statement behind it, so proof size and verification time are never where the trouble lies. It is the prover that pays.

Turning the relation @eq:relation into a proof the prover can actually produce is the task of @chap:methodology, but the idea is worth mentioning here. We start from a program that checks a route is valid, and we turn that program into an arithmetic circuit. The size of that circuit, the compile time, the witness-generation time, the proving time, and the memory all of it consumes scale with the instance size $n$. Of these, memory is the unforgiving one. The others only cost time, and time we can wait out. But memory runs out; once a circuit grows too large to fit in memory, no amount of waiting will produce its proof.

When $n$ grows large enough, a monolithic circuit encoding the entire computation becomes infeasible to prove. This scalability ceiling is what necessitates the composite proof constructions we introduce in @chap:hierarchical.


#section([Research Questions], label: <sec:research-questions>)

#section([Contributions], label: <sec:contributions>)

#section([Outline], label: <sec:outline>)
