#import "/theme/headings.typ": chapter, section, subsection
#import "/theme/colors.typ": colors
#import "/theme/utils.typ": inline, lc, fn, ccal
#import "/thesis/chapters/_pseudocode.typ": *

#chapter([Introduction], label: <chap:introduction>)

This chapter introduces the idea of a zero-knowledge proof: what it is, why it matters, and how it carries us from a puzzle to real-world applications. We then explain the problem this thesis sets out to solve and the research questions it raises. Finally, we summarize the contributions and outline the remaining chapters.

#section([Motivation], label: <sec:motivation>)

Alice has just solved a very hard Sudoku that Bob gave her. She tells him, but he is skeptical and wants proof. The obvious way to settle this is for Alice to show him the completed grid: Bob can quickly check it and be convinced that Alice is telling the truth. However, this resolves things entirely in Bob's favor. By handing over the completed grid, Alice has given away the solution to the puzzle. It is the only thing that was hard to come by, and Bob has obtained it for free. This leaves us with a natural question: can Alice convince Bob that she knows the solution, without giving it to him?

Phrased that way, the question sounds like a contradiction. A proof is something you show. And at first glance, to prove that you know a secret seems to mean revealing it. A _zero-knowledge proof_ @goldwasser1989 dissolves the contradiction: it lets Alice convince Bob that a statement is true without revealing anything more.

The asymmetry of Sudoku---that a solution is trivial to check but hard to find---makes the puzzle an ideal setting for a zero-knowledge proof. The solution is valuable precisely because it is hard to produce, and being able to prove knowledge of it, without giving it up, is something worth having.

But how could such a proof work? We have established that if Alice reveals the completed grid, she reveals everything. If she does not reveal it, Bob has no reason to trust her. The way out is to turn the proof into a conversation @gradwohl2009. First, Alice locks in her completed grid without showing it. We call this step a _commitment_. After that, Bob chooses a random row, column, or block, and asks her to reveal it to prove it contains each digit exactly once. We call this a _challenge_. An honest Alice can always provide a _response_ that is consistent with her commitment.
A cheating Alice cannot. Because she must commit to the grid before knowing Bob's challenge, she cannot adapt her response after the fact. She can only prepare for some of the challenges, and she is caught if Bob chooses one she did not prepare for.

A single round of this protocol---commitment, challenge, response---still leaves room for a lucky guess. A cheating Alice can escape detection if Bob's challenge happens to be one that she prepared for. To mitigate this, the protocol is repeated, round after round, until the probability of her guessing every challenge correctly is as small as Bob wants. 

This repetition introduces a new problem: if Bob inspects enough pieces of the same completed grid across rounds, he will eventually reconstruct all of it. To prevent this, Alice scrambles the completed grid before each round by relabeling the digits: every 1 might become a 6, every 6 a 9, and so on, consistently across the whole grid, using a mapping only she knows. She then commits to this scrambled grid instead of the original one. A valid Sudoku stays valid under any such relabeling, so Bob's checks still pass. But because the digits he sees at each round are the result of a fresh random relabeling, the pieces he collects never add up to the real solution. 

This scrambling raises one last problem: if Bob only ever sees relabeled rows, columns, and blocks, Alice does not actually need to solve _his_ specific puzzle. She could take _any_ entirely unrelated, pre-solved Sudoku, apply a random mapping for each round, and pass every check, without Bob ever knowing she is cheating. To avoid this, we give Bob one additional choice for his challenge at each round: he can ask Alice to reveal her secret mapping for the round, together with the scrambled values in the cells corresponding to the puzzle's original starting clues. Because the clues of the original puzzle are public knowledge, Bob already knows their true values. He applies her mapping to these known clues, verifies that the resulting values match what Alice revealed, and checks that those same values are also consistent with her commitment. This additional challenge is what ties Alice to a specific puzzle. Because she must commit before she knows the challenge, a cheating Alice is forced to choose in advance: hold a valid solution to the wrong puzzle, and risk the mapping challenge, or hold an invalid solution to the right one, and risk a challenge on one row, column, or block she did not prepare for. Either way, a single wrong guess exposes her. 

Ultimately, after enough successful rounds, Bob is convinced Alice holds a valid solution because the probability of her passing every round by chance is practically zero.

This example showcases the original form of a zero-knowledge proof: an _interactive protocol_ @goldwasser1989 between two parties. Alice played the part of the prover, while Bob that of the verifier. The example also demonstrates the three crucial properties any such proof must have. First, an honest prover always convinces the verifier (_completeness_#h(1pt)). Because Alice knows a valid solution, she can answer any challenge. Second, a cheating prover almost never succeeds (_soundness_#h(1pt)). Because of the repeated rounds, the chances that a cheater slips through every challenge by guessing are extremely low. Finally, the verifier learns nothing beyond the truth of the statement (_zero-knowledge_#h(1pt)). Because of the fresh random relabeling Alice uses before each round, Bob cannot reconstruct the underlying solution. Completeness makes the proof useful, soundness makes it trustworthy, and zero-knowledge makes it private. We formally define these properties in @sec:zk-proofs.

Zero-knowledge proofs are no longer a mathematical curiosity confined to textbooks. They are becoming more and more important across a wide range of applications. Zcash @zerocash, a cryptocurrency launched in 2016, uses them to hide the sender, receiver, and amount of a transaction while allowing the network to verify that no money was fraudulently created. Identity systems apply them to verify attributes like age or citizenship without requiring users to disclose their exact birth date or passport @babel2023. The cryptographic primitives enabling these anonymous credentials were formalized over two decades ago @brands2000, @camenisch2001. These proofs also extend to computation itself. Systems such as RISC Zero @risczero allow a party to prove a program executed correctly without re-running the computation, trusting the entity that ran it, or exposing the underlying private inputs. In each case, the same shift is happening: trust moves away from an institution---a bank, a government office, a server---and onto a mathematical guarantee that anyone can verify.

These applications span domains so diverse that designing a specific protocol for each would be wasteful. We need a _general-purpose_ proof system, one that can be pointed at any statement and treat its specifics as mere input. Generality of this kind is within reach: the commitment-challenge-response pattern of Sudoku can be adapted to many different statements. Generality, then, is not the hard part.

While necessary, generality is not enough. The applications ask for more. The interaction between prover and verifier has a cost. In the Sudoku example, this cost is negligible: asking Bob to sit through as many rounds as it takes is perfectly acceptable. At scale, however, interactivity becomes a severe obstacle. Zcash needs proofs that thousands of anonymous nodes can verify independently; requiring a live exchange with the sender is highly impractical. An identity system needs a proof that can be checked years later by a verifier the prover will never meet; it cannot rely on synchronous communication. Similarly, RISC Zero needs a proof that stays valid long after the computation finishes; it cannot keep the prover on call. Consequently, the proof must be a single object, produced once and verifiable by anyone, at any later time, with no further exchange required. We call such a proof _non-interactive_. And because that one object may be checked by thousands of parties, or vouch for a computation far too large to re-run, it must also be cheap to deal with: small to store and send, and fast to verify, however large the statement behind it. We call such a proof _succinct_.

Proof systems that meet all these demands and that provide zero-knowledge exist. They are called zk-SNARKs @bitansky2012, an acronym for Zero-Knowledge Succinct Non-Interactive ARgument of Knowledge. A zk-SNARK provides all the properties we are looking for, and it is an _argument of knowledge_, meaning that it does not simply prove that a statement is true---it also proves knowledge of some information that makes the statement true. We usually call that information the _witness_.

Generality is the property the acronym leaves out, and the one we already called within reach. That is because it is structural, not a cryptographic guarantee. We saw that the interactive protocol behind Sudoku could be adapted from one statement to another; a zk-SNARK reaches the same generality, but systematically. Instead of re-casting a protocol by hand for each statement, it compiles any program into a single common form: an arithmetic circuit @parno2013pinocchio. Much like an electrical circuit carries current along wires through logic gates, an arithmetic circuit carries numbers along wires through addition and multiplication gates. Each gate acts as a constraint, a rule its input and output numbers must satisfy. The statement fixes the public-input wires. The prover fills in the private-input wires so that every constraint holds, and that private assignment is the witness.

This circuit is where the generality comes from. Any computation ultimately reduces to arithmetic and logic, so any program can be turned into one. The proving machinery then treats the circuit as mere input: it does not care what the circuit computes, only that its constraints hold. The circuit changes from one problem to the next; the machinery around it never does. So any statement a program can check, this one framework can prove.

One word is worth a brief explanation: we said _argument_, not proof~#footnote[While a zk-SNARK is strictly an argument by definition, the difference is purely theoretical. Because all practical implementations of zk-SNARKs provide arguments, the literature often defaults to calling them proofs anyway.]~@brassard1988. The difference comes down to how much computational power we allow the prover to have, and we formalize the technical details in @sec:snarks. For now, a plain description is enough. We say _proof_ when soundness must hold against any prover, even one with unlimited computational power. We say _argument_ when soundness only needs to hold against a computationally-bounded prover, one restricted to a feasible amount of time and resources and thus the only kind that could actually exist. Against a bounded prover, an argument is sound. Against an unbounded one, it offers no guarantee at all. This relaxation is what makes the whole approach practical: it lets us rely on problems we believe are hard to solve, and build these systems on top of them. By hard, we mean that every known way of solving the problem takes an amount of time that grows so quickly with its size that no realistic amount of computation could finish it. No one has proven these problems are actually hard in this sense, but to this day no bounded prover has ever managed to break one. The soundness of an argument is therefore only as strong as our confidence that the underlying problem really is hard for a computationally-bounded prover.

A specific zk-SNARK is the tool we focus on for the rest of this work. To see it in use, we turn to the Traveling Salesman Problem, a well-known problem in combinatorial optimization @dantzig1954, @applegate2006: given a set of nodes and the cost of moving between each pair, the task is to find the least-cost route that visits every node exactly once and returns to the start.

Our goal is not to find that route, nor to prove that one is optimal. We assume the prover already holds a good route, one whose total cost does not exceed a public threshold. How good the route is depends on how tight that threshold is, but that is not our concern. We assume only that the threshold is tight enough that finding a route under it is not trivial. What we want is to use a zk-SNARK to build a proof that convinces one party that the other holds a route that visits every node exactly once, and whose cost is under the threshold, without revealing the route or its exact cost. 

This problem shares the same asymmetry that made Sudoku a good fit for zero-knowledge proofs: a solution is easy to check but hard to find. This is what makes a zero-knowledge proof worthwhile here as well. But the true value of such a proof lies in the practical importance of the problem at hand. While Sudoku was simply an example to build intuition, the problem we are considering---proving that a route's cost stays under a threshold, without revealing the route or the exact cost---is relevant across a wide range of real-world settings where compliance conflicts with secrecy.

For example, if a logistics firm bids to deliver perishable goods, it must prove its route stays under a strict spoilage threshold to guarantee product freshness and win the contract. However, proving this traditionally by revealing the route exposes the results of proprietary routing optimizations. Competitors could easily copy these optimizations, destroying the firm's competitive advantage in the market.

Similarly, consider a security company operating armored trucks to transport high-value assets between financial institutions. To maintain its insurance coverage and satisfy regulatory mandates, the company must verify to an auditor that its transit runs remain under a strict maximum time limit, minimizing exposure to risk. Under a traditional verification model, the company would have to surrender its complete GPS logs and timetables. Disclosing this operational data creates an immediate security vulnerability, as it reveals the precise paths, timing windows, and stop durations to potential attackers, compromising the safety of future transits.

#section([Problem Definition], label: <sec:problem-definition>)

These examples highlight a practical conflict between compliance and secrecy. Our work addresses this conflict, but to resolve it systematically, we must translate these practical scenarios into a general and rigorous framework.

#subsection([Mathematical Formulation], label: <sub:formulation>)

We begin by defining the setting. Our problem lives on a complete weighted graph with $n$ nodes. The graph is directed#footnote[The directed formulation loses no generality: an undirected graph is just the special case where the two arcs between a pair of nodes share a cost, $c#h(1pt)\(i, j) = c#h(1pt)\(j, i)$. Our implementation in fact uses undirected instances, only because they simplify instance generation; the choice is invisible to the proof system, and keeping the formulation directed lets it accommodate other instance types just as well.]: between each pair of nodes there are two connections, one in each direction, that we call arcs. Each arc has its own cost. We label the nodes using integers, from $0$ to $n-1$, and gather them in the set $ccal("V") = {0, dots, n-1}$. Similarly, all arcs are gathered in the set $ccal("A")$. Because the graph is complete, every ordered pair of distinct nodes is an arc, and we can write $ccal("A") = { (i, j) : i, j in ccal("V"), i != j }$. The nodes and arcs together form the graph $G = (ccal("V"), ccal("A"))$, the structure shared by every instance of size $n$; what sets one instance apart from another is the cost of each arc. The number $n = |ccal("V") #h(1.5pt)|$ is the size of the instance, and it is what nearly every metric in this work is measured against.

The arc costs form a table. We collect them in an $n times n$ cost matrix $C$, and the entry in row $i$ and column $j$ is the nonnegative cost $c#h(1pt)\(i, j)$ of traveling from node $i$ to node $j$.

A _valid_ route (a Hamiltonian cycle, in graph terms) visits every node exactly once and returns to where it began. We write it as an ordering of the nodes, $pi = (pi_0, pi_1, dots, pi_(n-1))$, where $pi_k$ is the node visited at step $k$. The return to the first node, after visiting $pi_(n-1)$, is not included in the sequence but is accounted for when computing the total cost of the route. In other words, the last arc is implicit and we adopt the convention $pi_n = pi_0$. The sequence's $n$ entries therefore stand for $n$ arcs: the consecutive pairs $(pi_k, pi_(k+1))$ for $k = 0, dots, n-1$, where the last of them is the closing arc from $pi_(n-1)$ back to $pi_0$. 

Leaving this arc implicit costs nothing in generality, and it yields a crucial structural advantage. Because a valid route visits each node exactly once, no node is repeated and none is skipped, so the sequence $pi$ mathematically constitutes a permutation of $ccal("V")$. This identification of a valid route with a permutation is more than a notational convenience: it is one of the properties the proof is built to enforce, and we return to it in @chap:methodology.

The cost of such a route is the sum of the costs of its $n$ arcs,
$ "cost"#h(1pt)\(pi) = sum_(k=0)^(n-1) c#h(1pt)\(pi_k, pi_(k+1)) med . $
The problem fixes a public threshold $T$, and we call the route _feasible_ when its cost does not exceed it, $"cost"#h(1pt)\(pi) <= T$. How valid and feasible routes #footnote[We use _valid_ to denote structural correctness (a Hamiltonian cycle) and _feasible_ to denote quantitative compliance (cost bounded by $T$).] are found, and how good they can be made, is the subject of @sec:tsp.

We can now formalize the exact proposition we want to prove. The public data consists of the cost matrix $C$ and the threshold $T$. The private witness is the route $pi$. The conditions for a valid and feasible route are captured by the relation

$ R = { chevron.l (C, T), pi chevron.r : pi "is a permutation of" ccal("V") "and" "cost"#h(1pt)\(pi) <= T }. $ <eq:relation>

The prover claims knowledge of a witness $pi$ for which $chevron.l (C, T), pi chevron.r in R$. A zero-knowledge proof of knowledge for this statement convinces the verifier that a valid and feasible route is known, while revealing nothing else about it.

#subsection([Computational Bottlenecks], label: <sub:computational-bottleneck>)

A proof system can be measured from two sides. On the verifier's side sit the size of the proof and the time to check it. On the prover's side sits the work of producing the proof in the first place: the time it takes and the memory it consumes. Succinctness, one of the properties that made a zk-SNARK worth choosing back in @sec:motivation, settles the verifier's side outright: the proof stays small and quick to check however large the statement behind it, so proof size and verification time are never where the trouble lies. It is the prover that pays.

Translating the relation @eq:relation into an actual proof is the task of @chap:methodology, but the idea is worth mentioning here. We start from a program that checks a route's validity and feasibility, and we turn that program into an arithmetic circuit. The size of this resulting circuit, along with the compile time, witness-generation time, proving time, and memory consumption all scale with the instance size $n$. Of these, memory is the unforgiving one. While extended times on the prover's side severely degrade performance, they do not prevent proof generation. Memory capacity, however, imposes an absolute physical limit. If a circuit grows too large and exhausts the available memory, proof generation fails entirely.

Therefore, as $n$ grows, a monolithic circuit encoding the entire computation to verify a route inevitably becomes infeasible to prove. This scalability limitation is what necessitates the proof constructions we introduce in @chap:hierarchical.

#section([Research Questions], label: <sec:research-questions>)

We have established that a monolithic circuit encoding relation @eq:relation has a fundamental limitation: when the instance size $n$ grows too large, the corresponding circuit no longer fits in memory and no proof can be generated. Therefore, to verify routes over extensive graphs, the underlying proof architecture must change.

Instead of building a single proof, we can distribute the computational load across multiple smaller proofs, and then recombine them back together. We call the result of this approach a _composite_ proof, and it sets the ground for our leading research question. 

#block(above: 1em, below: 1em, stroke: (left: 1pt + colors.primary), inset: (left: 10pt, top: 5pt, bottom: 5pt))[
    #block()[
        #set text(font: "Libertinus Sans", style: "italic", fill: colors.primary)
        Leading Research Question
    ]
    When proving knowledge of a valid, feasible route on a large-scale graph, to what extent can composite zero-knowledge proof architectures overcome the memory limit of a monolithic circuit---and what is the price for that decomposition, in total proving cost, in verification, and in what the proof is forced to reveal?
]

To tackle this question, we divide it into three specific research questions. Each targets a distinct phase of the architectural shift: defining the monolithic baseline, evaluating the composite constructions, and measuring the resulting structural trade-offs. 

#subsection([The Monolithic Baseline], label: <sub:monolithic-rq>)

We cannot fault the monolithic approach without first maximizing its efficiency. A memory ceiling reached through poor implementation reflects flawed engineering, not the structural limits of the architecture. Therefore, the baseline must be a rigorously optimized monolithic circuit. Only then does the resulting bottleneck belong strictly to the architecture rather than to us.

While memory is the absolute bottleneck, identifying the exact instance size $n$ where failure occurs offers limited insight. That specific $n$ depends entirely on available memory and the chosen proof system. Better hardware or a different proof system shifts the failure point, making an isolated value of $n$ useful only for fixed-budget comparisons. To understand the underlying architectural constraints, we must measure the shape of the memory growth. The core issue is therefore not where a specific machine fails, but how the prover's memory scales with $n$.

#block(above: 1em, below: 1em, stroke: (left: 1pt + colors.primary), inset: (left: 10pt, top: 5pt, bottom: 5pt),)[
#block()[
#set text(font: "Libertinus Sans", style: "italic", fill: colors.primary)
Research Question #text(style: "normal")[(1)]
]
How does peak prover memory scale with the instance size $n$ in an optimized monolithic circuit for proving knowledge of valid, feasible routes?
]

We expect memory to scale in a way that makes a hard ceiling inevitable. Quantifying this scaling establishes the reference baseline for comparison, while its shape shows why a transition to composite architectures is necessary.

#subsection([The Composite Constructions], label: <sub:composite-rq>)

Once the optimized monolithic circuit reaches its ceiling, the only way forward is to stop proving the entire route at once. A composite construction cuts a valid, feasible route into $K$ segments, proves each as its own smaller circuit, and then recombines the segment proofs into a single statement about the full route. Because each segment is roughly $n\/K$ in size, each segment proof requires far less memory than the monolithic circuit. This is the promise of the approach.

However, that promise is conditional. It depends entirely on how the segments are recombined, and there are two distinct ways to do so.

First, the verifier can do it externally. In this scenario, the prover generates the $K$ segment proofs alongside an additional proof that validates the joins. The verifier must check all $K+1$ proofs and perform an additional consistency check to ensure these separate pieces belong to the single original instance. This keeps the prover's memory footprint light, but shifts the recombination work to the verifier as overhead---a verifier cost we set aside here and take up in the third research question (@sub:trade-offs-rq).

Second, the prover can do it internally using recursion. This approach introduces a new, overarching outer circuit. The outer circuit takes the segment proofs, verifies them internally, and performs the necessary work to mathematically validate the joins. Only after verifying both the segments and their connections does it emit a single final proof for the verifier to check. However, the outer circuit requires its own memory to prove, introducing a distinct architectural overhead for the prover.

Because of these differing overheads, decomposing the route does not automatically guarantee a strictly lower peak memory. The true memory profile of the architecture depends on the cost of the chosen recombination method.

#block(above: 1em, below: 1em, stroke: (left: 1pt + colors.primary), inset: (left: 10pt, top: 5pt, bottom: 5pt))[
#block()[
#set text(font: "Libertinus Sans", style: "italic", fill: colors.primary)
Research Question #text(style: "normal")[(2)]
]
To what extent can decomposing the proof into segments lower the prover's peak memory below the monolithic baseline, and how does the recombination method shape that outcome?
]

We anticipate that while individual segments will predictably shrink the immediate memory footprint, the architecture's ability to flatten the overall memory scaling curve hinges on the cost of the recombination method. Specifically, we expect external recombination to keep peak prover memory below the monolithic baseline, whereas internal recombination through recursion will reintroduce a memory overhead that escapes this per-segment reduction, since its outer circuit must verify all $K$ segment proofs. That overhead grows with $K$, and can be made constant in $n$ when $K$ is fixed; but because it is a floor set by $K$ while the baseline climbs with $n$, it must be read against the baseline, and for small $n$ or large $K$ it can exceed it.

#subsection([The Structural Trade-offs], label: <sub:trade-offs-rq>)

We changed the architecture for one reason: memory. But the change reaches further than the reason we made it. Cutting a valid, feasible route into segments does not merely redistribute the prover's work---it changes how we deal with the statement we are proving, and that turns out to cost us in places we were not looking. A monolithic circuit inherently enforces the global constraints of our relation, such as ensuring every node is visited exactly once. Isolated segments cannot enforce this; they only prove local validity within their boundaries. To restore global soundness, the architecture must introduce recombination logic, a "#h(-1pt)glue" mechanism to check the joins and guarantee the independent segments form a single, consistent cycle. That logic is the price of the cut, and it does not stay confined to memory: it forces three costs, and accounting for them is the rest of this question.

The first is total proving work: the amount of computation the prover must perform, counted in circuit gates. It is at the core of the broader proving cost, since the time and resources a proof demands grow with the work it has to do. Dividing the problem does not reduce the amount of the route that must be proved; the recombination logic only adds work the monolith never paid. Whether that extra work is bought back anywhere, or simply accumulates, is one of the things the trade-off question must settle.

The second is verification load. A monolithic proof is checked once, in a time independent of $n$. Composite architectures can lose constant-time verification. If the verifier handles the recombination externally, it must check $K$ segment proofs plus the glue proof, causing verification time to grow with the number of segments. If the prover handles it internally via recursion, the verifier regains the single cheap check, but the prover absorbs the computational penalty of the outer circuit. Cheap verification is kept or surrendered depending on where the recombination lives.

The third is privacy, and it asks to be stated with care. The proof system's zero-knowledge property does not weaken: it is identical for every construction in this thesis, because it depends only on the proving backend, which never changes in this work. What decomposition puts at stake is instead the _public surface_: the line between what the statement reveals and what the witness keeps hidden. To see why that line can move, follow what the recombination needs. The glue must verify the global constraints that no single segment can enforce alone: that the segments join end to end into one consistent cycle, and that together they visit every node exactly once. To check the joins, it needs each segment's endpoints, where the segment begins and ends. To check the coverage, it needs to know which nodes each segment covers, in some form: the nodes spelled out one by one, or folded into a single digest that stands in for them. These are the two things the glue must be handed, and how the segments hand them over is the choice that determines to what extent privacy is kept or given away.

That choice runs along a spectrum. At one end, the segments hand the glue what it needs in the clear, and the partition lies open to anyone who reads the proof. At the other, that information is hidden: behind commitments the glue checks against, or absorbed entirely into a recursive proof. In that last case, the recombination logic moves inside the outer circuit, and the shared values reach it only as private witness, so the segments' public surface carries nothing at all. What remains hidden is therefore a property of the public surface, not of the proof system. We call this property _structural privacy_, and it is this that the constructions trade, not the proof system's secrecy.

These three pulls do not point the same way: easing one tends to tighten another. The final research question asks not only how large each cost is, but why the trade-off between them is structural---a property of the problem rather than a gap left for a better engineer to close.

#block(above: 1em, below: 1em, stroke: (left: 1pt + colors.primary), inset: (left: 10pt, top: 5pt, bottom: 5pt))[
#block()[
#set text(font: "Libertinus Sans", style: "italic", fill: colors.primary)
Research Question #text(style: "normal")[(3)]
]
When transitioning from an optimized monolithic proof to a composite one, what is paid in total proving cost, verifier load, and route privacy, and why do these costs form a structural trade-off that no single architecture eliminates?
]

We anticipate that each construction will buy some of these costs back only by paying the others: external recombination keeps the prover's overhead low but makes the verifier check every piece, and hides nothing unless commitments are added; recursion instead restores both the single cheap verification and full structural privacy, but charges the prover for the outer circuit. No single arrangement, we expect, settles all three at once. Which costs each construction pays, and why the trade-off cannot be escaped, is what building and measuring them will show. 

One caution belongs with this question before we answer it. Privacy is not only one of the three costs; it is also the one that makes the other two unreadable unless it is held fixed. A construction that reveals more can afford to do less work, so comparing the cost of two constructions that hide different amounts measures nothing clean: the cheaper one may simply be the one that gave more away. We therefore fix privacy first, and compare proving cost and verification only among constructions that reveal the same. Every cost comparison in this thesis is made at equal privacy, so that a gap which survives is a real difference in cost, and not a privacy difference in disguise. Comparisons across different privacy levels will still be useful, but for a different purpose: to see what a construction pays to reveal less, or saves by revealing more.

Together, these three research questions set the agenda for the rest of the thesis, building toward a comprehensive answer to our leading research question. They follow a single progression: define the memory limit, evaluate the architectural shift, and quantify the trade-offs it forces. Answering them is what turns the promise of composite proofs into something measured.


#section([Contributions], label: <sec:contributions>)

The three research questions have answers, and those answers are the substance of this thesis. They are not three numbers. The constructions we build to reach them---segmented proofs, commitments, proofs verified inside other proofs---are assembled from standard cryptographic parts, and building them is not, by itself, the contribution. The contribution is the account they make possible: a map of what decomposition does to a zero-knowledge proof, what it costs, and why those costs are forced rather than incidental. We state it as three results, each a piece of the answer to the leading question.

#subsection([The Two Faces of Decomposition], label: <sub:contrib-dualism>)

Decomposition is, in most settings, a way to make a hard problem tractable by shrinking the space that has to be searched. The travelling salesman problem is a natural example. Finding a good tour over $n$ cities means choosing among all their orderings, a number that explodes as $n$ grows. A standard way to tame it is to partition the cities into geographic clusters, find a short tour within each cluster, and join the clusters into one route. Each sub-problem now ranges over a handful of cities instead of all of them, so the search shrinks dramatically. In effect, decomposition has added a constraint---optimize within clusters, and then join the locally-optimized paths into a single global route---and that constraint is exactly what prunes the search. The price is paid in quality: the best route that respects the clustering may be worse than the true optimum, which the constraint has placed out of reach. Here decomposition buys tractability with optimality.

Decomposing a zero-knowledge proof of our relation behaves in the opposite way, and collects none of that reward. The prover is not searching for anything: it already holds the route, and proving is checking, not finding, so there is no search space for decomposition to shrink. The statement is also globally constrained---a valid route visits every node exactly once, a property no single piece can enforce on its own. Cutting the proof into segments therefore does not add a constraint; it _loosens_ one. Each segment proves only that its own piece is locally valid, and the global condition the cut discarded must be restored afterward, by a recombination step that checks the pieces fit together into one cycle. That recombination is work a single proof never had to do, and it is enough to cancel the per-segment saving: the first cost we set out to weigh, total proving work, is not reduced but slightly increased. What the cut does buy is narrower---each segment is a smaller circuit, so it proves with less memory, and the segments can be proved in parallel. Decomposition trades not for less work, but for work that can be spread out.

Decomposition thus cuts two ways. In optimization it tightens the problem, trading a worse solution for a smaller search. In a zero-knowledge proof it loosens the problem, trading extra recombination work for smaller, parallel pieces---and because there was never a search to shrink, the cut brings its cost without the saving that, in optimization, would justify it.

#subsection([The Cost of Recombination], label: <sub:contrib-stitching-tax>)

Decomposition distributes the prover's work, but it leaves a debt behind. The global conditions---that the segments join into one cycle, and that together they visit every node exactly once---are exactly the ones no single segment can check, so they must be re-established after the cut, by a recombination step that stitches the segment proofs back together. The cost of that step is the _stitching tax_. 

How much this tax charges turns on two decisions, and the whole family of constructions in this thesis is generated by them. The first is _where_ the stitch is enforced: outside the proofs, by a verifier that checks the segment proofs and a separate glue proof, or inside, by a recursive proof that verifies the segments and performs the recombination within its own circuit. The second is _what_ it is enforced on: the values each segment shares in the clear, the same values hidden behind commitments, or the values absorbed entirely as private witness.

Weigh those costs against what decomposition was for, and a frontier#footnote[We borrow the term from multi-objective optimization, where a _Pareto frontier_ is the set of solutions, none of which can be improved on one objective without being worsened on another. Here the objectives are the three goods that follow, and the solutions are the constructions.] appears, with a simple and fixed shape. Three goods are worth wanting from a composite proof. The first is that it stay _cheap_, costing no more than what decomposition forces. The second is that it run in _parallel_: because the segments are proved independently---no segment's proof depends on another's---the $K$ proofs need not be built one after another on a single machine, but can be spread across many and built at once. The third is that it be _structurally private_, hiding the partition the way an undivided proof does, by keeping it off the public surface rather than guarding it there with an added assumption---a property of the public surface, not of the proof system, whose secrecy is identical for every construction here. A fourth good one might expect---cheap verification---needs no axis of its own: it tracks the same choice as privacy, since an external stitch makes the verifier check every piece and can hide the partition only computationally, while moving the stitch inside restores a single cheap check and structural privacy together.

No construction holds all three. The undivided proof is cheap and structurally private, but cannot be split, and so never runs in parallel. The external, committed stitch is cheap and parallel, but gives up structural privacy, and the cheap verifier with it. Recursion is structurally private and proves its segments in parallel, but feeds them into one final proof that does not split---an aggregation that runs alone, and makes recursion the most expensive to build. Each reaches two of the goods only by surrendering the third. The corner that would hold all three is empty; it marks a direction for future work---folding schemes---rather than a result of this thesis, so we leave it open. The composite constructions we develop have no single winner: their costs do not fall on one axis, so they cannot be ranked on a line, only placed on the frontier they trace.

#subsection([A Controlled Comparison], label: <sub:contrib-methodology>)

A claim about trade-offs is only as good as the comparison behind it, and a loose comparison lets one cost pass for another. The comparisons here follow a discipline. Each changes a single variable. We compare costs only at equal privacy, so that a gap in cost is never secretly a gap in what is revealed; we compare across privacy levels too, but to read what is the cost of hiding more, and never to rank constructions that reveal different amounts. Saying plainly which comparisons are not allowed is as much a part of the method as the comparisons we make.

#section([Outline], label: <sec:outline>)

The remaining chapters follow the path this one has sketched, from the tools the problem needs to the measurements that settle its questions.

@chap:background makes precise what @sec:motivation gave only in intuition. It defines a zero-knowledge proof and the three properties it must have, sets out the zk-SNARK and the arithmetic circuit it compiles to---together with the cost of memory inside a circuit, which will matter throughout---and introduces the hash and commitment primitives the later constructions rely on. It closes by stating the problem and the threat model in full.

@chap:related-work places the thesis among others. It surveys zero-knowledge proofs over graph problems, the recursive and folding proof systems the later constructions draw on and point toward, and the other routes to privacy-preserving optimization, and from these marks out what is new here.

@chap:methodology builds the baseline. From the relation @eq:relation it assembles a single monolithic circuit, weighs the ways to enforce that a route is a permutation, and commits the cost matrix down to a short digest. The result is the flat proof every later construction answers to---and the memory wall that forces us past it.

@chap:hierarchical is the heart of the thesis. It cuts the route into segments, proves each alone, and stitches the pieces back into one statement, developing along the way the framework of the previous section---the dualism, the stitching tax, the frontier---and descending the family of constructions one decision at a time, from the one that gives the partition away to the one that hides it on no assumption at all.

@chap:results puts numbers to all of it: how the prover's memory scales, what decomposition costs in total work and buys in parallel proving, and where each construction falls on the frontier---every comparison held to the discipline of @sub:contrib-methodology.

@chap:conclusions looks back. It asks whether the framework was the right lens, turns the frontier into practical guidance for choosing a construction, says plainly what the work does not show, and points to the folding schemes that would fill the empty corner.
