#import "/theme/headings.typ": chapter, section, subsection
#import "/theme/colors.typ": colors
#import "/theme/utils.typ": inline, lc, fn

#chapter([Conclusions], label: <chap:conclusions>)

This thesis set out to make one trade-off answerable. Not in the abstract, where it is a truism that privacy, cost, and scale pull against each other, but for a concrete #smallcaps[np] statement a prover might actually want to prove in zero knowledge---a route through a graph whose cost stays under a threshold---and with numbers rather than intuition deciding where the lines fall. The arc that answered it is short to recall. A flat baseline fixed the control everything is read against. A dualism and a stitching tax said what cutting that baseline into pieces must cost, and a privacy ladder, walked one construction at a time, said what each cut buys back in secrecy. And a frontier placed the surviving constructions where each pays, three corners with no center, the deployer left to choose which good to forgo. The answer the thesis reached is that picture, and the case for it is the chapters behind this one.

This chapter looks back at the picture rather than adding to it. It asks first whether the framework that drew the frontier was the right instrument to draw it with (@sec:framework-retrospect), then turns the frontier from a diagram into guidance for someone who has to choose a construction, says plainly and in one place what the work does not show, and closes on the construction that would fill the frontier's empty center---the folding schemes the body has pointed toward all along, taken up as future work in @sec:future-work.

#section([The Framework in Retrospect], label: <sec:framework-retrospect>)

The framework came before the measurements. The dualism, the stitching tax, the fingerprint lever, and the pick-two triangle were all claims made from the structure of the constructions, set down in @chap:hierarchical before a single one of them was timed, and a results chapter has now had its say on each. So the honest question to open a conclusion with is not whether the numbers came out well---they did---but whether the frame earned its keep: whether it predicted what the benchmarks found, or merely supplied a vocabulary for narrating them after the fact. The difference shows in falsifiability. A frame that only ever fits is decoration; a frame that forbids things, and is not contradicted, is a lens. Taken one idea at a time, ours mostly forbade.

The dualism was the most exposed of the claims, and so the most informative when it held. It said that decomposition conserves the prover's total work: cut a proof into segments and the gates can only be relocated and taxed, never reduced, so the hierarchical total can never fall below the flat one. A single instance in which it did---one size, one segment count, where splitting bought a cheaper proof---would have broken the claim outright. @sub:dualism-measured found none. The $K$ segments summed back to the flat gate count within a percent at every size, and every total, across every variant and every $K$, sat above the conservation floor. The frame here did more than fit the data; it ruled a thing out, the free lunch from splitting, and the ruling held without exception. That is the cleanest kind of confirmation a structural claim can get.

The stitching tax was specific in a way that gave it room to be wrong. The frame did not merely say there would be a tax; it said how the tax should move---shrinking as the instance grows and the glue's fixed cost dilutes, rising as the segment count grows and there is more to stitch---and it named the one variant that should refuse to dilute, committed-sort, whose $O(n)$ commitment re-fold rides at a fixed fraction of the circuit rather than thinning against it. All three predictions held to the percent. The tax fell from several percent at small sizes toward a single percent at large ones, rose with $K$ at every size, and committed-sort alone stayed pinned at seven to seventeen percent, heaviest and undiluting, exactly the asymmetry @chap:hierarchical had drawn between the two committed variants from their shapes alone. A frame precise enough to be falsified on three counts, falsified on none, is doing real work.

The fingerprint lever the measurement did not merely confirm but sharpened. The frame's careful claim was that swapping the sort mechanism for the grand product changes the glue's coverage cost as a matter of _slope, not class_---the product still touches all $n$ nodes, so its coverage stays $O(n)$, only at a gentler rate per node. There was a tempting overstatement nearby, that the product collapses an $O(n)$ check to a handful of multiplications, and the frame had explicitly warned against it. @sub:lever-measured vindicated the careful reading over the tempting one: both glues came out linear in $n$, the product's slope about seven times gentler than the sort's but a slope all the same, never the flat line a true $O(K)$ coverage would draw. And the same lever is the witness inversion of @sec:witness-inversion surfacing a second time at the recombiner---the arithmetic mechanism solving its witness faster precisely where the gate count says it should be slower. To be right about the thing that was easy to get wrong is the strongest sign a lens is ground correctly.

The pick-two triangle was the frame's headline, and the most striking to see reproduced. It was an architecture-level claim, drawn from the three constructions' shapes before any of them had a wall-clock or a peak-memory figure attached: each holds two of cheap, parallel, and private, and yields the third, so the deployable set is three corners around an empty center. @sec:frontier-figure redrew that triangle from the measured points, and the two drawings agree corner for corner---three non-dominated constructions, no fourth, and the center genuinely empty rather than merely unoccupied. The frontier was not found in the data and then explained; it was argued first and then found, which is as much as an empirical chapter can do to confirm that the shape was real and not imposed.

A frame that only ever confirmed itself would invite suspicion, and ours did not. Two places it strained, and both are worth stating, because both are refinements the measurement forced rather than failures it exposed. The first is inside the triangle's "parallel" corner, which the word flatters. @sec:frontier-figure found recursion's wall-clock sitting _above_ flat's, not below: its segments stay small and clear the memory wall, reaching instances flat cannot touch, but its monolithic outer proof runs alone and dominates the clock, so the good recursion actually holds there is scale and low per-prover memory, not a faster finish. The single axis labeled "parallel" quietly bundles two goods that recursion and the hierarchical constructions hold in different measure, and only the two-clock discipline of @sub:control-both-clocks kept the bundle from misleading. The second is a caution about how to read the mechanism choice. The frame insisted, back in @sec:witness-inversion, that the choice between sort and product would _not_ be settled by their costs, which run to a near-tie, but by what each becomes under decomposition; @sec:two-by-two bore that abstention out, finding the mechanism a small row against an aggregation column that dwarfs it. The vivid witness inversion, real as it is, is a secondary mark on the product's account and not the reason it earns its place---the reason is the $O(1)$ surface decomposition exposes. Even where the frame declined to let the numbers decide, the numbers declined too.

On balance, then, the lens was the right one---not because it flattered the constructions but because it made claims the benchmarks could have broken and largely did not, and because where it bent it bent into a sharper statement rather than a wrong one. The dualism it got exactly right, the stitching tax in all three of its particulars, the lever it understated and the measurement corrected upward, the triangle it predicted whole. What the frame cannot do is choose, for a deployer standing in front of the three corners it correctly drew, which corner is theirs. That is a separate task from drawing the frontier, and turning the frontier into a decision is where this chapter turns next.