#import "/theme/headings.typ": *

#chapter([Background], label: <chap:background>)

Chapter 1 told the story of the problem and named the tool that addresses it. A zero-knowledge proof convinces one party that a statement is true while revealing nothing more. A zk-SNARK makes that proof short, produced just once, and checkable by anyone at any later time. Those accounts were intuitive, and intuition is enough to see why the problem matters. It is not enough to build a proof. This chapter supplies the precise definitions and the concrete machinery the rest of the thesis is built on.

We assemble the background in the order the later chapters reach for it. We begin with zero-knowledge proofs as formal objects: the three properties such a proof must have, and two supporting tools the constructions reuse --- a hash that removes the need for interaction, and a polynomial identity that exposes a cheating prover. We then turn to the machine that actually produces our proofs, the arithmetic circuit and the SNARK built on top of it, and to the way a circuit handles memory, which governs more of what follows than its size alone. Next are the cryptographic primitives the circuits call on: a single hash function, put to three different jobs, and the commitments built from it. With the tools in hand we return to the problem itself --- why the Travelling Salesman Problem is hard, and how it is solved when an exact answer is out of reach. We close by fixing what our proofs guarantee, against which adversary, and what they leave to others.

One rule shapes the whole chapter. We define only what a later argument uses, and we define it once.

#section([Zero-Knowledge Proofs], label: <sec:zk-proofs>)

The Sudoku game of Chapter 1 named the three properties a zero-knowledge proof must have, but left them as descriptions. This section makes them definitions, and assembles the two tools the rest of the thesis uses without pausing to explain them.

#subsection([Interactive Proofs and Their Three Properties], label: <sub:ip-properties>)

The setting is two parties and a claim. The claim is that a common input $x$ belongs to a set $L$ of true statements; for us, that a given problem instance admits a route under budget. Membership in $L$ is decided by a _relation_ $R$: the input $x$ lies in $L$ exactly when there exists a _witness_ $w$ with $(x, w) in R$, and for us the witness is the route. A _prover_ and a _verifier_ exchange messages, and at the end the verifier either accepts or rejects. The prover wants acceptance. Three properties fix when it should be granted.

_Completeness._ When the statement is true and the prover is honest, the verifier accepts. If $(x, w) in R$ and the prover follows the protocol using $w$, the interaction ends in acceptance. A true claim, argued honestly, always goes through. This is what makes the proof useful.

_Soundness._ When the statement is false, no prover convinces the verifier, except with some small probability called the _soundness error_. If $x in.not L$, so that no witness exists, then for every prover, however far it strays from the protocol, the verifier accepts only with probability below that bound. A false claim is caught almost always, whoever argues it and whatever tricks they try. The error is made as small as desired by repetition, just as the repeated rounds of the Sudoku game in Chapter 1 drove a cheat's chances toward zero. This is what makes the proof trustworthy.

_Zero-knowledge._ The verifier learns nothing from the interaction beyond the truth of the statement. This is the property that needs care, because _learns nothing_ has to be given a precise meaning, and the meaning is comparative. Imagine a _simulator_: a procedure handed the statement $x$ but not the witness, whose task is to forge a transcript of the interaction. If the forged transcript cannot be told apart from a real one by any efficient test, then the real interaction carried no information the simulator lacked --- and the simulator lacked the witness. Whatever the verifier sees, it could have produced for itself, knowing only that the statement is true. So it learns nothing more. This is what makes the proof private.

These definitions are due to Goldwasser, Micali, and Rackoff, who introduced interactive proofs and the zero-knowledge property @goldwasser1989. Completeness, soundness, and zero-knowledge are the same three roles Chapter 1 gave them --- useful, trustworthy, private --- now resting on something firmer than description.

#subsection([Knowledge and Generality], label: <sub:knowledge>)

Soundness rules out proving a false statement. For our problem that is not quite the guarantee we want. The graph is complete, so a route always exists; whether one stays under the threshold depends only on how tight the threshold is set. When the threshold is generous, feasible routes are plentiful, and the bare claim that one exists is never in doubt. What is in doubt, and what is hard to come by, is a route in hand. We do not want the prover to certify that some feasible route exists somewhere. We want it to certify that it holds one.

This stronger guarantee is _knowledge soundness_, and a proof that has it is an _argument of knowledge_ --- the phrase from Chapter 1, now earned. It is made precise through an _extractor_: an efficient algorithm that, given control of any prover convincing enough to be accepted, and free to run and rewind it, recovers a witness $w$ with $(x, w) in R$. If a witness can always be pulled out of a convincing prover, then convincing the verifier amounts to holding a witness. A prover with no route could never be accepted, because there would be nothing for the extractor to find. Acceptance certifies possession.

The name now reads in full. Its _argument_ half was settled in Chapter 1: soundness is required only against a prover of bounded computational power, never an unbounded one. Its _of knowledge_ half is the extractor just described. Together they make an argument of knowledge.

One question from Chapter 1 is still open: how general is any of this? We claimed there that a single framework could prove any statement a program can check, and called that generality structural rather than hard-won. The claim rests on a foundational result. Goldreich, Micali, and Wigderson showed that every statement in NP --- every statement whose witness can be checked efficiently --- admits a zero-knowledge proof @goldreich1991. Our statement sits squarely in that class: the witness is a route, and checking a route is easy, which was the premise of Chapter 1 all along. More than that, the route is a _Hamiltonian cycle_, the textbook NP witness, with a budget attached. The generality we will rely on is therefore not something our construction arranges. It is inherited from the class the problem belongs to.

#subsection([Removing the Interaction], label: <sec:fiat-shamir>)

The proofs defined so far are conversations. The prover commits, the verifier sends a random challenge, the prover responds, and the exchange repeats. The Sudoku game of Chapter 1 had exactly this shape. But Chapter 1 also asked for something a conversation cannot give: a proof produced once and checkable by anyone afterward, with no live exchange. We need to remove the interaction without losing what the interaction bought.

What did it buy? In the protocols we use, the verifier contributes only randomness. It draws challenges at random and does nothing else the prover could not do. The soundness of such a protocol rests entirely on one fact: the prover must commit before it sees the challenge. It is this ordering --- commit first, then be challenged --- that denies a cheating prover the chance to tailor its commitment to the challenge it will face.

The _Fiat--Shamir transform_ keeps the ordering while dropping the verifier @fiat1986. In place of a challenge sent by the verifier, the prover computes the challenge itself, as a hash of the transcript built so far --- its own commitments. A hash is unpredictable: the prover cannot know the challenge until the commitment that determines it is fixed. So the ordering survives, now as a one-way dependence. The challenge is a function of the commitment. The prover may fix its commitment and then read off the challenge; it cannot fix the challenge and then choose a commitment to suit, because the challenge is computed from the commitment, not the other way around. This one-way dependence is what the later constructions lean on, and we name it again when they do.

The result is a single, non-interactive proof. The prover runs the whole conversation alone, hashing to supply each challenge, and sends the finished transcript; anyone can recompute the hashes and check it, at any later time. This is the _non-interactive_ in zk-SNARK. The soundness of the transform is argued in the _random-oracle model_, an idealization in which the hash is treated as a perfectly random function, handed to all parties as a black box @bellare1993. Real hashes are not random functions, so the model is a working assumption rather than a theorem about any particular one. The hash we actually use, and the senses in which we trust it, are the subject of @sec:primitives.

#subsection([Catching a Cheat with a Random Point], label: <sub:schwartz-zippel>)

Fiat--Shamir hands the prover a random challenge. What makes a random challenge useful? The answer is a fact about polynomials, and it is the second tool the later constructions reuse.

A polynomial in one variable of degree $d$ has at most $d$ roots, unless it is the zero polynomial, which is zero everywhere. Over a finite field of size $q$, a nonzero polynomial of degree $d$ is therefore zero at no more than $d$ of the $q$ field elements. Pick a field element at random, and the chance of landing on a root is at most $d \/ q$. When the field is enormous --- ours has about $2^254$ elements --- and the degree is modest, this is vanishingly small. A nonzero low-degree polynomial is, in this precise sense, almost nowhere zero. The same holds for polynomials in several variables, where the statement is known as the _Schwartz--Zippel lemma_ @schwartz1980 @zippel1979.

The lemma turns equality of complicated objects into one cheap test. Suppose we must check that two objects are equal: two lists, two multisets, two assignments. Encode each as a polynomial, chosen so that the two encodings coincide exactly when the objects do. Their difference is then the zero polynomial when the objects match and a nonzero polynomial when they do not. To tell the cases apart, evaluate the difference at a random point. If the objects match, the difference is zero everywhere, so the test passes. If they do not, the difference is a nonzero low-degree polynomial, and a random point evaluates it to nonzero --- exposing the mismatch --- with overwhelming probability. One evaluation at one random point stands in for checking the objects entry by entry.

The random point is exactly what Fiat--Shamir supplies, and the order of dependence from the previous section is what keeps the test honest: the prover fixes the objects first, and the point is then fixed by hashing them. A prover free to choose its objects after seeing the point could arrange for the difference to vanish there; the one-way dependence forbids it. The guarantee is not absolute. A cheating prover slips through if the random point happens to be one of the few roots of the difference --- an event of probability at most $d \/ q$, which our field makes negligible. The check is _probabilistic_: sound, but carrying a small error that an exact check would not. This trade returns in @chap:methodology, where a route is proved to be a permutation by exactly this device, and again wherever a challenge must be bound to the values it tests.

#section([SNARKs, Circuits, and Memory], label: <sec:snarks>)

The previous section described proofs in the abstract: a prover, a verifier, and the properties their exchange must have. It did not say how such a proof is built for a real statement. The path runs through a single object that Chapter 1 named in passing, the _arithmetic circuit_. A statement becomes a circuit; a proof system runs over that circuit and produces the short, non-interactive proof we are after. We take the two in turn, the circuit and then the system, and then spend the rest of the section on the feature of circuits that shapes everything the later chapters do: how they handle memory.

#subsection([The Arithmetic Circuit], label: <sub:circuits>)

Chapter 1 already described the arithmetic circuit: numbers travel along wires through gates that add and multiply, each gate is a _constraint_ its wires must satisfy, the statement fixes the _public_ wires, and the prover fills the _private_ wires with the witness so that every constraint holds. Two details that account passed over matter now. The first is the field. The numbers are elements of a finite field $bb(F)$: the integers modulo a fixed prime of about $2^254$. Every wire carries one field element, and the two gate operations are addition and multiplication modulo that prime. The field is enormous, and it is the very one that made the Schwartz--Zippel bound of @sub:schwartz-zippel negligible --- the $q approx 2^254$ of that argument is the size of $bb(F)$.

The second detail is the one that sets circuits apart from ordinary programs. A circuit is _fixed_ before it runs. Its wires and gates are laid out in advance, identical for every input of a given size, and only afterward are the wire values filled in. It has no notion of time and no control flow: it is a static graph of constraints, not a sequence of steps. A program may loop until some condition is met; a circuit cannot, so every loop is _unrolled_ to a fixed number of repetitions chosen when the circuit is built. A program may branch on a value it computes and follow one path or another; a circuit cannot, so both outcomes must be written as arithmetic that holds either way. The circuit does not bend to its input. It is the same shape for every input of the same size, and the input chooses only the values that flow through it.

This rigidity is the price of turning a computation into a fixed system of equations, and it carries a consequence the later chapters meet again and again. Anything whose shape depends on the witness is awkward, and usually expensive: the length of a loop, the direction of a branch, and --- the case that will matter most --- the position read in an array. A circuit cannot simply fetch the element at a secret index, because it has no addressable memory to reach into. How it manages such reads at all is the subject of @sub:memory. For now the point is only that the difficulty exists, and that it comes from the circuit being fixed in advance. The _size_ of a circuit is its number of gates, and because the circuit covers every input of a given instance size $n$, that number grows with $n$. Size is the cost the whole thesis is organized around, because it is the prover's work, and the prover's memory, that grow with it.

#subsection([From Circuit to SNARK], label: <sub:snark>)

A circuit fixes the statement; the proof system turns a satisfying assignment of its wires into a proof. We need not open the system up, only state its interface and its guarantees. The prover hands it the circuit and a full assignment --- public values and witness together --- and receives a proof. The verifier hands it the circuit, the public values, and the proof, and receives accept or reject. What comes back carries the three properties of @sec:zk-proofs, now for the relation the circuit encodes.

Two of the guarantees earn the name SNARK, and both were anticipated in Chapter 1. The proof is _non-interactive_: a single object, produced once through Fiat--Shamir's hashing of the transcript (@sec:fiat-shamir), with no live exchange. And it is _succinct_: small and quick to check, at a size and verification cost that do not grow with the circuit. In our system every proof is the same fixed size, 14,656 bytes, whether it attests to a few thousand gates or a few million, and a statement far too large to re-execute is checked from that one object in milliseconds. This is the property that made a SNARK worth choosing in Chapter 1: the verifier's side is settled, and the cost lives with the prover.

The system we use is UltraHonk, the prover of the Barretenberg library, built on the Plonkish family of arithmetizations @gabizon2019 @aztec_barretenberg. Two of its features surface later. First, beyond addition and multiplication it offers _lookup_ gates, which check that a value appears in a fixed table; these will matter for memory in @sub:memory. Second, the prover works over a domain whose size is a power of two, so a circuit is padded up to the next power of two before proving. Cost then rises in steps rather than smoothly: two circuits whose gate counts fall between the same pair of powers of two are padded alike and cost the same to prove. We use this in @chap:methodology, where a circuit with more gates proves no slower than a leaner one because both land on the same step.

It helps to fix which guarantees come from where, because the distinction governs how the rest of the thesis reads. There are two layers. The lower layer is the backend just named. It provides knowledge-soundness, zero-knowledge, and succinctness, on its own cryptographic assumptions, for _any_ circuit handed to it; it neither knows nor cares what the circuit computes. It is the same backend for every construction in this thesis, so it can never be the reason one construction is more private, or more sound, than another. The upper layer is ours: the circuit we write, and within it the line between public and private wires. Every choice this thesis makes lives in the upper layer.

Two consequences follow, stated here once so that later chapters may assume them. The first is about soundness. The backend guarantees only that a proof attests to some satisfying assignment of the circuit; whether a satisfying assignment really is a valid route is a question about the circuit's own constraints, some of which are the probabilistic checks of @sub:schwartz-zippel. The overall soundness error is thus the backend's error plus the error of those in-circuit arguments. We state soundness in this reduced form throughout, and Chapter 5 makes it formal. The second is about privacy. The backend's zero-knowledge hides the witness wires, identically for every construction. So when a later chapter calls one construction more private than another, it never means the zero-knowledge is stronger --- it cannot be. It means the construction's _public_ wires carry less about the route. Privacy, in this thesis, is a property of where the public-private line is drawn, not of the proof system that hides whatever falls on the private side.

#subsection([Memory in a Circuit], label: <sub:memory>)

We noted in @sub:circuits that a circuit has no addressable memory, and that reading the element at an index not known when the circuit is built is therefore awkward. Here is how it is done. The prover supplies the value it claims sits at that index, on a witness wire, and the circuit checks that the claim is consistent with the array's contents. The read becomes a check. What that check costs is the whole question, and the answer turns on two things: how much is known about the index, and whether the array can change.

The cheapest case is no indirection at all. When the index is fixed in advance --- a constant, or a loop counter settled by unrolling --- the circuit knows which wire holds the value and simply connects to it. A _static_ read costs nothing beyond the wire. Most reads in a well-built circuit are of this kind, and they set the floor: the work to beat, and the work the later constructions try to stay near.

The next case is a read at an index the prover chooses, a _dynamic_ read, into an array that does not change --- a _read-only memory_. Here the indirection is unavoidable, and consistency is enforced after the fact. The classical method, offline memory checking, gathers all the reads and proves in one stroke that the whole collection of claimed index--value pairs agrees with the array, through a permutation argument over the accesses @blum1994. UltraHonk offers this through the _lookup_ gates of @sub:snark: a lookup proves that a claimed pair appears in a fixed table of the array's true contents @gabizon2020. The cost is real but moderate, and it falls in two places at once: in extra gates for the consistency argument, and in extra work for the prover when solving the witness, which must now resolve the bookkeeping that argument describes. The second of these costs returns, sharply, in @chap:methodology.

The last case is a memory that can also be written, a _read--write RAM_, where a read must return the most recent write to its address. Consistency now has to respect time as well as address: the usual method sorts all accesses by address and by when they occurred, then checks that reads follow writes correctly. This is the most expensive of the three, and we avoid it entirely --- our circuits read fixed data and never write, so a read-only memory suffices throughout.

The three cases form a ladder of cost: static the free floor, read-only memory a moderate charge, read--write RAM the costliest. Where a computation sits on that ladder is not dictated by the problem but chosen by how the circuit is written, and the same value can often be reached by a static read under one formulation and a dynamic read under another. That choice --- pay for dynamic memory, or rearrange the computation to avoid it --- is a recurring lever in the chapters ahead. It first decides a result in @chap:methodology, where two ways of checking the very same permutation differ chiefly in how much dynamic memory each one needs.

#subsection([Verifying a Proof Inside a Circuit], label: <sub:recursion-bg>)

Verifying a proof is itself a computation. The verifier runs a fixed algorithm on three inputs: the proof, the public values, and a _verifying key_ that stands for the circuit being checked. Anything a fixed algorithm computes, a circuit can encode, and so it can encode the verifier. We can build a circuit that takes a proof as input and outputs a single verdict wire: this proof checks, or it does not. A circuit that verifies another proof inside itself is the basis of _recursion_.

Recursion lets one proof stand for many. An outer circuit takes several inner proofs as witness, verifies each of them in-circuit, and re-proves their combined claim, emitting a single proof in their place. A verifier then checks that one outer proof instead of all the inner ones, and its work falls back to the constant cost of @sub:snark, however many proofs were gathered in. Soundness composes: if the outer proof is sound and it verified the inner proofs honestly, the inner statements hold. The price is the prover's. A verifier's algorithm is heavy to express as constraints, so a circuit that verifies even a few proofs is large and slow to prove. That trade --- a constant verifier bought at a large prover --- is the one @chap:hierarchical weighs when it builds a recursive construction, and the proof systems that make recursion practical, such as Halo @bowe2019halo, are surveyed in @chap:related-work.

#subsection([What We Measure], label: <sec:metrics>)

We have a circuit and a system to prove it. The rest of the thesis compares many such circuits, so we close this section by fixing how a circuit's cost is measured. Size, we said, is the number of gates, and that number is itself the product of a compilation. Our circuits are written in Noir, a language that compiles first to an intermediate form --- a list of _ACIR opcodes_ --- which the backend then lowers into gates. The two are different rulers for the same circuit: one opcode may expand into many gates, so opcode count and gate count need not move together. We report gate count as the measure of size, and note where the two diverge, because one such divergence becomes a result in its own right in Chapter 6.

Beyond size, each circuit is measured on a fixed set of quantities, the same throughout the thesis. Four are times: how long the circuit takes to _compile_, to _generate the witness_ from the inputs, to _prove_, and to _verify_. Two are sizes: the _proof_ in bytes --- constant, as @sub:snark noted --- and the _peak memory_ the prover uses. Of these, two carry most of the weight. Gate count and proving time track the prover's effort; peak memory tracks what the prover must hold at once, and it is the quantity that, once it exceeds the machine, turns a slow proof into an impossible one. That is the metric the whole argument of this thesis turns on.

One feature of these circuits deserves a name, because it shapes what the measurements can and cannot reveal. A circuit is _data-oblivious_: being fixed and branch-free, it executes the same gates in the same order whatever the witness holds. Two runs on different secret routes are indistinguishable from the outside --- same size, same timing, same shape. Nothing about the witness leaks through how the proof is computed; whatever a proof discloses, it discloses through its public values alone. This is the boundary @sub:snark drew for privacy, now seen from the side of cost: the quantities above are properties of the circuit and the instance size, never of the secret carried through them.

#section([Hash-Based Primitives and Commitments], label: <sec:primitives>)

Two cryptographic objects recur throughout the constructions: a hash function, and the commitments built from it. We have already leaned on a hash once, to remove interaction in @sec:fiat-shamir, and promised to say which one and why we trust it. This section keeps that promise, and then builds the commitments --- the tools that let a circuit refer to data it does not reveal --- that the cost representation of @chap:methodology and the composite constructions of @chap:hierarchical rest on.

#subsection([The Hash, and Its Three Jobs], label: <sub:poseidon>)

A _hash function_ takes an input of any size and returns a short, fixed-size digest, by a rule that is cheap to compute but practically impossible to invert or to fool. Most familiar hashes, such as SHA-256, are built to run fast on bit-oriented hardware. Inside an arithmetic circuit they are prohibitively expensive: their bitwise operations have no natural expression in field arithmetic, so each call costs tens of thousands of gates. We use _Poseidon2_ instead, a hash designed for this setting @poseidon2. It works directly on field elements, through the same additions and multiplications a circuit is made of, so a single call costs a few dozen gates rather than tens of thousands. Where a circuit must hash --- and ours hash often --- Poseidon2 is the difference between a feasible circuit and an impossible one.

A hash is trusted for different reasons in different places, and this thesis relies on three of them. The same Poseidon2 does three jobs, and each job leans on a separate security property.

The first is its role as a stand-in for a random function, the _random-oracle_ sense of @sec:fiat-shamir: when the prover hashes a transcript to draw a Fiat--Shamir challenge, the hash is trusted to return something unpredictable, as a truly random function would. The second is _collision resistance_: it must be infeasible to find two different inputs with the same digest. This is what lets a single digest stand in for the data it was computed from, and it is the property the Merkle commitments of @sub:merkle are built on. The third is _preimage resistance_: given only a digest, it must be infeasible to recover an input that produces it. This is what lets a hash conceal a value while still pinning it down, the property the commitments of @sub:commitments use to hide.

One primitive, three properties, three jobs. Naming them apart matters, because the later soundness and privacy arguments invoke them one at a time, and because they do not rest on the same footing. Collision and preimage resistance are standard, well-studied assumptions about the hash; the random-oracle sense is the idealization already flagged in @sec:fiat-shamir, stronger and less literal. When it counts, we will say which sense a step depends on.

#subsection([Merkle Commitments], label: <sub:merkle>)

A circuit must often refer to a large array --- the cost matrix has $n^2$ entries --- without carrying the whole of it as public input. A _Merkle commitment_ does this @merkle1987. It reduces an array to a single short digest, the _root_, that pins down every entry, and it lets any one entry be revealed later without revealing the rest. The entries are placed at the leaves of a binary tree and then combined upward: each internal node is the hash of its two children, and the root is the single hash at the top. Some Merkle constructions first hash each leaf as well; ours does not. The cost entries themselves, cast to field elements and padded with zeros to the next power of two, are the leaves. The first hash combines pairs of cost leaves. This saves one Poseidon2 call per opened edge, and the missing position information is supplied by the explicit leaf-index check below. Because the root depends, through the tree, on every leaf, it commits to the whole array at once.

To show that a particular entry sits at a particular leaf, the prover gives an _opening_: the entry itself, together with the sibling hash at each level on the path from that leaf to the root. From these the verifier recomputes the chain of hashes up the tree and checks that it arrives at the committed root. The opening has the length of that path, the tree's _depth_, about $log_2$ of the number of leaves, so a single entry of a vast array is proved with a handful of hashes rather than by rereading the array. This is what makes the commitment usable inside a circuit: an entry is read by verifying its opening, at a cost set by the depth, not the size. More specialized committed-membership and lookup arguments, such as Caulk, can batch or accelerate this kind of table-membership proof @zapico2022caulk; we use Merkle openings as the simple, transparent baseline that the later optimization discussion can improve on.

The commitment is _binding_: once the root is fixed, the prover cannot open a leaf to a value other than the one it holds. To do so, the recomputed chain would have to reach the same root from a different value, which means two different inputs hashing to one node along the way --- a collision. The collision resistance of @sub:poseidon forbids it, up to the same negligible chance that defines the assumption. Binding is the second of the hash's three jobs, now made concrete.

One subtlety is easy to miss and fatal to omit. An opening proves that a value hashes up to the root along _some_ path; on its own it does not prove _which_ leaf the value sits at. The shape of the path --- which sibling is left and which is right at each level --- encodes the leaf's position, so that position must be checked, not assumed. A circuit that verifies only that a value reaches the root, without tying the path to the index claimed, can be fooled: a prover reads the entry it wants from the wrong position, supplies that position's genuine path, and passes. Our circuits read the cost matrix at indices the route dictates, so they must verify both that an opened value reaches the root and that it does so from the index in question. This leaf-index check is small but load-bearing, and @chap:methodology returns to it where it matters.

What a Merkle commitment gives is binding, and binding alone. The root pins the array down, but it does not by itself _hide_ it: if the entries are few or guessable, anyone can try candidate arrays and see which reproduces the root. Hiding is a separate property, with its own cost, and it is where we turn next.

#subsection([Hiding, Binding, and Pedersen], label: <sub:commitments>)

A _commitment_ is a short value that stands for a hidden one, published now and opened later. It is asked to do two things, and they pull against each other. It must _bind_: having committed, the committer cannot open to any value but the one it fixed --- the property @sub:merkle gave us. And it must _hide_: the commitment on its own reveals nothing about the value inside it --- the property @sub:merkle did not. A Merkle root binds an array but may leak it; to hide as well, a commitment needs something more.

The missing ingredient is randomness. A hiding commitment mixes the value with a fresh random _blinding_ value, so that the same value committed twice yields two unrelated commitments and the commitment alone betrays nothing. But hiding and binding cannot both be made absolute. If a commitment hides perfectly --- if commitments to different values are distributed identically --- then some commitment must be openable to more than one value, and a committer of unlimited power could find the second opening: binding is then only computational. If instead it binds perfectly, the value is fixed by the commitment beyond all doubt, so an adversary of unlimited power could in principle read it back: hiding is then only computational. At most one of the two can hold unconditionally, against an adversary of any power; the other must rest on a computational assumption, a problem believed hard.

Two commitment schemes bracket that choice, and both have a part to play here. The first is a hash commitment: to commit to a value, hash it together with a random blinding value, by one call to the Poseidon2 of @sub:poseidon. Both of its guarantees are computational --- binding on collision resistance, hiding on preimage resistance --- and both are strong, though neither is unconditional. Its virtue is cost: a commitment is a single hash, a few dozen gates, so a circuit can make and check many of them cheaply. The second is a _Pedersen_ commitment @pedersen1991, which lives in a group where discrete logarithms are hard. It hides _unconditionally_: against an adversary of any power whatever, the commitment reveals nothing about the value, because every value is equally consistent with it. Its binding, in exchange, is computational, resting on the hardness of discrete logarithms. The price is paid in the circuit, where a Pedersen commitment needs group operations costing orders of magnitude more gates than a hash.

The two schemes mark two points on a scale this thesis returns to. A hash commitment is cheap and computationally hiding; a Pedersen commitment is expensive and unconditionally hiding. Both let a value be placed on the public surface in concealed form --- present, and bound, but not revealed --- a middle ground between a value made fully public and one kept entirely as private witness. That middle ground is where the composite constructions of @chap:hierarchical equalize privacy, and the gap between computational and unconditional hiding becomes one rung of the privacy ladder weighed there. For now it is enough to have the two properties, their tension, and the two schemes that resolve it in opposite ways.

#section([The Travelling Salesman Problem], label: <sec:tsp>)

Chapter 1 gave the formal objects of our problem in @sub:formulation: a complete weighted graph with symmetric costs, a route --- the problem calls it a _tour_ --- that visits every node exactly once and returns to its start, and a threshold the route must stay under. This section steps back to the general Travelling Salesman Problem those objects belong to, and records the facts about it the later chapters rely on: the two forms it takes, why it is hard, and how it is solved when an exact answer is out of reach. One of those facts --- the gap between finding a tour and checking one --- is the seed of this thesis's central finding, and we mark it where it appears.

#subsection([The Two Forms], label: <sub:tsp-def>)

The problem comes in two forms, and the difference between them matters here more than usual. The _optimization_ form asks for a tour of least cost: the shortest route that visits every node once and returns. This is the form the name usually brings to mind. The _decision_ form fixes a threshold $T$ and asks only whether a tour of cost at most $T$ exists --- a yes-or-no question, not a search for the best. The decision form is the one we prove a statement about, the choice made precise in @sub:formulation as proving feasibility rather than optimality: the carrier shows that her route stays under budget, not that it is the cheapest one possible.

The problem is old and thoroughly studied. Dantzig, Fulkerson, and Johnson put it on its modern computational footing in 1954, solving a 49-city instance by methods that became a root of integer programming @dantzig1954. It has been a benchmark for combinatorial optimization ever since, and the standard account of its computational study is the monograph of Applegate and co-authors @applegate2006.

#subsection([Why It Is Hard], label: <sub:tsp-hardness>)

The problem resists brute force. A tour is an ordering of the $n$ nodes, so for symmetric costs the number of distinct tours grows like $(n - 1)! \/ 2$ --- already astronomical for a few dozen nodes, and hopeless to enumerate beyond that. Nor is there a known shortcut. The decision form is NP-complete and the optimization form NP-hard @karp1972: no algorithm is known that solves every instance in time polynomial in $n$, and it is widely believed none exists. Solving large instances exactly is therefore out of reach, which is why the methods that scale give up the guarantee of an exact answer.

One feature of this hardness deserves to be drawn out, because it shapes much of what follows. Finding a good tour is hard, but _checking_ one is easy. Given a tour and a threshold, confirming that it visits every node once and that its cost stays under the threshold takes only a walk along its edges --- work that grows gently with $n$, not explosively. This gap between finding and checking is what defines the class NP, and it is exactly what makes a zero-knowledge proof worthwhile here: the prover does the hard part once, in private, and leaves the verifier only the easy part. The same asymmetry, as @chap:hierarchical will show, is the root of this thesis's central structural finding. We name it here and return to it there.

#subsection([Solving It in Practice], label: <sub:tsp-solving>)

The methods that address the problem fall into two families. _Exact_ methods, such as branch-and-bound and cutting-plane algorithms, return a provably optimal tour, but their running time climbs steeply with $n$ and reaches a ceiling beyond which they are impractical. _Heuristic_ methods give up the optimality guarantee in exchange for speed: a tour is built quickly, for instance by repeatedly walking to the nearest unvisited node, and then improved by local search such as 2-opt or the Lin--Kernighan algorithm @lin1973. The tour they return is usually good and rarely optimal, which for most purposes is a worthwhile trade.

One technique deserves singling out, because the chapters ahead return to it: _decomposition_. Instead of solving the whole instance at once, one partitions the $n$ nodes into $K$ smaller groups, solves a tour within each group, and joins the partial tours into one @karp1977. The gain comes directly from how steeply the cost of solving climbs with size. A single instance has on the order of $(n - 1)! \/ 2$ tours to reckon with; one group of $n \/ K$ nodes has only $(n \/ K)!$, and even across all $K$ groups, with the $K!$ ways of arranging the groups thrown in, the total stays smaller than the original by an enormous factor. Replacing one large search with several small ones cuts the work sharply, and the savings dwarf the cost of joining the pieces. The joined tour is generally suboptimal, but a good tour found fast is, again, usually worth more than the optimal one found slowly. Decomposition is a standard and effective way to bring a hard instance within reach, and it is the idea the decomposition chapters of this thesis take up --- in a different setting.

#section([Threat Model], label: <sec:threat-model>)

We close the background by fixing what the proof is meant to guarantee, against whom, and what it leaves to others. The statement is the one of @sub:formulation. Public are the problem instance and the threshold: the cost matrix --- in whatever form @chap:methodology chooses to supply it --- and the bound $T$. Private is the route. The proof is non-interactive (@sec:fiat-shamir): the prover produces it alone and anyone may check it afterward.

The adversary is a _cheating prover_: a party that wants the verifier to accept when it should not, when no feasible route exists or when the prover does not actually know one. We assume the prover is _computationally bounded_, restricted to feasible computation. This is the _argument_ setting of @sec:zk-proofs: soundness is required against such a prover, not against one of unlimited power. The verifier is honest, meaning it runs the checks as specified. Because the proof is non-interactive, the verifier sends nothing back that a prover could exploit, and there is no interaction to corrupt.

Against this adversary the proof carries the three guarantees of @sec:zk-proofs, now read for our problem. _Completeness_: a prover who knows a feasible route can always convince the verifier. _Knowledge soundness_: a prover the verifier accepts must know a feasible route, in the precise sense that one could be extracted from it, and a cheating prover succeeds only with negligible probability. _Zero-knowledge_: the verifier learns nothing beyond the truth of the statement, neither the route nor its exact cost. As @sub:snark set out, knowledge soundness rests on the backend together with the circuit's own in-circuit arguments, and the overall error is the sum of the two; @chap:hierarchical makes that accounting formal for each construction.

Three things the proof does not guarantee, and we name them so that later claims are not misread. The first is the authenticity of the input. The proof certifies a feasible route _against the matrix and threshold it is given_; it does not certify that the matrix holds the true costs. A prover who supplies a matrix of all zeros can honestly prove a zero-cost route. This bites hardest where the matrix is committed rather than made public --- the representation @chap:methodology introduces --- since there the verifier never sees the matrix at all, only a commitment to it. The principle has a name: binding is not authenticity. A commitment ties the proof to one fixed table, but something outside the proof, a signature or a published reference, must vouch that the table is the right one. The proof secures the route, not the data it is judged against.

The second is anything outside the statement. The proof says a feasible route is known; it says nothing about whether a cheaper route exists, how good this one is, or who the prover is. Optimality, in particular, is never claimed: the guarantee is feasibility against the threshold, the choice made back in @sub:formulation. The third is side channels at the level of the system rather than the circuit. Within the circuit, the data-obliviousness of @sec:metrics ensures that a proof's size and timing carry nothing about the route; what happens on the machine that runs the prover, its memory traffic or its power draw, lies outside this model. With the guarantees and their limits fixed, the vocabulary is in place for @chap:hierarchical to read off, construction by construction, exactly what each one trusts and what it reveals.
