#import "/theme/headings.typ": chapter, section, subsection
#import "/theme/colors.typ": colors
#import "/theme/utils.typ": inline, lc, fn

#chapter([Conclusions], label: <chap:conclusions>)

This thesis set out to make one trade-off answerable. Not in the abstract, where it is a truism that privacy, cost, and scale pull against each other, but for a concrete #smallcaps[np] statement a prover might actually want to prove in zero knowledge---a route through a graph whose cost stays under a threshold---and with numbers rather than intuition deciding where the lines fall. The arc that answered it is short to recall. A flat baseline fixed the control everything is read against. A dualism and a stitching tax said what cutting that baseline into pieces must cost, and a privacy ladder, walked one construction at a time, said what each cut buys back in secrecy. And a frontier placed the surviving constructions where each pays, three corners with no center, the deployer left to choose which good to forgo. The answer the thesis reached is that picture, and the case for it is the chapters behind this one.

This chapter looks back at the picture rather than adding to it. It asks first whether the framework that drew the frontier was the right instrument to draw it with (@sec:framework-retrospect), then turns the frontier from a diagram into guidance for someone who has to choose a construction, says plainly and in one place what the work does not show, and closes on the construction that would fill the frontier's empty center---the folding schemes the body has pointed toward all along, taken up as future work in @sec:future-work.

#section([The Framework in Retrospect], label: <sec:framework-retrospect>)

The framework came before the measurements. The dualism, the stitching tax, the fingerprint lever, and the pick-two triangle were all claims made from the structure of the constructions, set down in @chap:hierarchical before a single one of them was timed, and a results chapter has now had its say on each. So the honest question to open a conclusion with is not whether the numbers came out well---they did---but whether the frame earned its keep: whether it predicted what the benchmarks found, or merely supplied a vocabulary for narrating them after the fact. The difference shows in falsifiability. A frame that only ever fits is decoration; a frame that forbids things, and is not contradicted, is a lens. Taken one idea at a time, ours mostly forbade.

The dualism was the most exposed of the claims, and so the most informative when it held. It said that decomposition conserves the prover's total work: cut a proof into segments and the gates can only be relocated and taxed, never reduced, so the hierarchical total can never fall below the flat one. A single instance in which it did---one size, one segment count, where splitting bought a cheaper proof---would have broken the claim outright. @sub:dualism-measured found none. The $K$ segments summed back to the flat gate count within a percent at every size, and every total, across every variant and every $K$, sat above the conservation floor. The frame here did more than fit the data; it ruled a thing out, the free lunch from splitting, and the ruling held without exception. That is the cleanest kind of confirmation a structural claim can get.

The stitching tax was specific in a way that gave it room to be wrong. The frame did not merely say there would be a tax; it said how the tax should move---shrinking as the instance grows and the glue's fixed cost dilutes, rising as the segment count grows and there is more to stitch---and it named the one variant that should refuse to dilute, committed-sort, whose $O(n)$ commitment re-fold rides at a fixed fraction of the circuit rather than thinning against it. All three predictions held to the percent. The tax fell from several percent at small sizes toward a single percent at large ones, rose with $K$ at every size, and committed-sort alone stayed pinned at seven to seventeen percent, heaviest and undiluting, exactly the asymmetry @chap:hierarchical had drawn between the two committed variants from their shapes alone. A frame precise enough to be falsified on three counts, falsified on none, is doing real work.

The fingerprint lever the measurement did not merely confirm but sharpened. The frame's careful claim was that swapping the sort mechanism for the grand product changes the glue's coverage cost as a matter of _slope, not class_---the product still touches all $n$ nodes, so its coverage stays $O(n)$, only at a gentler rate per node. There was a tempting overstatement nearby, that the product collapses an $O(n)$ check to a handful of multiplications, and the frame had explicitly warned against it. @sub:lever-measured vindicated the careful reading over the tempting one: both glues came out linear in $n$, the product's slope about seven times gentler than the sort's but a slope all the same, never the flat line a true $O(K)$ coverage would draw. And the same lever is the witness inversion of @sec:witness-inversion surfacing a second time at the recombiner---the arithmetic mechanism solving its witness faster precisely where the gate count says it should be slower. To be right about the thing that was easy to get wrong is the strongest sign a lens is ground correctly.

The pick-two triangle was the frame's headline, and the most striking to see reproduced. It was an architecture-level claim, drawn from the three constructions' shapes before any of them had a wall-clock or a peak-memory figure attached: each holds two of cheap, parallel, and private, and yields the third, so the deployable set is three corners around an empty center. @sec:frontier-figure redrew that triangle from the measured points, and the two drawings agree corner for corner---three non-dominated constructions, no fourth, and the center genuinely empty rather than merely unoccupied. The frontier was not found in the data and then explained; it was argued first and then found, which is as much as an empirical chapter can do to confirm that the shape was real and not imposed.

A frame that only ever confirmed itself would invite suspicion, and ours did not. Two places it strained, and both are worth stating, because both are refinements the measurement forced rather than failures it exposed. The first is inside the triangle's "parallel" corner, which the word flatters. @sec:frontier-figure found recursion's wall-clock sitting _above_ flat's, not below: its segments stay small and clear the memory wall, reaching instances flat cannot touch, but its monolithic outer proof runs alone and dominates the clock, so the good recursion actually holds there is scale and low per-prover memory, not a faster finish. The single axis labeled "parallel" quietly bundles two goods that recursion and the hierarchical constructions hold in different measure, and only the two-clock discipline of @sub:control-both-clocks kept the bundle from misleading. The second is a caution about how to read the mechanism choice. The frame insisted, back in @sec:witness-inversion, that the choice between sort and product would _not_ be settled by their costs, which run to a near-tie, but by what each becomes under decomposition; @sec:two-by-two bore that abstention out, finding the mechanism a small row against an aggregation column that dwarfs it. The vivid witness inversion, real as it is, is a secondary mark on the product's account and not the reason it earns its place---the reason is the $O(1)$ surface decomposition exposes. Even where the frame declined to let the numbers decide, the numbers declined too.

On balance, then, the lens was the right one---not because it flattered the constructions but because it made claims the benchmarks could have broken and largely did not, and because where it bent it bent into a sharper statement rather than a wrong one. The dualism it got exactly right, the stitching tax in all three of its particulars, the lever it understated and the measurement corrected upward, the triangle it predicted whole. What the frame cannot do is choose, for a deployer standing in front of the three corners it correctly drew, which corner is theirs. That is a separate task from drawing the frontier, and turning the frontier into a decision is where this chapter turns next.

#section([From Frontier to Decision], label: <sec:practical-guidance>)

The frontier places three constructions and ranks none, and the first control of @sec:fairness-controls is the reason it cannot. Flat, committed-product, and recursion are not better and worse versions of one thing; they hide different things, on different assumptions, and a cost from one is not a victory over a cost from another. So there is no construction to recommend in the abstract, and the question "which is best" has no answer. The question that does have one is "best for what", and it is settled not by the constructions but by the deployment---by what the proof must hide, how large the instance is and whether it can be spread, and how the proof will be checked. This section turns those three considerations into a procedure, and walks it on the scenarios @sec:motivation raised.

Three questions fix a corner. The _first_ is about privacy, and it is the question @sub:privacy-ladder taught us to ask precisely: not "must the route be hidden" but _on what assumption_. If the route may be disclosed, none of this thesis's machinery is needed. If it must be hidden but a computational assumption is acceptable---the partition sealed behind a commitment that an unbounded adversary could in principle open---the computational class is in play. If it must be hidden on _no_ assumption, absent from the proof rather than encrypted within it, only the structural class will do. The _second_ question is about scale and parallelism: does the instance fit on one machine, or does it run past the memory wall of @sub:flat-wall, a little beyond four thousand nodes, where a single prover can no longer hold the circuit? And is there parallel hardware to spread the work across, turning the conserved total of @sec:parallel-proving into a shorter wall-clock? The _third_ is about verification: is the proof checked once, by a single known counterparty who can afford to download the $K + 1$ proofs an external stitch produces, or is it checked many times, by many independent verifiers or a public ledger, where the $O(K)$ download of @sec:two-by-two is paid over and over and only an $O(1)$ proof will serve?

The scenarios of @sec:motivation, extended along these three axes, fall to three different corners---which is the practical content of the frontier having three corners at all.

Take first the armored-truck operator, proving to an auditor that its transit runs stay under a time limit without surrendering the routes. Its instance is modest---a city's worth of secured sites, well short of the wall---and its secrecy is safety-critical: the routes protect lives and high-value cargo, so a privacy that rests on a commitment an adversary might someday open is the wrong bet, and structural hiding, the route absent from the proof entirely, is the prudent default. The verifier is a single auditor, checking repeatedly. A small instance, structural privacy, a single cheap proof, no need to spread the work: this is _flat_ exactly. It is the cheapest construction, hides on no assumption, and verifies in one constant-time check; the one thing it cannot do, grow past the wall, the scenario never asks of it. The corner's weakness is invisible here, which is precisely when it is the right corner.

Take next the national logistics firm of @sec:motivation, scaled to the size its business implies---thousands of delivery points, an instance well past what one machine can prove. It has a fleet-scheduling cluster already, so parallel hardware is at hand, and its proof goes to one party, the contracting authority it bids to. Its secret is commercial, the proprietary routing it does not want copied, and the adversary is a competitor of ordinary means, not an unbounded one---so computational hiding, the partition sealed under a commitment, is enough. A large instance, parallel hardware, a single counterparty, and computational privacy acceptable: this is _committed-product_. It clears the wall its size would otherwise hit, spreads across the cluster to finish in a fraction of the flat wall-clock, hides the partition for a few tenths of a percent over disclosing it, and pays the one price the scenario can absorb---an $O(K)$ proof the single contracting authority downloads once. Were that authority instead a thousand independent auditors, the $O(K)$ download paid a thousand times would push the choice elsewhere, which is the next scenario.

Take last a public-tender or consortium setting, where a feasibility proof over a large network is published once and verified by many---a blockchain, a regulator's open registry, a field of competing bidders each checking the others. Now all three demands arrive together: the instance is large, past the wall, so the work must be spread; the proof is checked by many, so the verifier must be $O(1)$; and the route, made part of a permanent public record, must stay hidden even against an adversary with time and power on its side, so the privacy must be structural. Flat cannot reach the size; committed-product gives up structural privacy and the cheap verifier both. Only _recursion_ holds all three of the goods this scenario insists on---it spreads the segments, hides the partition on no assumption, and folds everything into a single proof a thousand verifiers each check in milliseconds. It is the dearest construction in the family by a factor of several, and here the expense is simply the price of admission: no cheaper corner meets the three demands at once. Recursion is not the construction to reach for often, but when structural privacy, scale, and a cheap public verifier are all required, it is the only one that answers.

@fig:decision collects the procedure. One construction it leaves to a footnote in the table is committed-sort, which @sub:price-of-privacy found dominated on cost by committed-product and so never a corner of its own. It returns for exactly one kind of deployer: one who will not accept coverage argued by the probabilistic Schwartz--Zippel check the grand product rests on, and demands instead the exact, algebraic certainty of the sort. For a regulator or standard that forbids a negligible soundness error on principle, committed-sort buys that certainty for the six-to-seven percent @sub:within-class measured---a soundness preference, paid for in gates, sitting beside committed-product rather than replacing it.

#figure(
  caption: [Choosing a construction from the deployment. The three questions---what must be hidden and on what assumption, whether the instance exceeds one machine, and whether the verifier is one party or many---route to one of the three non-dominated corners of @sec:frontier-figure. Committed-sort is not a corner but a soundness option: where a deployer rejects the grand product's probabilistic coverage, it buys exact coverage for the premium of @sub:within-class.],
  table(
    columns: (auto, auto, auto, auto),
    align: (left, left, left, left),
    table.header([*privacy required*], [*instance / hardware*], [*verifier*], [*construction*]),
    [structural (no assumption)],  [fits one machine],           [one or many],          [flat],
    [computational (commitment)],  [large; parallel hardware],   [one counterparty ($O(K)$ ok)], [committed-product],
    [structural (no assumption)],  [large; parallel hardware],   [many / public ($O(1)$ needed)], [recursion],
    [either, but exact coverage required], [as above],            [as above],             [committed-sort#footnote[The soundness option, not a fourth corner: exact algebraic coverage in place of the grand product's probabilistic check, at the premium of @sub:within-class.]],
  ),
) <fig:decision>

The procedure is only as good as the costs it stands on, and those costs were measured under conditions this chapter has not yet stated plainly in one place---one proof system, one notion of parallelism, one problem. A deployer reading @fig:decision is entitled to know where its numbers come from and where they stop applying. Setting that out, honestly and in one place, is the next section's task.

#section([What the Work Does Not Show], label: <sec:limitations>)

The thesis flagged its limits as it met them---the two-clock caveat of @sub:control-both-clocks, the soundness it cites rather than proves, the single backend behind every figure---but flags scattered through six chapters are easy to lose, and a reader weighing the frontier deserves them collected. Four limitations bound the claims, and we state them in order of how far they reach, each with the line between what the work establishes and what it leaves open.

The first is that every number came from one proof system. All the measurements ran on UltraHonk, the Barretenberg prover, and the two-layer framing of @sub:snark is what says which claims survive a change of backend and which do not. The framework is the surviving part: the dualism, the placement of the public--private line, the privacy ladder, and the pick-two shape are statements about _where the partition sits relative to the witness_ and about _how decomposition relocates work_, and neither depends on how the underlying argument is compiled. The constants are the part that does not survive: the gate counts, what a single hash call costs inside the circuit, the memory wall a little past four thousand nodes, the crossover near $n = 176$ where committing the matrix overtakes publishing it, the seventy-percent witness inversion at $n = 3000$. Each of these is a property of this backend's arithmetization---its hash cost, its memory-checking scheme, its power-of-two padding---and another backend could move any of them. We claim the shape of the frontier, not the coordinates of its corners.

The second is that the parallel speedups were measured in isolation. The wall-clock wins of @sec:parallel-proving rest on the composition assumption @sub:control-both-clocks stated openly: the parallel time is the critical path, the longest segment plus the glue that waits on all of them, computed as though each segment proved on its own uncontended machine, one prover per segment, with no network between them. That is an _upper bound_ on the achievable speedup, not a measured multi-machine run. A real cluster adds what the model leaves out---communication to gather the segment proofs, contention for shared resources, stragglers, the cost of distributing the witness---so a deployment lands somewhere below the sixfold ceiling by a margin this thesis did not measure. The memory side of the same result is firmer: per-prover peak memory is a property of the segment circuit, not of how the segments are scheduled, so the claim that decomposition clears the wall stands on surer ground than the claim of how much faster the clock runs. One is a measured fact about a circuit; the other is a ceiling a network erodes.

The third is that the framework was shown on one problem, in one form. The statement proved throughout is narrow by design: a Hamiltonian cycle whose cost stays under a public threshold, over a complete graph with symmetric costs---feasibility, not optimality, and the decision form, not the search. The thesis argued the framework reaches further, and the argument is not idle: the dualism is the finder--checker asymmetry of @sub:tsp-hardness, present in every NP relation, and the mechanisms are permutation and lookup arguments common to a wide class of circuits. But it demonstrated that reach on no second problem. The frontier is drawn for one statement, and the claim that another NP statement would trace the same three-cornered shape is a conjecture the structure supports, not a result the benchmarks establish. One boundary the threat model already fixed belongs in this list too: the proof secures the route against the matrix it is handed, never the matrix's authenticity---binding is not authenticity, as @sec:threat-model put it---so any real deployment needs an external anchor, a signature or a published reference, vouching that the committed costs are the true ones.

The fourth is that soundness is argued, not mechanized. Every construction's soundness is a reduction, set out in @app:soundness, and three gaps in it are carried to the conclusion rather than closed. The product and recursive constructions rest on idealizations: the grand product's coverage is sound in the random-oracle model, and recursion's knowledge soundness composes only under the heuristic that an in-circuit-verified proof is extractable---both drawn from the literature and neither reproved here, the second the standard price of folding Fiat--Shamir inside a circuit. The reductions themselves are written and checked by hand, with no proof assistant to verify them. And, most concretely, the Noir circuits have not been formally verified to encode the relations the lemmas assume they encode; the negative-test battery of @app:negative-tests exercises that correspondence against deliberate cheats and finds no gap, but a finite battery validates rather than proves. A deployer trusting these proofs trusts a cited reduction and an audited implementation, not a mechanized end-to-end guarantee.

None of the four sinks a claim; each bounds one, and stated together they fix what kind of object the frontier is. It is a measured map of one problem under one backend, whose shape is argued to be general and whose constants are not, whose parallel ceiling is real but eroded by any network, and whose guarantees rest on cited cryptography rather than machine-checked proof. What would lift each limitation in turn---a second backend to separate structure from constant, a real cluster to measure the speedup the model bounds, a second NP statement to test the framework's reach, a mechanized proof to close the soundness gap---is not a list of regrets but the shape of the work that comes after this one. That work is the chapter's last subject.

#section([The Empty Corner], label: <sec:future-work>)

The most interesting thing the work leaves open is not a flaw to be repaired but the place the whole frontier has been pointing at: the empty center of the pick-two triangle. @sec:frontier-figure found three corners and nothing between them, and the gap was not an accident of measurement but a structural fact---no construction the thesis built holds cheap, parallel, and structurally private all at once. This section takes up the directions the body marked as it went, headed by the one that would fill that center, and then closes.

Recall why the center stayed empty. Every construction either proves the whole statement in one circuit, which cannot be spread, or cuts it into segments and pays to stitch them---either in the verifier's $O(K)$ download, the price the external constructions pay, or in a heavyweight recursive outer, the price recursion pays. Recursion came closest to the center: it bought structural privacy, an $O(1)$ verifier, and the scale to pass the wall, and gave up only cost. But that cost was steep, an outer proof several times the baseline and run serially, and it came from one specific choice---binding the segments by _verifying each one's proof in full_ inside the outer circuit. That choice is not the only way to bind, and its expense is not intrinsic to decomposition. It is the expense of full re-verification, and @sec:frontier-figure called it a _characterized price_ precisely because the thesis measured what that one choice costs.

Folding schemes bind without paying it. Instead of verifying each segment's proof inside the outer circuit, they _accumulate_ each segment's instance into a single running instance, at a cost that does not grow with the number of segments, and defer the one heavy proving step to the very end. Nova introduced the technique @kothapalli2022nova, and the line after it---SuperNova, HyperNova, ProtoStar---has made it general and efficient @bunz2023protostar. Mapped onto the three goods, the promise is exactly the missing corner. The per-segment cost falls from a full verification to an accumulation, so the outer stops being a monolith and the construction recovers _cheap_; the segments still accumulate in parallel, each prover holding only its own small circuit, so it keeps _parallel_ and its low memory; and the partition is still folded away rather than published, so it stays _structurally private_. Three goods at once, the center filled. This is why recursion's cost was worth measuring rather than lamenting: the thesis pinned down what full re-verification costs, and folding is the principled way to stop paying it.

The work nearest to ours makes the point concrete. Mangrove, surveyed in @chap:related-work, is a folding framework with a uniformizing compiler, a low-memory parallel prover, and a commit-and-fold step @nguyen2024mangrove; its commit-and-fold echoes our committed constructions, and its low-memory folding is the performance realization of the corner we leave open. The honest division of labour is the one @chap:related-work already drew: this thesis contributes the structural map---the dualism, the privacy ladder, the frontier, and the application to a concrete NP statement---while Mangrove embodies the performance of folding. The natural next step joins the two: carry the privacy ladder onto a folding backend, building the committed and structural partitions over an accumulation scheme rather than a recursive verifier, and re-measure the frontier. The framework makes that re-measurement a set of testable predictions rather than a blank experiment---the dualism should hold again, since folding conserves total work no less than recursion does; the stitching tax should change in character, an accumulation in place of a re-verification; and the center, this time, should fill.

A second direction is narrower and was named in @chap:methodology rather than left for here. The per-edge Merkle proofs that carry the cost matrix into the circuit are simple and transparent but not the cheapest possible, and two roads were marked and not taken. A vector commitment that opens in constant size, a KZG or Verkle commitment, would shorten each opening, but at the price of elliptic-curve arithmetic inside the circuit and a trusted setup. The stronger road replaces the $n$ separate per-edge proofs with a single committed-lookup argument---cq, Lasso, or the Caulk line @zapico2022caulk, proving in one batched step that all $n$ used costs come from the committed table. This is very likely cheaper than per-edge Merkle proofs, and it is orthogonal to the partition story: it would lower the matrix-binding floor that every construction in the family shares alike, sliding the whole frontier downward without altering its shape. We named it as the honest answer to whether the baseline is the best one could do, and left it as work for another time.

The limitations of @sec:limitations each carry their own next step, and they round out the list. A second proving backend would separate the framework's structure from this one's constants. A real multi-machine cluster would measure the speedup the isolation model only bounds, replacing a ceiling with a number. A second NP statement would test whether the three-cornered frontier is a property of the travelling-salesman problem or of decomposition itself---graph colouring, scheduling, or any relation carrying the finder--checker asymmetry of @sub:tsp-hardness would serve, and that is the conjecture the thesis most wants tried. A mechanized, circuit-level verification would turn the cited soundness reductions into machine-checked ones. And one direction the thesis gestured at without pursuing: composing the proof layer with the clustered solver that produces the candidate tour in the first place, so that the partition the hierarchy needs is the very partition the solver already computes---the upstream search and the downstream proof meeting at the same cut.

This thesis set out to ask whether a proof of a hard combinatorial fact could be cheap, parallel, and private at once, and to answer with measurement rather than intuition, for a statement someone might really want to prove. The answer is that it cannot---not by any construction built here---but that the impossibility has a shape. There are three goods and three corners, each construction reaches two of them, and which one to give up is a question the deployment answers, not the cryptography. That frontier is what the thesis offers in place of a single best construction it could not honestly name, and the empty space at its center is not a gap in the map but a direction off the edge of it---the folding schemes that would hold all three goods at once, and the work that fills the corner this thesis was content to draw.