#import "/theme/headings.typ": chapter, section, subsection
#import "/theme/colors.typ": colors
#import "/theme/utils.typ": inline, lc, fn

#chapter([Conclusions], label: <chap:conclusions>)

This thesis set out to make one trade-off answerable. Not in the abstract, where it is a truism that privacy, cost, and scale pull against each other, but for a concrete #smallcaps[np] statement a prover might actually want to prove in zero knowledge---a route through a graph whose cost stays under a threshold---and with numbers rather than intuition deciding where the lines fall. The arc that answered it is short to recall. A flat baseline fixed the control everything is read against. A dualism and a stitching tax said what cutting that baseline into pieces must cost, and a privacy ladder, walked one construction at a time, said what each cut buys back in secrecy. And a frontier placed the surviving constructions where each pays, three corners with no center, the deployer left to choose which good to forgo. The answer the thesis reached is that picture, and the case for it is the chapters behind this one.

This chapter looks back at the picture rather than adding to it. It asks first whether the framework that drew the frontier was the right instrument to draw it with (@sec:framework-retrospect), then turns the frontier from a diagram into guidance for someone who has to choose a construction, says plainly and in one place what the work does not show, and closes on the construction that would fill the frontier's empty center---the folding schemes the body has pointed toward all along, taken up as future work in @sec:future-work.

#section([The Framework in Retrospect], label: <sec:framework-retrospect>)

The framework came before the measurements. The dualism, the stitching tax, the fingerprint lever, and the pick-two triangle were all claims made from the structure of the constructions, set down in @chap:hierarchical before a single one of them was timed, and a results chapter has now had its say on each. So the honest question to open a conclusion with is not whether the numbers came out well---they did---but whether the frame earned its keep: whether it predicted what the benchmarks found, or merely supplied a vocabulary for narrating them after the fact. The difference shows in falsifiability. A frame that only ever fits is decoration; a frame that forbids things, and is not contradicted, is a lens. Taken one idea at a time, ours mostly forbade.

The dualism was the most exposed of the claims, and so the most informative when it held. It said that decomposition conserves the prover's total work: cut a proof into segments and the gates can only be relocated and taxed, never reduced, so the hierarchical total can never fall below the flat one. A single instance in which it did---one size, one segment count, where splitting bought a cheaper proof---would have broken the claim outright. @sub:dualism-measured found none. The $K$ segments summed back to the flat gate count within a percent at every size, and every total, across every variant and every $K$, sat above the conservation floor. The frame here did more than fit the data; it ruled a thing out, the free lunch from splitting, and the ruling held without exception. That is the cleanest kind of confirmation a structural claim can get.

The stitching tax was specific in a way that gave it room to be wrong. The frame did not merely say there would be a tax; it said how the tax should move---shrinking as the instance grows and the glue's fixed cost dilutes, rising as the segment count grows and there is more to stitch---and it named the one variant that should refuse to dilute, committed-sort, whose $O(n)$ commitment re-fold rides at a fixed fraction of the circuit rather than thinning against it. All three predictions held to the percent. The tax fell from several percent at small sizes toward a single percent at large ones, rose with $K$ at every size, and committed-sort alone stayed pinned at seven to seventeen percent, heaviest and undiluting, exactly the asymmetry @chap:hierarchical had drawn between the two committed variants from their shapes alone. A frame precise enough to be falsified on three counts, falsified on none, is doing real work.

The fingerprint lever the measurement did not merely confirm but sharpened. The frame's careful claim was that swapping the sort mechanism for the grand product changes the glue's coverage cost as a matter of _slope, not class_---the product still touches all $n$ nodes, so its coverage stays $O(n)$, only at a gentler rate per node. There was a tempting overstatement nearby, that the product collapses an $O(n)$ check to a handful of multiplications, and the frame had explicitly warned against it. @sub:lever-measured vindicated the careful reading over the tempting one: both glues came out linear in $n$, the product's slope about seven times gentler than the sort's but a slope all the same, never the flat line a true $O(K)$ coverage would draw. And the same lever is the witness inversion of @sec:witness-inversion surfacing a second time at the recombiner---the arithmetic mechanism solving its witness faster precisely where the gate count says it should be slower. To be right about the thing that was easy to get wrong is the strongest sign a lens is ground correctly.

The pick-two triangle was the frame's headline, and the most striking to see reproduced. It was an architecture-level claim, drawn from the three constructions' shapes before any of them had a wall-clock or a peak-memory figure attached: each holds two of cheap, parallel, and private, and yields the third, so the deployable set is three corners around an empty center. @sec:frontier-figure redrew that triangle from the measured points, and the two drawings agree corner for corner---three non-dominated constructions, no fourth, and the center genuinely empty rather than merely unoccupied. The frontier was not found in the data and then explained; it was argued first and then found, which is as much as an empirical chapter can do to confirm that the shape was real and not imposed.

A frame that only ever confirmed itself would invite suspicion, and ours did not. Two places it strained, and both are worth stating, because both are refinements the measurement forced rather than failures it exposed. The first is inside the triangle's "parallel" corner, which the word flatters. @sec:frontier-figure found recursion's wall-clock sitting _above_ flat's, not below: its segments stay small and clear the memory wall, reaching instances flat cannot touch, but its monolithic outer proof runs alone and dominates the clock, so the good recursion actually holds there is scale and low per-prover memory, not a faster finish. The single axis labeled "parallel" quietly bundles two goods that recursion and the hierarchical constructions hold in different measure, and only the two-clock discipline of @sub:control-both-clocks kept the bundle from misleading. The second is a caution about how to read the mechanism choice. The frame insisted, back in @sec:witness-inversion, that the choice between sort and product would _not_ be settled by their costs, which run to a near-tie, but by what each becomes under decomposition; @sec:two-by-two bore that abstention out, finding the mechanism a small row against an aggregation column that dwarfs it. The vivid witness inversion, real as it is, is a secondary mark on the product's account and not the reason it earns its place---the reason is the $O(1)$ surface decomposition exposes. Even where the frame declined to let the numbers decide, the numbers declined too.

On balance, then, the lens was the right one---not because it flattered the constructions but because it made claims the benchmarks could have broken and largely did not, and because where it bent it bent into a sharper statement rather than a wrong one. The dualism it got exactly right, the stitching tax in all three of its particulars, the lever it understated and the measurement corrected upward, the triangle it predicted whole. What the frame cannot do is choose, for a deployer standing in front of the three corners it correctly drew, which corner is theirs. That is a separate task from drawing the frontier, and turning the frontier into a decision is where this chapter turns next.

#section([From Frontier to Decision], label: <sec:practical-guidance>)

The frontier places three constructions and ranks none, and the first control of @sec:fairness-controls is the reason it cannot. Flat, committed-product, and recursion are not better and worse versions of one thing; they hide different things, on different assumptions, and a cost from one is not a victory over a cost from another. So there is no construction to recommend in the abstract, and the question "which is best" has no answer. The question that does have one is "best for what", and it is settled not by the constructions but by the deployment---by what the proof must hide, how large the instance is and whether it can be spread, and how the proof will be checked. This section turns those three considerations into a procedure, and walks it on the scenarios @sec:motivation raised.

Three questions fix a corner. The _first_ is about privacy, and it is the question @sub:privacy-ladder taught us to ask precisely: not "must the route be hidden" but _on what assumption_. If the route may be disclosed, none of this thesis's machinery is needed. If it must be hidden but a computational assumption is acceptable---the partition sealed behind a commitment that an unbounded adversary could in principle open---the computational class is in play. If it must be hidden on _no_ assumption, absent from the proof rather than encrypted within it, only the structural class will do. The _second_ question is about scale and parallelism: does the instance fit on one machine, or does it run past the memory wall of @sub:flat-wall, a little beyond four thousand nodes, where a single prover can no longer hold the circuit? And is there parallel hardware to spread the work across, turning the conserved total of @sec:parallel-proving into a shorter wall-clock? The _third_ is about verification: is the proof checked once, by a single known counterparty who can afford to download the $K + 1$ proofs an external stitch produces, or is it checked many times, by many independent verifiers or a public ledger, where the $O(K)$ download of @sec:two-by-two is paid over and over and only an $O(1)$ proof will serve?

The scenarios of @sec:motivation, extended along these three axes, fall to three different corners---which is the practical content of the frontier having three corners at all.

Take first the armored-truck operator, proving to an auditor that its transit runs stay under a time limit without surrendering the routes. Its instance is modest---a city's worth of secured sites, well short of the wall---and its secrecy is safety-critical: the routes protect lives and high-value cargo, so a privacy that rests on a commitment an adversary might someday open is the wrong bet, and structural hiding, the route absent from the proof entirely, is the prudent default. The verifier is a single auditor, checking repeatedly. A small instance, structural privacy, a single cheap proof, no need to spread the work: this is _flat_ exactly. It is the cheapest construction, hides on no assumption, and verifies in one constant-time check; the one thing it cannot do, grow past the wall, the scenario never asks of it. The corner's weakness is invisible here, which is precisely when it is the right corner.

Take next the national logistics firm of @sec:motivation, scaled to the size its business implies---thousands of delivery points, an instance well past what one machine can prove. It has a fleet-scheduling cluster already, so parallel hardware is at hand, and its proof goes to one party, the contracting authority it bids to. Its secret is commercial, the proprietary routing it does not want copied, and the adversary is a competitor of ordinary means, not an unbounded one---so computational hiding, the partition sealed under a commitment, is enough. A large instance, parallel hardware, a single counterparty, and computational privacy acceptable: this is _committed-product_. It clears the wall its size would otherwise hit, spreads across the cluster to finish in a fraction of the flat wall-clock, hides the partition for a few tenths of a percent over disclosing it, and pays the one price the scenario can absorb---an $O(K)$ proof the single contracting authority downloads once. Were that authority instead a thousand independent auditors, the $O(K)$ download paid a thousand times would push the choice elsewhere, which is the next scenario.

Take last a public-tender or consortium setting, where a feasibility proof over a large network is published once and verified by many---a blockchain, a regulator's open registry, a field of competing bidders each checking the others. Now all three demands arrive together: the instance is large, past the wall, so the work must be spread; the proof is checked by many, so the verifier must be $O(1)$; and the route, made part of a permanent public record, must stay hidden even against an adversary with time and power on its side, so the privacy must be structural. Flat cannot reach the size; committed-product gives up structural privacy and the cheap verifier both. Only _recursion_ holds all three of the goods this scenario insists on---it spreads the segments, hides the partition on no assumption, and folds everything into a single proof a thousand verifiers each check in milliseconds. It is the dearest construction in the family by a factor of several, and here the expense is simply the price of admission: no cheaper corner meets the three demands at once. Recursion is not the construction to reach for often, but when structural privacy, scale, and a cheap public verifier are all required, it is the only one that answers.

@fig:decision collects the procedure. One construction it leaves to a footnote in the table is committed-sort, which @sub:price-of-privacy found dominated on cost by committed-product and so never a corner of its own. It returns for exactly one kind of deployer: one who will not accept coverage argued by the probabilistic Schwartz--Zippel check the grand product rests on, and demands instead the exact, algebraic certainty of the sort. For a regulator or standard that forbids a negligible soundness error on principle, committed-sort buys that certainty for the six-to-seven percent @sub:within-class measured---a soundness preference, paid for in gates, sitting beside committed-product rather than replacing it.

#figure(
  caption: [Choosing a construction from the deployment. The three questions---what must be hidden and on what assumption, whether the instance exceeds one machine, and whether the verifier is one party or many---route to one of the three non-dominated corners of @sec:frontier-figure. Committed-sort is not a corner but a soundness option: where a deployer rejects the grand product's probabilistic coverage, it buys exact coverage for the premium of @sub:within-class.],
  table(
    columns: (auto, auto, auto, auto),
    align: (left, left, left, left),
    table.header([*privacy required*], [*instance / hardware*], [*verifier*], [*construction*]),
    [structural (no assumption)],  [fits one machine],           [one or many],          [flat],
    [computational (commitment)],  [large; parallel hardware],   [one counterparty ($O(K)$ ok)], [committed-product],
    [structural (no assumption)],  [large; parallel hardware],   [many / public ($O(1)$ needed)], [recursion],
    [either, but exact coverage required], [as above],            [as above],             [committed-sort#footnote[The soundness option, not a fourth corner: exact algebraic coverage in place of the grand product's probabilistic check, at the premium of @sub:within-class.]],
  ),
) <fig:decision>

The procedure is only as good as the costs it stands on, and those costs were measured under conditions this chapter has not yet stated plainly in one place---one proof system, one notion of parallelism, one problem. A deployer reading @fig:decision is entitled to know where its numbers come from and where they stop applying. Setting that out, honestly and in one place, is the next section's task.