#import "/theme/headings.typ": chapter, section, subsection
#import "/theme/colors.typ": colors
#import "/theme/utils.typ": inline, lc, fn

#chapter([Results], label: <chap:results>)

The previous chapter drew a map and promised numbers. It argued, one construction at a time, that the hierarchical proofs occupy a space with three corners and no center---cheap, parallel, structurally private, and never all three at once---and it left the reader with a shape rather than a scale. This chapter supplies the scale. The pick-two triangle of @sub:pick-two is a claim about where each construction sits; what follows is the measurement that pins it there, and the discipline that keeps the measurement honest.

We begin by fixing how the numbers are to be read: three controls, stated once and then applied silently, without which a results chapter misleads as easily by arithmetic as by error (@sec:fairness-controls). We then measure the flat baseline the whole thesis is read against (@sec:flat-eval)---how its circuit grows, what a single hash call really costs, where committing the cost matrix overtakes publishing it, and which of the backend's own numbers quietly mislead. With the baseline in hand we turn to the constructions: their gate counts set against the predictions of @chap:hierarchical (@sec:gates-vs-prediction), their proving time and memory when the segments are spread across machines (@sec:parallel-proving), and a small factorial that separates the price of aggregating from the price of the mechanism (@sec:two-by-two). We then read the constructions in equal-privacy slices, the only comparisons that are fair (@sec:equal-privacy-results), check the soundness arguments against deliberate cheating (@sec:soundness-validation), and finally draw the frontier the last chapter named (@sec:frontier-figure).

#section([Reading the Numbers Fairly], label: <sec:fairness-controls>)

A results chapter can mislead without a single wrong measurement. It is enough to compare two numbers that should never have been set side by side---a proof that hides the route against one that publishes it, the cost of changing the mechanism against the cost of changing everything at once, a wall-clock that shrank because the construction improved against one that shrank because more machines were thrown at it. Each of these is a fair-looking sentence built on an unfair comparison, and none of them involves an arithmetic mistake. So before any number is read, we fix three controls. They are simple to state and we state them here, at the front, so that the rest of the chapter can apply them without repeating itself.

#subsection([Compare Only Within a Privacy Class], label: <sub:control-class>)

The constructions do not all hide the same thing. @sub:privacy-ladder sorted them into classes by what an adversary learns of the partition: _structural_, where the partition is absent from the proof and hidden on no assumption, as in flat and recursion; _computational_, where it is present but sealed behind a commitment, as in the committed variants; and _disclosing_, where it sits on the surface in plaintext, as in the plain variants. These are not degrees of the same good. A proof that hides the route on no assumption and a proof that discloses it are answering different questions, and the prices they pay buy different things.

It follows that a cheaper number from one class is not a victory over a dearer number from another. The plain variants are cheap precisely because they hide nothing; reading their cost against recursion's and declaring them the winner would be reporting the discount for forgoing privacy as though it were an efficiency. So we never set a cost from one class against a cost from another as if the smaller simply won. Every comparison in this chapter is drawn _within_ a class---structural against structural, computational against computational---and where a cross-class number appears it is there to price the privacy itself, the gap between the classes, and is labeled as such. This is the discipline @sec:equal-privacy-results is built on, and the reason the frontier of @sec:frontier-figure has three corners rather than a single cheapest point.

#subsection([Change Exactly One Thing], label: <sub:control-one-thing>)

Every construction in the thesis is a point on a grid with two axes. One axis is the _regime_: how the proof is bound together---monolithic and whole (flat), or cut into segments and stitched, with the stitch left in the open (plain), sealed under a commitment (committed), or folded into a single recursive verification (recursion). The other axis is the _mechanism_: how the permutation at the heart of the statement is enforced---by sorting the cycle and checking the result, or by reducing it to a single grand-product fingerprint. The regime is the subject of @sec:stitching-tax; the mechanism is the subject of @sec:witness-inversion.

Laid out this way, a cause can be isolated by moving along one axis and holding the other fixed. Step down a _column_---change the regime, keep the mechanism---and whatever the cost does, it did so because the proof is bound differently; the delta is the price of aggregation, and nothing else moved to muddy it. Step across a _row_---change the mechanism, keep the regime---and the delta is the price of the fingerprint, the witness-time-against-gates inversion of @sec:witness-inversion read in isolation. What we do not do is change both at once. The diagonal step---a different regime _and_ a different mechanism---confounds the two prices into a single number from which neither can be recovered, and we treat it as forbidden.

This is not merely a reading convention; it is the discipline the figures of this chapter are drawn to make visible. The visual language fixes hue to the regime and marker to the mechanism, so that a legitimate comparison is one in which only the color changes, or only the marker, and the forbidden diagonal is exactly the step in which both change at once. When a later figure asks the reader to compare two curves, the grammar of the plot already says whether the comparison is a fair one.

#subsection([Report Both Clocks, and Say Which], label: <sub:control-both-clocks>)

The dualism of @sec:dualism established that decomposition conserves the prover's total work: cutting a proof into segments and stitching them never reduces the sum of the gates, it only relocates them and adds a tax for the relocation. And yet the entire motive for decomposing was a gain in time---segments that prove in parallel, each on a machine that need never hold the whole circuit. Both statements are true, and they are true of two different clocks. A single time can therefore flatter a construction or condemn it, depending on which clock the reader is invited to imagine.

So we report two, and we always label which is meant. The _total_ work is the sum of the cost across every piece---segments and stitch together---and it is the clock the dualism speaks to: decomposition never lowers it. The _parallel_ wall-clock is the time to finish when the segments run at once on separate machines, the longest segment plus the stitch that waits on all of them, and it is the clock on which the win actually appears. Conflating the two is the most natural way to claim a speedup the hardware delivered rather than the construction, or to miss one that is genuinely there; reporting only the total hides the parallel gain, reporting only the parallel hides the conserved cost it was bought with. Every timing in this chapter says, in so many words, which clock it stands on, and the wall-clock figures state the composition assumption they rest on---uncontended machines, one segment per prover---rather than leave it implied.

With the three controls fixed---compare within a class, move one axis at a time, name the clock---the numbers can be read without misleading. The first of them is the baseline the rest are read against, and we turn to it now.

#section([The Flat Baseline], label: <sec:flat-eval>)

The flat proof of @chap:methodology is the control: it is the whole statement proved in one circuit, and every construction that comes after is read as some multiple or fraction of it. Before those later numbers can mean anything we have to measure this one, and measure it in a way we can trust. So this section fixes how the measurements were taken, then reads the baseline's two costs in turn---the gates, which set the proving work, and the wall-clock and memory, which decide whether a single machine can carry the proof at all. Two facts surface along the way that bear on the whole thesis: a single hash inside the circuit costs far less than its textbook price, and the memory a flat instance demands runs into a hard ceiling not far past a thousand nodes.

#subsection([How the Baseline Was Measured], label: <sub:flat-setup>)

We sweep the instance size $n$ from $8$ to $4000$ nodes, finely at the small end where the curves bend and in wider steps past a thousand where they have straightened out. At each size the circuit is compiled once and then proved and verified two or three times over, on an otherwise idle machine---a four-core, eight-thread Intel Core i7-1165G7 with $16$ #lc[GB] of memory, running Barretenberg's UltraHonk prover (#inline[bb] $5.0$) behind the Noir compiler (#inline[nargo] beta-$20$). #footnote[The machine's memory ceiling matters for the wall this section ends at; if the benchmark host differs from the one quoted here, only the absolute memory and time figures move, not the scaling.]

Not every number we collect varies the same way, and the chapter reads more clearly once the two kinds are separated. The _structural_ metrics---the gate count, the ACIR opcode count, the proof size---are counted from the circuit rather than timed, and they are exact: across every repeat at every size their variation is precisely zero. The _wall-clock_ metrics---compile, witness, prove and verify time, and peak memory---are readings off a running machine and carry the noise of one, a few percent, largest at the smallest instances where fixed costs dominate and again at the largest where memory pressure does. We treat the two kinds as what they are. A structural count is reported as the single exact value it is; a time is reported as the mean over repeats, with the standing understanding that a two-percent wobble in a prove time is the machine talking, not the construction. When a later comparison turns on a small difference in time we say so plainly; when it turns on a gate count, we can simply be exact.

#subsection([Publishing the Matrix], label: <sub:flat-publish>)

The first cost the prover pays is the cost of the graph itself. The statement is about a weighted graph on $n$ nodes, and the most direct way to put its cost matrix in front of the circuit is to hand the whole thing over: all $n^2$ entries, as public inputs. Call this the _full_ representation. It is the right place to begin because its cost is the cost of the data and nothing more---no commitment, no hashing, just the matrix laid out in the open.

Measured, that cost is a clean quadratic. Across the entire sweep the gate count of the full-matrix flat proof, taken with the sort mechanism, fits

$ "gates"(n) = 7.25 thin n^2 + 26.5 thin n + 2829, quad R^2 approx 1 $ <eq:flat-full-fit>

and the fit is not an approximation that happens to be good---it is the structure of the circuit read back off the data. The leading term counts the matrix. Each of the $n^2$ public entries costs about $7.25$ UltraHonk gates to carry into the circuit, the fixed plumbing of a public input, the same for every entry; and at any appreciable $n$ those $n^2$ entries are the whole story. The linear term is the permutation and threshold work that grows with the tour, and the constant is the scaffolding every proof carries no matter how small.

That the quadratic term is the _matrix_ and not the _mechanism_ is worth pinning down, because the permutation check is the natural suspect for the expensive part, and it is innocent. Trade the sort mechanism for the pairwise one---which enforces the permutation with $n(n-1)$ explicit comparisons, a mechanism that is itself genuinely quadratic---and the leading coefficient moves only from $7.25$ to $8.25$. A quadratic _mechanism_, when one is used, adds a single gate per entry; the published _matrix_ costs seven. This is the column-against-row discipline of @sub:control-one-thing made concrete before we have even left the flat row: the representation of the graph dominates the cost of a flat proof, and the choice of mechanism is a correction on top of it. The lesson points straight at the next move. If carrying the graph in the open is what a flat proof mostly pays for, the first thing any serious construction will do is stop carrying it in the open---and that is the move we measure next.

#subsection([Committing the Matrix], label: <sub:flat-commit>)

To stop publishing the matrix is to _commit_ it. Rather than hand over all $n^2$ entries, the prover hashes the matrix into a single Merkle root, makes only that root public, and proves each cost the circuit needs by exhibiting a Merkle path---the entry, its sibling hashes, and the chain that climbs to the root. The matrix is now private behind one field element, and the circuit no longer pays for $n^2$ public inputs. It pays for hashing instead.

How much hashing is a counting question. Each of the $n$ directed edges in the tour reads one cost from the matrix, and checking that read against the root costs a path of $D$ hashes, where $D = ceil(log_2 n^2)$ is the height of a tree over the $n^2$ leaves. So the dominant cost is $n dot D$ Poseidon2 calls, and since $D$ grows like $2 log_2 n$, the whole proof grows as $O(n log n)$---for the first time the flat statement is proved in sub-quadratic work. The fit confirms the shape and hands us a coefficient worth pausing on:

$ "gates"(n) = 85.75 thin (n dot D) + 16 thin n + 2830, quad D = ceil(log_2 n^2), quad R^2 approx 1 $ <eq:flat-merkle-fit>

That leading coefficient is the price of one Poseidon2 call inside the circuit: about $86$ UltraHonk gates. This is the first of the section's two facts, and it is a surprise, because a single Poseidon2 permutation is usually costed at around $264$ gates---roughly three times what we measure. The gap is amortisation. UltraHonk proves a hash through a lookup argument, and the tables a Poseidon2 needs are built once for the whole circuit and then shared across every call; the fixed cost of standing the tables up is paid by the proof as a whole, and the marginal cost of one more hash is only the few lookups that read them. A circuit with a single hash would see something near the full $264$; a circuit with $n dot D$ of them---past $n = 100$, already tens of thousands---sees the amortised $86$. The committed flat proof is hashing-bound, and its hashing is cheap precisely because there is so much of it. The figure is worth carrying forward, because every committed and hierarchical construction in this thesis is built on Merkle openings, and the price of each opening is this measured $86$, not the textbook $264$.

Set the two representations side by side and their costs decompose cleanly (@tab:flat-cost): the full proof pays $7.25$ gates on each of $n^2$ matrix entries, the committed proof about $86$ on each of $n dot D$ hashes. A heavier coefficient on a lighter count---and which product is smaller depends entirely on $n$.

#figure(
  caption: [The two flat representations, decomposed. The full proof pays a light per-element cost on a quadratic count; the committed proof a heavy per-element cost on a log-linear count. Whether $86 thin (n dot D)$ or $7.25 thin n^2$ is the smaller is the crossover of @fig:flat-crossover.],
  table(
    columns: (auto, auto, auto, auto),
    align: (left, center, center, center),
    table.header([*representation*], [*per element*], [*element count*], [*class*]),
    [full (publish matrix)], [$7.25$ gates / entry], [$n^2$ entries], [$O(n^2)$],
    [Merkle (commit matrix)], [$approx 86$ gates / hash], [$n dot D$ hashes], [$O(n log n)$],
  ),
) <tab:flat-cost>

So the two representations cross. @fig:flat-scaling lays all four flat curves out at once: on log axes the committed proofs climb at the gentle log-linear rate and the full proofs at slope two, the two families fanning apart; on linear axes the quadratics overtake. At small $n$ the committed proof is the dearer of the two---a few thousand published entries cost less than the hashing to commit them, because $D$ is already a dozen levels deep while $n^2$ is still small. As $n$ grows the quadratic catches the log-linear and passes it for good. @fig:flat-crossover reads the meeting directly: between $n = 152$, where publishing still wins ($174$k gates against $201$k), and $n = 200$, where committing has pulled ahead ($298$k against $280$k), the two curves cross near $n approx 176$, where they sit within forty gates of each other---$232069$ against $232026$.

#figure(
  image("/assets/figures/01_flat_scaling.pdf", width: 100%),
  caption: [Gate scaling of the flat proof, across both matrix representation and permutation mechanism. The committed (Merkle) representations, in blue, climb at the log-linear rate of @eq:flat-merkle-fit; the full (publish) representations, in slate, at the quadratic rate of @eq:flat-full-fit. Left, on log axes, the slope is the complexity exponent and the two representations separate into two families; right, on linear axes, the same curves in absolute gates, where the quadratics overtake. Within a representation the mechanism---sort against product---is the small linear correction of @sub:flat-publish, all but invisible beside the choice of representation.],
) <fig:flat-scaling>

#figure(
  image("/assets/figures/02_flat_full_vs_merkle_crossover.pdf", width: 78%),
  caption: [Where committing the matrix overtakes publishing it, for the sort mechanism. The full representation (matrix public, quadratic) is cheaper only below the crossover at $n approx 176$; past it the Merkle representation (matrix committed, log-linear) wins and the gap widens without bound.],
) <fig:flat-crossover>

But the crossover is not where the decision is made, and saying so is the reason for measuring it. Even below $n = 176$, where publishing the matrix is the cheaper proof, the committed proof is the one the thesis builds on---because publishing the matrix _discloses the graph_, and the whole statement was meant to hide it. The crossover tells us that committing costs nothing asymptotically and little even at small instances; privacy tells us we would commit regardless. The canonical flat baseline, the control every later chapter is read against, is therefore the committed sort proof---_flat-sort_---at every size. The full representation was the instrument that let us see what the matrix costs and where the two representations trade; it was never a proof we would ship.

We now have the baseline's gates, and with them its shape: log-linear, hashing-bound, about $86$ gates a hash. What those gates cost in time and memory, and where that cost stops a single machine cold, is the reading the section closes on.

#subsection([Time, Memory, and the Wall], label: <sub:flat-wall>)

Gates are the structural cost, exact and machine-independent. What they become on a real prover---seconds and gigabytes---is the cost that decides whether the proof can be made at all, and it is the cost the rest of the thesis is organised around. @tab:flat-costs reads the committed baseline across the sweep.

#figure(
  caption: [The committed flat baseline (_flat-sort_) across the size sweep. Gates and proof size are exact; prove and verify times are means over repeats. Three things grow with the instance and two do not: the gate count and prove time climb together, peak memory climbs fastest of all, while the proof size is fixed and the verify time barely moves.],
  table(
    columns: (auto, auto, auto, auto, auto, auto),
    align: (right, right, right, right, right, right),
    table.header([*$n$*], [*gates*], [*prove (s)*], [*verify (ms)*], [*proof (B)*], [*peak (MB)*]),
    [8],    [7\,074],     [0.17],  [9],  [14\,656], [44],
    [256],  [358\,158],   [4.45],  [9],  [14\,656], [517],
    [1000], [1\,733\,830],[25.1],  [12], [14\,656], [2\,451],
    [3000], [6\,224\,830],[91.9],  [15], [14\,656], [9\,736],
    [4000], [8\,298\,830],[114.5], [29], [14\,656], [13\,262],
  ),
) <tab:flat-costs>

The prover's time follows the gate count almost exactly. From $n = 1000$ to $n = 3000$ the circuit grows $3.6$-fold, from $1.73$ to $6.22$ million gates, and the prove time grows $3.7$-fold, from twenty-five seconds to ninety-two; proving is linear in the size of the circuit, as UltraHonk's prover is, so prove time simply inherits the log-linear shape of the gates. A flat instance of a thousand nodes proves in about twenty-five seconds, three thousand in a minute and a half.

Two of the costs do not grow at all, and they are the ones the chapter will lean on later. The proof is $14\,656$ bytes at every size, from eight nodes to four thousand---a fixed length, the succinctness the proof system promises: the verifier downloads the same small proof whatever the instance. Verification is nearly as flat, a handful of milliseconds throughout, nine at the small end and rising only to fifteen at $n = 3000$. This is the $O(1)$ verifier the rest of the chapter measures everything against---flat's single cheap check, the one @sec:stitching-tax says the external hierarchical variants pay $K$-fold to give up and recursion buys back. We pin it here so that the later "$O(K)$ verifier" has a unit: one flat verification is milliseconds, and one flat proof is fifteen kilobytes.

The cost that grows, and the one that finally bites, is memory. Peak prover memory climbs with the circuit at roughly a kilobyte and a half per gate: half a gigabyte at $n = 256$, two and a half at $n = 1000$, nearly ten at $n = 3000$, and thirteen and a third at $n = 4000$. Set that last figure against the machine. The host holds sixteen gigabytes, and at four thousand nodes the prover is already using thirteen of them. There is no room to go much further. A flat instance of five or six thousand nodes does not prove slowly on this machine---it does not prove at all, because the prover cannot fit the circuit in memory. This is the _wall_. It is not a figure of speech but a measured ceiling, the largest flat instance the hardware will carry, and it is the reason everything after this section exists. Every construction the thesis goes on to build is, at bottom, an attempt to get past this one number: to prove a tour too large for a single prover by cutting it into pieces each small enough to fit, with room to spare. The dualism of @sec:dualism already warned that the cutting cannot lower the _total_ work; the wall is why one would cut anyway.

The flat baseline is now fully read---log-linear in its gates, hashing-bound at about $86$ a hash, succinct in proof and verifier, and walled by memory not far past a thousand nodes. One number remains, and it is a cautionary one: a metric the toolchain reports that looks like it measures cost and, read carelessly, does not.

#subsection([What the Opcode Count Hides], label: <sub:flat-acir>)

Alongside the gate count, the toolchain reports a second size: the ACIR opcode count, the number of operations the circuit compiles to _before_ arithmetization. It sits right next to the gate count in the output, it is smaller and tidier, and it is tempting to read as the circuit's true size. It is not the proving cost, and the gap between the two is worth a paragraph, because taking one for the other is the easiest way to draw a false conclusion from a correct measurement.

The trouble is that an opcode is not a gate, and different opcodes become different numbers of gates. Our own data shows it cleanly. By the opcode count, the pairwise mechanism looks _twice_ as expensive as sort: pairwise compiles to about $2 n^2$ opcodes, sort to about $n^2$, a clean two-to-one. By the gate count, the same two mechanisms sit within a seventh of each other, $8.25 n^2$ against $7.25 n^2$. The opcode count says pairwise costs double; the prover says it costs fourteen percent more. Both are right about what they measure. They disagree because the extra opcodes pairwise spends are multiplications---one opcode and one gate apiece---while the $n^2$ opcodes both mechanisms share are public inputs, one opcode but seven-and-a-quarter gates apiece. The opcode count weighs a multiplication and a public input the same; UltraHonk charges the input seven times more.

The hash is the sharpest form of the same effect. A Poseidon2 call is a single blackbox opcode, indivisible in the ACIR, and it expands to the scores of gates @sub:flat-commit measured. So a hashing-bound circuit---which the committed baseline is---carries an opcode count that badly understates its proving cost: a handful of opcodes per Merkle level standing in for the eighty-six gates each level truly costs. Count opcodes and the committed proof looks lean; prove it and the hashing is the entire bill.

The lesson is the plain one: know what a number measures before you trust it. The opcode count is a pre-arithmetization figure, a fair proxy for how large the circuit _description_ is and how long it takes to compile, but not for what it costs to prove. Proving cost lives in the gates, because the gates are what the prover commits to and what its time and its memory scale with. Gates are therefore the currency this chapter reports, and wherever a comparison could turn on the difference we use them and not opcodes.

Honesty adds one qualification, because this section's own central comparison happens _not_ to suffer the distortion. Full against Merkle crosses at the same $n approx 176$ whether it is read in opcodes or in gates, because a public input and a Merkle level happen to expand at nearly the same rate---$7.25$ gates against about $7.8$. That agreement is luck of composition, not a property of the metric, and the pairwise gap on the very same data shows how readily it breaks. The opcode count was right about the crossover here and would have been wrong about the mechanisms, and nothing in the number itself tells you which case you are in. Which is exactly why one reads the gates.

With that caution logged, the baseline is fully in hand: its scaling, its hashing cost, its succinct verifier, its memory wall, and the one number not to trust. Every construction the earlier chapters built was designed against this baseline. The next section is the first to set their _measured_ gates beside the predictions @chap:hierarchical made for them, and to ask whether the analysis and the prover agree.

#section([Gates Against the Predictions], label: <sec:gates-vs-prediction>)

@chap:hierarchical made two quantitative claims about the prover's gates, both reasoned from the shape of the constructions rather than measured: the _dualism_, that decomposition conserves the prover's total work and charges a tax to recombine, and the _fingerprint lever_, that swapping the sort mechanism for the product trades an expensive coverage check for a cheaper one. This section sets both against the measured gate counts. Both survive the test---and the measurement sharpens the second of them, settling a detail that a convenient one-line summary of the lever gets wrong and that @chap:hierarchical was careful not to.

#subsection([The Dualism, Measured], label: <sub:dualism-measured>)

The dualism of @sec:dualism has two halves, and they can be checked separately. The first is that the $K$ segments, taken together, simply redo the flat proof's work---each segment proving its $M = n\/K$ nodes, the $K$ of them summing back to the same $n$ the flat circuit proved. The second is that the glue is pure addition on top of that conserved work, the recombination the segments cannot do for themselves. Measure the segments alone and the first half is almost exact. At $n = 1000$ the $K$ segment circuits, summed, come to within a whisker of the flat gate count: a factor of $1.004$ of it at $K = 2$, $1.006$ at $K = 4$, $1.008$ at $K = 8$ for plain-sort, and tighter still, $1.001$ to $1.005$, for plain-product. The surplus is under a percent, and it is the per-segment scaffolding---the few thousand fixed gates every circuit carries, now paid $K$ times instead of once---not any growth in the real work. The books balance: split a cost proportional to $n$ into $K$ pieces and add the pieces back up, and the sum is $n$ again, with nothing saved and almost nothing lost. There was never a prize to win there, exactly as @sec:dualism argued.

So the whole of the excess over flat is the glue, and adding it back gives the total the dualism predicted: the conserved segment work, plus a tax to stitch it. @fig:dualism reads that total as a percentage of the flat baseline, and its first lesson is the one the dualism insisted on---every curve sits _above_ the hundred-percent line, at every $n$ and every $K$. The hierarchical total never dips beneath the flat one. There is no crossover, no instance size at which decomposing the proof costs fewer gates than proving it whole; the saving decomposition offers was never in the gate count, and the figure shows the floor holding without exception.

#figure(
  image("/assets/figures/04_dualism_total_work.pdf", width: 100%),
  caption: [Total hierarchical gates as a percentage of the flat baseline, by mechanism, for each variant and segment count $K$. The $100%$ line is the conservation floor: every curve sits above it, at every $n$ and $K$, so no decomposition spends fewer total gates than the flat proof. The tax shrinks as $n$ grows (the glue's fixed cost diluting) and rises with $K$ (more pieces to stitch). Committed-sort, in the left panel, is the exception that does not dilute: its $O(n)$ commitment re-fold rides at a roughly constant fraction of the circuit.],
) <fig:dualism>

How large the tax is, and how it moves, is the figure's second lesson, and it tracks the prediction closely. The tax shrinks as $n$ grows and swells as $K$ grows. Plain-sort cut into eight segments costs $8.3%$ over flat at $n = 256$ but only $1.7%$ at $n = 3000$: the glue's fixed costs, paid once per recombination, dilute against a segment workload that climbs with the instance. And more segments mean more to stitch---more boundary edges to prove, a longer coverage check to run---so at any fixed size the tax rises with $K$. The family's worst case is a small instance cut into many pieces, its best a large instance cut into few, and between them the tax is what @sec:dualism promised: a few percent where the sizes matter, and never, at any size, a saving.

One variant refuses to dilute, and @chap:hierarchical predicted which one. Committed-sort sits $7$ to $17%$ above flat and stays there---$12.5%$ at $n = 256$ and still $7.4%$ at $n = 3000$, where the other three have fallen toward a single percent. The cause is the re-fold the earlier chapter named: to open its commitments the committed-sort glue folds all $n$ of its node values a second time, an $O(n)$ cost riding at a roughly fixed fraction of an $O(n log n)$ circuit, so it holds its share rather than thinning. Committed-product, which folds only a handful of scalars per segment, behaves like the plain variants and dilutes to a third of a percent over flat. Among the four, then, committed-sort carries both the heaviest tax and the only one that does not fade with scale---the measured price of committing an _exact_ sort, precisely the asymmetry @chap:hierarchical drew between the two committed variants.

The dualism, then, holds in full and down to the percent: the segments conserve, the glue taxes, the total never falls below flat, and the one variant that should resist dilution does. The chapter's second gate claim, the fingerprint lever, is next---and it is the one the measurement does not merely confirm but sharpens.

#subsection([The Lever, Measured], label: <sub:lever-measured>)

The fingerprint lever swaps the sort mechanism for the product, and @chap:hierarchical traced two effects of the swap on the glue. The first is a shrinking of each segment's published surface, from a list of $M$ nodes to a single fingerprint scalar---$O(M)$ down to $O(1)$---which is a win the verifier feels but the glue's own gate count does not show, and which later sections collect. The second is a change in the glue's coverage check: where plain-sort's glue sorts all $n$ published node values and reads off $0$ through $n-1$, plain-product's glue folds them into a grand product instead. It is this second effect that the measurement is needed to pin down, because it is the easy one to overstate. The tempting summary is that the product makes coverage cheap by making it _small_---an $O(n)$ sort collapsed to an $O(K)$ handful of multiplications. That is not what happens, and @chap:hierarchical was careful to say so: the product glue still forms its target product over all $n$ values of ${0, dots, n-1}$, so its coverage is still $O(n)$, only of a cheaper kind. The gate counts settle which description is right, and it is the careful one.

The lever is a change of slope, not of class. Fit the glue against $n$ at a fixed four segments and both mechanisms come out linear in $n$: plain-sort's glue grows at about $19$ gates per node, plain-product's at about $2.8$---the same $O(n)$, a slope roughly seven times gentler. @fig:lever shows the two families of curves, the product's sitting well below the sort's and rising at a shallower angle, but rising: at every $K$ the product glue climbs with $n$ and never flattens into the constant an $O(K)$ coverage would give. The grand product touches all $n$ nodes exactly as the sort did. What the lever changed is not how many nodes the coverage visits but how much each visit costs.

That sevenfold gap is the witness inversion of @sec:witness-inversion, surfacing again at the recombiner. The sort's coverage is a dynamic, prover-steered permutation check---a read-only memory sorted and scanned---and every node it covers drags that machinery behind it, some nineteen gates' worth. The product's coverage is straight-line arithmetic, one multiplication per node into a running product, under three gates and no prover-chosen memory at all. Same length, different instrument: the lever does not shorten the coverage check, it cheapens every step of it, and cheapens the witness work behind each step by more still---the very inversion @sec:witness-inversion measured on the flat row, paying off a second time here at the glue.

There _is_ an $O(K)$ term in the glue, and naming it shows exactly what the convenient summary mistook. On top of the $O(n)$ coverage, every glue carries a cost that grows with the number of segments: the $K$ boundary edges joining one segment to the next, each proved against the committed root by its own Merkle path, for an $O(K dot D)$ contribution. Hold $n$ fixed and raise $K$ and the glue rises on that account alone---plain-product's from about $8.4$k gates at two segments to $18.8$k at eight. The summary that called the product glue "$O(K)$" had this term in hand and mistook the part for the whole; the coverage it left out is the larger contribution and the $O(n)$ one. The honest decomposition is a glue of three parts---an $O(n)$ coverage, an $O(K dot D)$ set of boundary edges, and a fixed remainder---with the lever acting on the slope of the first.

So the lever's worth is now exact. It does not lower the glue's complexity class; it cuts the coverage's per-node cost about sevenfold and strips the dynamic memory out of it, and---where the gate count cannot see---it shrinks each segment's published surface from $O(M)$ to $O(1)$, which is where the verifier-side savings of the sections ahead will come from. That cheaper glue is why plain-product carried the lighter tax of @sub:dualism-measured, and, once commitments enter, why committed-product's scalar re-fold dilutes where committed-sort's $O(n)$ re-fold will not. The lever is a constant-factor win where the gates can see it and a structural one where only the surface can; the figure that once summarised it as a change of order was reaching for the second saving and misnaming the first.

#figure(
  image("/assets/figures/05_fingerprint_lever_glue.pdf", width: 78%),
  caption: [Glue circuit size against $n$ for the two plain mechanisms, at each segment count $K$. Both grow $O(n)$---neither flattens---but the product glue (squares) climbs at about a seventh the per-node slope of the sort glue (circles): fitted at $K = 4$, about $2.8$ gates per node against about $19$. The lever cheapens each step of the coverage check rather than making the check asymptotically smaller; the upward shift with $K$ is the $O(K dot D)$ boundary-edge cost both glues share.],
) <fig:lever>

With the two gate predictions read---the dualism confirmed, the lever sharpened---the per-variant picture of the prover's _work_ is complete: it is conserved, taxed by a glue whose coverage the lever cheapens but does not shrink. What none of it has shown is the thing decomposition was actually for. Total work was never the point; time was. Whether cutting the proof into pieces and proving them at once on separate machines clears the wall @sec:flat-eval ended on is the next question, and the first the chapter asks of the clock rather than the gate.

#section([Proving in Parallel], label: <sec:parallel-proving>)

The wall of @sec:flat-eval was a wall of memory, and behind it of time: one prover holding one enormous circuit, until the circuit no longer fit. Decomposition's promise was to retire that single prover for $K$ small ones running at once, each holding only a piece. The previous section showed the promise costs something---a conserved total and a glue tax on top---but said nothing about whether it is kept. That is a question for the clock, and the clock answers in two parts: how much sooner the proof finishes when the segments run in parallel, which this section reads first, and how much less memory each prover needs, which it reads second and which is what truly clears the wall.

One point about method governs every number that follows. We did not run $K$ provers at once on one machine; doing so would have them fight over the same cores and memory bandwidth, and would measure the contention rather than the construction. We measured each proof alone on the full machine and compose the times as the distributed model prescribes: $K$ segments proved at once on $K$ machines finish when the slowest of them does, and the glue, which needs them all, runs after. The critical path is therefore the slowest segment's prove time plus the glue's. This is the ideal-parallel wall-clock, a compute-only upper bound on what the construction would deliver across $K$ uncontended machines---not what a single shared machine would---and we report it as exactly that.

#subsection([The Speedup, and Its Ceiling], label: <sub:speedup>)

Read the speedup as the flat prove time over the critical path (@fig:speedup-memory, left). At $n = 3000$ cut into eight segments, the plain-product proof finishes in $13.5$ seconds against the flat proof's $86$, a $6.4$-fold speedup, with committed-product matching it at $6.5$. The win grows with $K$---roughly $1.9 times$ at two segments, $3.5$ at four, $6.4$ at eight---and grows slightly with $n$ as well, the segments coming to outweigh the fixed per-proof costs.

It is not, however, the eightfold that eight segments might seem to promise, and the shortfall has two sources, both already in hand. The first is the dualism. Eight segments sum to a little _more_ than the flat proof's work, not less, and each carries its own fixed per-proof overhead that does not shrink with the piece; so the slowest segment at $K = 8$ takes not an eighth of the flat time but nearer a seventh, capping the segment-bound speedup around $6.7 times$ before the glue is even added. The second source is the glue, and it is where the mechanism at last reaches the clock.

The glue runs last and alone, on the critical path, and how long it takes is the fingerprint lever's bill come due. For the product variants it is almost nothing---half a second at the tail of a thirteen-second path, the cheap straight-line coverage of @sub:lever-measured. For the sort variants it is the $O(n)$ coverage sort, and sitting on the critical path it is a _serial_ tail that parallelism cannot touch: about seven seconds for plain-sort at $n = 3000$, eleven for committed-sort with its extra re-fold. That tail is the entire difference. The sort and product segments finish in essentially the same time, near twelve and a half seconds; yet plain-sort's speedup falls to $4.7 times$ and committed-sort's to $3.8$, each made to wait out a serial glue the product variants simply do not have. The lever's seven-fold-cheaper coverage, an abstraction in the gate count of @sub:lever-measured, is here a concrete five-to-eleven-second wait, and Amdahl's law converts it directly into lost speedup. The left panel of @fig:speedup-memory shows the consequence: the product curves press toward the ideal line, the sort curves bend away beneath them, and committed-sort, carrying the heaviest glue, bends furthest.

#figure(
  image("/assets/figures/07_speedup_and_memory_vs_K.pdf", width: 100%),
  caption: [Parallel proving at $n = 3000$, against the flat baseline, versus segment count $K$. Left: speedup, the flat prove time over the critical path (slowest segment plus glue). Right: per-prover peak memory reduction. The product variants (squares) approach the ideal $K times$ in both; the sort variants (circles) are capped---by the glue's serial $O(n)$ coverage sort in time, by the glue's $O(n)$ footprint in memory---and committed-sort, with the heaviest glue, falls furthest in each. Isolated per-proof measurements composed as the distributed model prescribes (uncontended machines): a compute-only upper bound.],
) <fig:speedup-memory>

So the clock's first reading is that decomposition does buy speed---most of the ideal $K times$ with the product mechanism, appreciably less with the sort---and buys all of it in the segments, the glue only ever giving some back. The second reading is memory, the quantity the wall was really about, and there the same split returns in a sharper form.

#subsection([Clearing the Wall], label: <sub:memory-wall>)

The wall was a wall of memory, so memory is the reading that decides whether decomposition kept its promise (@fig:speedup-memory, right). For the product variants the per-prover peak falls almost as cleanly as the speedup rose: at $n = 3000$ cut into eight, each prover holds about $1.1$ #lc[GB] against the flat proof's $8.3$, a $7.3$-fold reduction, near the ideal eight. And this is a genuine _per-process_ reduction---not the total memory summed and divided, but the most any single prover ever holds at once---because each segment is an $n\/K$-node circuit and nothing makes a prover hold more than its own piece, the product glue being far too light to be the peak. Total work, the dualism showed, decomposition cannot cut. Memory it can.

Cutting it is what clears the wall. Recall @sec:flat-eval: the flat prover ran out of room not far past four thousand nodes, holding thirteen of its sixteen gigabytes at $n = 4000$ and unable to go further. Decomposed into eight product segments, that same proof asks about $1.7$ #lc[GB] of each prover at $n = 4000$, and a tour of _five thousand_ nodes---which the flat prover cannot prove at all on this machine---comes within reach at under two gigabytes apiece. The wall @sec:flat-eval ended on is not pushed back but stepped over: a tour too large for any single prover is proved by provers none of which ever holds a circuit near the limit. This was decomposition's real promise, and for the product mechanism it is kept in full.

For the sort mechanism it is not, and the right panel of @fig:speedup-memory shows the failure plainly: the sort variants' memory reduction lies flat against $K$, about twofold and no better, whether the tour is cut into two pieces or eight. More segments buy nothing, and the reason is again the glue, now in space rather than time. The sort glue is an $O(n)$ circuit---its coverage sort holds all $n$ node values at once---so its footprint does not shrink when the segments do, and the per-prover peak is set not by the segment but by the glue, fixed by $n$ and untouched by $K$. Worse, that footprint grows with $n$ exactly as the flat proof's did: about nine gigabytes at four thousand nodes, nearly thirteen at five thousand---back at the wall. Decomposing with the sort mechanism does not clear the memory wall. It moves the wall from the monolithic prover to the glue prover and leaves it standing at the same height. The product mechanism steps over the wall; the sort mechanism rebuilds it in the seam.

So both readings of the clock agree, and they agree on the mechanism. Decomposition delivers what it promised---most of the $K times$ in speed, most of it in memory, the wall cleared and instance sizes reached that the flat prover cannot touch---but only through the product fingerprint, whose $O(1)$ surface leaves a glue light enough, in both time and memory, to stay off the critical path and out of the prover's footprint. The sort mechanism's $O(n)$ glue caps the speedup, pins the memory, and at large $n$ re-erects the very wall decomposition set out to clear. The fingerprint lever of @sub:lever-measured, weighed in gates as a sevenfold cut to a single term, is weighed here at its true worth: it is the difference between a decomposition that clears the wall and one that only appears to. With the external family's costs now read on every axis---gates, time, and memory---one construction remains unmeasured, the one that moved the stitch inside; and to place it, and to separate the cost of aggregating from the cost of the mechanism it has been tangled with all along, the next section turns to a small controlled factorial.

#section([Aggregation versus Mechanism], label: <sec:two-by-two>)

Recursion is the last construction to measure, and measuring it fairly takes more care than the others, because of a confound built into the family. Recursion ships with a product inner---@chap:hierarchical showed it has no choice, the sort inner's published surface being exactly what the outer cannot afford---while flat ships with sort. So the two constructions a deployer would actually compare, flat-sort and recursive-product, differ in _two_ things at once: the regime, monolithic against recursively aggregated, and the mechanism, sort against product. Set their gate counts side by side and the difference is real but uninterpretable, two changes folded into one number---precisely the forbidden diagonal of @sub:control-one-thing, the comparison the chapter's second control forbids.

The cure is to fill in the grid. We measure all four cells of the $2 times 2$---both regimes crossed with both mechanisms---including the two that ship nowhere: flat-product, a flat proof carrying a fingerprint it has no reason to, and recursive-sort, recursion built on the very inner @chap:hierarchical ruled out. Neither is a construction anyone would deploy; both exist only to complete the factorial, so that the cost of changing the regime can be read down the columns with the mechanism held fixed, and the cost of changing the mechanism across the rows with the regime held fixed. They are controls, in the strict sense, and with them in place the two effects come apart cleanly.

#subsection([The Factorial], label: <sub:factorial>)

@tab:factorial lays the four cells out at $n = 1000$ and eight segments, and the asymmetry between the two readings is the whole point. Down a column---hold the mechanism, change flat to recursive---the gate count leaps by about six million, and it leaps by almost exactly the same six million for either mechanism: $6.15$ million for sort, $6.10$ for product. Across a row---hold the regime, change sort to product---it moves by a few tens of thousands: $61$ thousand at flat, a mere $9$ thousand under recursion. The aggregation cost is two orders of magnitude the mechanism cost, and it does not care which mechanism it aggregates.

#figure(
  caption: [The $2 times 2$ factorial of total gates at $n = 1000$, $K = 8$: regime (flat / recursive) crossed with mechanism (sort / product). The margins give the deltas. The column delta is the cost of aggregating, the row delta the cost of the mechanism; the former is mechanism-blind and about a hundred times the latter. flat-product and recursive-sort ship nowhere---they are controls, present only to de-confound the diagonal flat-sort\/recursive-product comparison.],
  table(
    columns: (auto, auto, auto, auto),
    align: (left, right, right, right),
    table.header([], [*sort*], [*product*], [*row $Delta$*]),
    [*flat*],            [$1.73$ M], [$1.79$ M], [$+61$ k],
    [*recursive*],       [$7.88$ M], [$7.89$ M], [$+9$ k],
    [*col $Delta$*],     [$+6.15$ M], [$+6.10$ M], [],
  ),
) <tab:factorial>

That asymmetry de-confounds the comparison a deployer cares about. Flat-sort to recursive-product is a jump from $1.73$ to $7.89$ million gates, a $4.5$-fold blow-up, and it would be easy to read some of that as the price of the product mechanism. It is not: of the $6.16$ million added, $6.10$ million is aggregation and $60$ thousand is mechanism. Recursion's cost is the aggregation, full stop; the mechanism it is forced to adopt is, at this scale, a rounding error. And the factorial says why the cost is so large. The recursion total decomposes as the inner segments plus the outer, and the inner segments are just the dualism's conserved work again---$K$ of them sum to about $1.8$ million gates, within a few percent of the flat proof they replace. The entire remainder, the whole six million, is the outer: a single circuit that verifies $K$ proofs inside itself, and that alone runs to roughly three and a half times the flat proof it sits on top of. No other construction in the family aggregates by re-proving; this one does, and the factorial measures the bill.

So the dualism reaches its most extreme form here, and the controls were what let us see it. Recursion conserves the segment work like every variant before it, then spends, on the recombination alone, several times the cost of the whole original proof. The mechanism, which mattered so much to the glue of the external family and to the wall of @sec:parallel-proving, barely registers against an aggregation cost this size---which is the factorial's quiet second lesson, that the same product mechanism that was decisive a section ago is nearly invisible here, swamped by the outer it rides inside. What that outer buys for its enormous price, and why it must be the product inner that goes into it, is the reading the section turns to now.

#subsection([The Outer Proof], label: <sub:outer-proof>)

The outer costs six million gates, and the first thing it buys is the verifier back. @sec:stitching-tax named a tax the external family pays not on the prover but on the verifier: where flat hands over one proof and runs one check, the external variants hand over $K + 1$ proofs and reconcile them in $K$ further rounds, a download and an effort that both grow with the number of segments. @fig:verifier-tax measures it. At eight segments the external verifier downloads nine proofs, about a hundred and thirty kilobytes against flat's fifteen, and its work rises with $K$. Recursion erases the tax. Its verifier downloads one proof, the outer, fifteen kilobytes like flat's, and checks it in twelve milliseconds---flat's figure to the millisecond, and flat in $K$, unmoved as the segment count climbs. The outer's vast prover cost has purchased, on the verifier's side, a clean return to the baseline: one small proof and one cheap check, however many pieces the tour was cut into. This is the stitching tax of @sec:stitching-tax paid off in full, by the prover, on the verifier's behalf.

#figure(
  image("/assets/figures/09_verifier_tax_vs_K.pdf", width: 100%),
  caption: [The verifier-side stitching tax at $n = 1000$, versus segment count $K$. Left: the proof bytes the verifier downloads. Right: verification wall-clock. The external hierarchical variants hand over $K + 1$ proofs and reconcile them, both $O(K)$; recursion hands over one outer proof and flat one monolithic proof, both $O(1)$. Recursion's verifier is flat's---to the kilobyte and the millisecond, unmoved by $K$---the single cheap check the outer's prover cost bought back.],
) <fig:verifier-tax>

The outer earns that single check by verifying the $K$ inner proofs inside itself, and the cost of each in-circuit verification turns on one quantity: how much the inner proof makes public. The outer must bind every public input of every inner proof it checks, so an inner with a wide public surface makes a wide outer and one with a narrow surface a narrow one. Here the mechanism the factorial found nearly invisible becomes decisive again, one layer down. @sub:forced-inner argued the choice; @fig:recursion-mindep measures it. The product inner publishes $O(1)$---a handful of scalars---so the outer's cost per verified segment is flat in the segment size: about seven hundred and sixty thousand gates whether the tour runs to two hundred nodes or three thousand. The sort inner publishes its node list, $O(M)$, so the outer's per-segment cost climbs with $M$, steepest where the segments are largest. The divergence is modest across the sizes measured---a few percent in gates, widening to about half again as much in the outer's memory by five thousand nodes---but its direction is the whole point, and it only grows: the product inner holds the outer flat in $n$, the sort inner does not. Recursion was forced onto the product inner for exactly this reason, and the figure is that reason made quantitative.

But flat in $n$ is not the same as cheap, and the outer's true cost is the one the other panel of @fig:recursion-mindep shows. The outer is a single circuit and a heavy one---six million gates, eight gigabytes of prover memory at eight segments---and it does not parallelize. The inner segments spread across machines exactly as the external family's did, each small and held alone; the outer does not. It is one proof verifying all $K$ at once, its memory rising with $K$ at roughly a gigabyte a segment, and at eight segments it stands at eight gigabytes---back within sight of the very wall @sec:flat-eval ended on. So recursion's relation to the wall splits in two. Its segments clear the wall as cleanly as any product decomposition; its finish walks back toward it. Where the sort mechanism re-erected the wall in an $O(n)$ glue, recursion re-approaches it in a monolithic outer that grows with $K$---a different cause, the same shape, and the steepest the chapter has measured.

#figure(
  image("/assets/figures/08_recursion_M_independence.pdf", width: 100%),
  caption: [Recursion's outer proof against instance size $n$, by mechanism and segment count $K$ (marker = mechanism, linestyle = $K$). Left: outer gates per verified segment. Right: outer prover peak memory. The product inner (squares) publishes an $O(1)$ surface, so the outer is flat in $n$ at every $K$; the sort inner (circles) publishes $O(M)$, so the outer grows with the segment, most steeply where segments are largest (small $K$). The divergence is modest at these sizes but widens with $n$. Note the absolute memory scale: the outer climbs with $K$ to about eight gigabytes at eight segments, a monolithic finish that does not parallelize.],
) <fig:recursion-mindep>

So the outer's price is fully counted. For its six million gates and its un-parallel eight-gigabyte finish, recursion buys the verifier back to flat---one proof, one cheap check, $O(1)$ in the segments---and, as the next section shows, buys the partition's secrecy outright. It is the most expensive construction in the family by a wide margin: its cost almost entirely the aggregation, its mechanism forced and then nearly irrelevant, its finish monolithic and near the wall. @chap:hierarchical called recursion the steepest corner of the pick-two triangle and the one a folding scheme would smooth; the measurements bear the description out to the gate. What recursion buys with all of this, set beside what the cheaper constructions buy and what they do not, is the privacy reading---the last the chapter owes, and the one its first control was written to make fair.

#section([Equal-Privacy Comparisons], label: <sec:equal-privacy-results>)

The first control of @sec:fairness-controls forbade setting a cost from one privacy class against a cost from another. We have now measured every construction's gates, time, and memory; the way to read those costs fairly is to sort the constructions by what they hide and weigh each class on its own. The ladder of @sub:privacy-ladder gives three classes. The _disclosing_ class holds the plain variants, their partition in plaintext. The _computational_ class holds the committed variants, their partition sealed behind a commitment. The _structural_ class holds flat and recursion, their partition absent from the proof entirely. Within a class the privacy is equal, so cost may be set against cost and the comparison is fair; across classes, the comparison instead prices the privacy. This section reads within first, then across.

#subsection([Within a Class], label: <sub:within-class>)

In the _disclosing_ class, neither plain variant dominates. On total gates plain-sort is the cheaper, by a small and steady margin---plain-product costs about two percent more at every $(n, K)$ measured (@fig:f7). But @sec:parallel-proving showed the other side of the ledger: plain-product parallelizes to $6.4 times$ where plain-sort caps at $4.7$, and clears the memory wall where plain-sort rebuilds it. So the choice inside the disclosing class is the chapter's central tradeoff in miniature, two percent of total gates set against the whole of the parallel win. Neither is best; each buys the one thing with the other.

#figure(
  image("/assets/figures/06_F7_sort_not_dominated.pdf", width: 70%),
  caption: [Plain-product's total gates as a percentage above plain-sort's, by segment count $K$. Plain-product costs a steady two percent or so more at every $(n, K)$: on _total_ gates, plain-sort is the cheaper of the two disclosing variants. Its parallel-time and memory advantages (@sec:parallel-proving) run the other way, so within the disclosing class neither dominates.],
) <fig:f7>

Climb to the _computational_ class, the two committed variants, equal in what they hide---@sub:equal-privacy established the partition equally opaque behind either commitment---and the comparison sharpens, and reverses. Where plain-product cost two percent _more_ than plain-sort, committed-product costs about four percent _less_ than committed-sort. Committing flipped the order, and the reason is the re-fold @sub:dualism-measured measured: to open its commitment, committed-sort folds all $n$ of its nodes a second time, an $O(n)$ cost, while committed-product folds a handful of scalars. So the privacy-equalized comparison is not close. Committed-product is the cheaper on total gates and parallelizes to $6.5 times$ where committed-sort caps at $3.8$; within the computational class it dominates on cost and on time at once. Committed-sort holds a single advantage against it, the exact and unconditional coverage its sort delivers where committed-product leans on Schwartz--Zippel. Inside this class the choice is no longer cost against parallelism but cost-and-parallelism against soundness.

The _structural_ class holds flat and recursion, the two that hide the partition on no assumption---flat by never dividing, recursion by dividing and then hiding the division. Here the two are not near each other at all. Flat is the cheapest construction in the family, $1.7$ million gates, and the most confined: it cannot be split, and it runs into the wall past four thousand nodes. Recursion is the dearest, $7.9$ million with its monolithic outer, and the most capable: its segments clear the wall and reach instances flat cannot touch. So within structural privacy the choice is not a few percent but a fork in kind---pay little and stay beneath the wall, or pay several times over and scale past it. Neither dominates; they answer to different needs.

Three classes, then, and within each a genuine tradeoff rather than a winner: the disclosing class trades gates for parallelism, the computational trades soundness for cost, the structural trades cost for scale. What the within-class readings leave open is the across-class one---how much it costs to climb the ladder, and whether every rung is worth standing on. That reading is next, and it takes two of the five constructions out of contention.

#subsection([The Price of Privacy], label: <sub:price-of-privacy>)

Climbing from the disclosing rung to the computational one---plain to committed---means committing the shared values and re-folding them to open the commitment, and what that costs depends, like everything else in the chapter, on the mechanism. For the product variants the re-fold is a handful of scalars, and committing is almost free: committed-product is dearer than plain-product by three-tenths of a percent at a thousand nodes and a tenth at three thousand---privacy bought, to measurement precision, for nothing. For the sort variants the re-fold is the whole node list, an $O(n)$ cost, and committing runs six to seven percent. The price of the computational rung is set by the fingerprint, then, near-zero for the product and six-or-seven percent for the sort: the same lever that bought a cheap glue in @sub:lever-measured and the parallel win in @sec:parallel-proving here buys cheap privacy.

That near-zero price has a consequence that clears two constructions from the deployable set. Committed-product costs three-tenths of a percent more than plain-product and hides the partition that plain-product lays in the open; on every other axis---parallel time, per-prover memory, soundness---the two are identical. So committed-product dominates plain-product outright: no instance, no segment count, no priority makes plain-product the better pick, because committed-product is the same proof that also hides. And it dominates plain-sort nearly as cheaply, costing about two percent more in gates but parallelizing to $6.5 times$ where plain-sort manages $4.7$, clearing the wall plain-sort cannot, and hiding what plain-sort discloses. The plain variants are dominated, in short, not by some distant construction but by the committed one a single rung above them, available for a rounding error in cost. They were never destinations---only the rungs the chapter climbed to reach the rest---and the measurements confirm what @sub:pick-two argued from the constructions' shapes: a leaking proof is out of contention the moment a hiding one costs the same.

So the five constructions reduce to three deployable ones, and they are exactly the survivors of the three privacy classes. The disclosing class empties, both its members dominated. The computational class keeps committed-product, with committed-sort surviving beside it only as an exact-coverage variant for a deployer who will not rest on Schwartz--Zippel---a soundness option, not a separate corner. The structural class keeps both flat and recursion, which @sub:within-class showed are no substitutes for each other, the one cheap and walled and the other dear and scaling. Three points are left standing: flat, committed-product, and recursion---one cheap and structurally private but unable to split, one cheap and parallel but private only computationally, one structurally private and parallel but the costliest by far. Each holds two of the three goods and yields the third. The pick-two triangle @chap:hierarchical drew from the constructions' shapes is, measured, exactly these three points, and drawing it is the chapter's last figure.

Before that, though, a third axis the cost readings have set aside deserves its own check. A deployer trusts a construction for what it proves as much as for what it costs and hides, and soundness the chapter has so far taken on the constructions' design and @chap:hierarchical's analysis. The frontier should not be drawn over claims left untested, so the next section tests them---not by reproving the constructions, but by trying to cheat them.

#section([Validating Soundness], label: <sec:soundness-validation>)

@sub:soundness-reductions and @app:soundness argued each construction's soundness as a reduction: any prover that passed on a false witness would have to have broken the proof system or one of its primitives. That argument is the load-bearing one, and this section does not replace it. It does something narrower and complementary---it tests the argument against concrete cheats, checking that each construction rejects the witnesses the reduction says it must, and at the place the reduction says it will. This is validation, not proof: a finite battery of attempted forgeries, not a quantification over all of them. What it can catch is a gap between the analysis and the circuit---a constraint the reduction assumes but the implementation omits---and that is worth catching before the frontier is drawn over it.

The technique is uniform across the family. Start from a valid witness, a real sub-threshold cycle that the construction accepts, and corrupt it in exactly one way, each corruption aimed at a single soundness mechanism: push a node out of range, have two segments claim the same node, tamper an edge's cost or its Merkle path, set the threshold below the true cost, break one of the boundary edges, or---for recursion---tamper an inner proof. Then run the construction and confirm the corruption is rejected. Where the rejection lands is itself part of what we check, because the reduction predicts it. Most cheats violate an in-circuit assertion and are caught at witness generation, when #inline[nargo execute] returns a failure---the encoding lemmas of @app:soundness doing their work directly. A cheat against the external stitch is subtler: each segment proof is individually valid, so it passes execution, and only the off-circuit cross-check catches the mismatch---rejection in verifier code, the trust surface @sub:soundness-reductions flagged as audited rather than probabilistic. And a tampered recursive proof passes witness generation entirely, only to make the prover unsatisfiable: it is caught at #inline[bb prove] by the in-circuit verifier, the one cheat that reaches the heaviest layer.

#figure(
  caption: [The consolidated negative-test battery: each cheat, the soundness mechanism it attacks, and the layer at which the construction rejects it. The in-circuit constraint groups reject at witness execution; the external stitch rejects in off-circuit verifier code; recursion's in-circuit verifier rejects only at proving. The full per-construction battery---each corruption and its exit code---is collected in a dedicated appendix.],
  table(
    columns: (auto, auto, auto),
    align: (left, left, left),
    table.header([*cheat*], [*mechanism attacked*], [*caught at*]),
    [out-of-range node],            [range check (group 1)],                 [execute],
    [duplicate / overlapping node], [coverage --- sort or grand product (group 2)], [execute],
    [tampered cost, path, or root], [matrix commitment (group 3)],           [execute],
    [cost above threshold],         [threshold (group 4)],                   [execute],
    [broken boundary edge],         [inter-segment join],                    [execute],
    [segments mixed across cycles], [external cross-check],                  [verifier code],
    [tampered inner proof or key],  [recursive verification],                [prove (#inline[bb])],
  ),
) <tab:negatives>

@tab:negatives consolidates the battery, and the pattern in its last column is the result. Every soundness mechanism the reduction names is probed by a cheat built to exploit it, and every cheat is rejected---each at the layer its mechanism lives in. The range, coverage, commitment, and threshold checks all reject at execution, exactly the in-circuit constraints the encoding lemmas describe. The external cross-check rejects a cross-segment forgery in verifier code, bearing out the reduction's claim that the stitch adds a line of audited code rather than a term of error. And recursion's in-circuit verifier rejects a tampered inner proof at proving time, the empirical face of the $epsilon_"rec"$ the reduction carries. None of this proves the constructions sound; a battery of chosen cheats never could. But it exercises every mechanism the analysis leans on, finds each one closed at the layer predicted, and so turns up no gap between the reduction and the circuits that implement it---which is the most a test, as opposed to a proof, can offer.

With cost measured, privacy classed, and soundness checked against every cheat we could devise, the three axes a deployer weighs are all in hand. The three constructions left standing after @sub:price-of-privacy, namely flat, committed, and recursion, can at last be set into a single picture, each at the corner it pays for and none at the center. That picture is the chapter's last, and the frontier the whole of it has been building toward.
