#!/usr/bin/env bash
# End-to-end recursion test:
#   1. Compile + prove the inner circuit (x^2 == y) with noir-recursive-no-zk
#   2. Extract proof/VK fields from JSON output
#   3. Build outer Prover.toml and execute the outer recursive verifier circuit
#
# Requires: nargo (1.0.0-beta.20+) and bb (5.0.0-nightly.20260324+)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INNER="$SCRIPT_DIR/inner"
OUTER="$SCRIPT_DIR/outer"

# ── 1. Inner circuit ────────────────────────────────────────────────────────
echo "==> Compiling inner circuit..."
(cd "$INNER" && nargo compile)

echo "==> Executing inner circuit (witness)..."
(cd "$INNER" && nargo execute)

echo "==> Writing VK (binary + JSON)..."
bb write_vk \
    -b "$INNER/target/inner.json" \
    -t noir-recursive-no-zk \
    -o "$INNER/target/vk"

bb write_vk \
    -b "$INNER/target/inner.json" \
    -t noir-recursive-no-zk \
    --output_format json \
    -o "$INNER/target/vk_json"

echo "==> Proving inner circuit (noir-recursive-no-zk)..."
bb prove \
    -b "$INNER/target/inner.json" \
    -w "$INNER/target/inner.gz" \
    -k "$INNER/target/vk/vk" \
    -t noir-recursive-no-zk \
    --output_format json \
    --verify \
    -o "$INNER/target/proof_json"

echo "==> Proof self-verified OK"

# ── 2. Build outer Prover.toml ──────────────────────────────────────────────
echo "==> Generating outer Prover.toml..."
INNER="$INNER" OUTER="$OUTER" python3 - <<'PYEOF'
import json, os

inner_target = os.path.join(os.environ["INNER"], "target")
outer_dir    = os.environ["OUTER"]

with open(os.path.join(inner_target, "proof_json", "proof.json")) as f:
    proof_data = json.load(f)
with open(os.path.join(inner_target, "vk_json", "vk.json")) as f:
    vk_data = json.load(f)
with open(os.path.join(inner_target, "proof_json", "public_inputs.json")) as f:
    pi_data = json.load(f)

proof_fields = proof_data["proof"]          # list of 410 hex strings
vk_fields    = vk_data["vk"]                # list of 115 hex strings
key_hash     = vk_data["hash"]              # single hex string
public_inputs = pi_data["public_inputs"]    # list of 1 hex string (y=9)

assert len(proof_fields) == 410, f"expected 410 proof fields, got {len(proof_fields)}"
assert len(vk_fields) == 115,    f"expected 115 VK fields, got {len(vk_fields)}"

def toml_array(fields):
    inner = ", ".join(f'"{f}"' for f in fields)
    return f"[{inner}]"

toml = f"""# Auto-generated by run_test.sh — do not edit by hand

verification_key = {toml_array(vk_fields)}
proof            = {toml_array(proof_fields)}
public_inputs    = {toml_array(public_inputs)}
key_hash         = "{key_hash}"
"""

out_path = os.path.join(outer_dir, "Prover.toml")
with open(out_path, "w") as f:
    f.write(toml)

print(f"  Written {out_path}")
print(f"  proof_fields={len(proof_fields)}, vk_fields={len(vk_fields)}, key_hash={key_hash}")
PYEOF

# ── 3. Compile + execute outer circuit ─────────────────────────────────────
echo "==> Compiling outer circuit..."
(cd "$OUTER" && nargo compile)

echo "==> Executing outer circuit (recursive verify)..."
(cd "$OUTER" && nargo execute)

echo ""
echo "SUCCESS: outer recursive verifier accepted the inner proof."
